name: platform_engine_sdk
description: Common contract that every inference engine implements.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  platform_pipeline:
    path: ../platform_pipeline
  flutter:
    sdk: flutter
  platform_core:
    path: ../platform_core

  mocktail: ^1.0.3
dev_dependencies:
  platform_pipeline:
    path: ../platform_pipeline
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
