// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mind.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `minutes_prompt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Library`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Loads both models and opens the store. Safe to call again — a Flutter hot
/// restart runs it a second time, and refusing would make development require a
/// full relaunch.
///
/// A missing model is an ordinary error carrying the path, because on a real
/// device it is the most likely failure and the user can act on it.
Future<void> initialize({required MindConfig config}) =>
    RustLib.instance.api.crateApiMindInitialize(config: config);

/// True once `initialize` has succeeded. Lets the UI show why it cannot record
/// instead of failing at the moment the user presses the button.
bool isReady() => RustLib.instance.api.crateApiMindIsReady();

/// Recording → transcript → minutes → saved, streaming throughout.
///
/// The whole of steps 2–5 of the milestone journey. Runs on a
/// `flutter_rust_bridge` worker thread, never the Dart main isolate.
Stream<ProcessingEvent> processRecording({
  required String wavPath,
  required String title,
  required BigInt recordedAtMs,
}) => RustLib.instance.api.crateApiMindProcessRecording(
  wavPath: wavPath,
  title: title,
  recordedAtMs: recordedAtMs,
);

/// Stops the in-flight job at the next segment or token.
void cancelProcessing() => RustLib.instance.api.crateApiMindCancelProcessing();

/// Every meeting, newest first.
Future<List<MeetingRecord>> listMeetings() =>
    RustLib.instance.api.crateApiMindListMeetings();

/// Step 7 of the journey. Searches transcripts and minutes.
Future<List<SearchHit>> searchMeetings({required String query}) =>
    RustLib.instance.api.crateApiMindSearchMeetings(query: query);

/// Step 8. Opens one meeting.
Future<MeetingRecord?> getMeeting({required String id}) =>
    RustLib.instance.api.crateApiMindGetMeeting(id: id);

/// A stored meeting, flattened for the bridge.
///
/// Deliberately not `crate::Meeting` re-exported: the wire contract and the
/// storage record are allowed to diverge, and coupling them means a storage
/// change becomes a Dart change.
class MeetingRecord {
  final String id;
  final String title;
  final BigInt recordedAt;
  final String transcript;
  final String minutes;
  final String model;

  const MeetingRecord({
    required this.id,
    required this.title,
    required this.recordedAt,
    required this.transcript,
    required this.minutes,
    required this.model,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      recordedAt.hashCode ^
      transcript.hashCode ^
      minutes.hashCode ^
      model.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          recordedAt == other.recordedAt &&
          transcript == other.transcript &&
          minutes == other.minutes &&
          model == other.model;
}

/// Where the models and the store live. Supplied by Dart, which owns the
/// platform's notion of an application directory.
class MindConfig {
  /// Where the Model Manager looks. **Not** a model path — `ADR-0018 §4`
  /// says nothing above the Manager names a file, a quantisation or a
  /// runtime, and this type is above the Manager.
  final String modelsDir;
  final String storePath;

  /// Admission ceiling for the Supervisor (`C6`). A device that cannot afford
  /// the model is told so before anything allocates.
  final int memoryBudgetMb;

  const MindConfig({
    required this.modelsDir,
    required this.storePath,
    required this.memoryBudgetMb,
  });

  @override
  int get hashCode =>
      modelsDir.hashCode ^ storePath.hashCode ^ memoryBudgetMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MindConfig &&
          runtimeType == other.runtimeType &&
          modelsDir == other.modelsDir &&
          storePath == other.storePath &&
          memoryBudgetMb == other.memoryBudgetMb;
}

@freezed
sealed class ProcessingEvent with _$ProcessingEvent {
  const ProcessingEvent._();

  /// One transcript segment, as whisper produced it.
  const factory ProcessingEvent.transcribing({required String text}) =
      ProcessingEvent_Transcribing;

  /// The joined transcript. The UI can stop appending and start displaying.
  const factory ProcessingEvent.transcriptReady({required String text}) =
      ProcessingEvent_TranscriptReady;

  /// One token, as llama produced it.
  const factory ProcessingEvent.generating({required String text}) =
      ProcessingEvent_Generating;
  const factory ProcessingEvent.minutesReady({required String text}) =
      ProcessingEvent_MinutesReady;

  /// Durable. Only after this is the meeting reopenable.
  const factory ProcessingEvent.saved({required String meetingId}) =
      ProcessingEvent_Saved;

  /// The user navigated away. Nothing was saved.
  const factory ProcessingEvent.cancelled() = ProcessingEvent_Cancelled;
}

/// A search result, with the line that matched.
class SearchHit {
  final String meetingId;
  final String title;
  final BigInt recordedAt;
  final String snippet;

  const SearchHit({
    required this.meetingId,
    required this.title,
    required this.recordedAt,
    required this.snippet,
  });

  @override
  int get hashCode =>
      meetingId.hashCode ^
      title.hashCode ^
      recordedAt.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          meetingId == other.meetingId &&
          title == other.title &&
          recordedAt == other.recordedAt &&
          snippet == other.snippet;
}
