import '../entities/catalog_meal.dart';
import '../entities/enums.dart';
import '../entities/ingredient.dart';
import '../entities/nutrition.dart';

/// Seeded catalog — deterministic source of truth for generated plans.
List<CatalogMeal> seedMealCatalog() => List.unmodifiable(_catalog);

const _veg = DietType.vegetarian;
const _vegan = DietType.vegan;
const _pesc = DietType.pescatarian;
const _meat = DietType.none;

final _catalog = <CatalogMeal>[
  _meal(
    id: 'veg_poha',
    name: 'Veg Poha',
    diet: _veg,
    moods: {FoodMood.speedy, FoodMood.budgetFriendly},
    calories: 380,
    protein: 9,
    carbs: 62,
    fat: 10,
    cook: 20,
    cost: 3.5,
    aisleIngredients: [
      ('poha (flattened rice)', 80, 'g', GroceryAisle.grains),
      ('onion', 1, 'count', GroceryAisle.vegetables),
      ('green chilli', 1, 'count', GroceryAisle.vegetables),
      ('peanuts', 20, 'g', GroceryAisle.protein),
    ],
    steps: [
      'Rinse poha.',
      'Temper mustard and chilli.',
      'Fold in poha and serve.',
    ],
  ),
  _meal(
    id: 'millet_roti_paneer',
    name: 'Millet Roti with Paneer Sabji',
    diet: _veg,
    moods: {FoodMood.proteinPacked, FoodMood.familyFavorites},
    calories: 620,
    protein: 28,
    carbs: 58,
    fat: 28,
    cook: 35,
    cost: 7.5,
    aisleIngredients: [
      ('millet flour', 80, 'g', GroceryAisle.grains),
      ('paneer', 120, 'g', GroceryAisle.dairy),
      ('tomato', 2, 'count', GroceryAisle.vegetables),
      ('spinach', 100, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Roll millet roti.', 'Cook paneer in tomato-spinach gravy.'],
  ),
  _meal(
    id: 'tandoori_chicken_traybake',
    name: 'Tandoori Chicken Traybake',
    diet: _meat,
    moods: {FoodMood.proteinPacked, FoodMood.familyFavorites},
    calories: 802,
    protein: 40,
    carbs: 75,
    fat: 38,
    cook: 25,
    cost: 8.5,
    aisleIngredients: [
      ('chicken thighs', 400, 'g', GroceryAisle.protein),
      ('yogurt', 80, 'g', GroceryAisle.dairy),
      ('mixed vegetables', 300, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Marinate chicken.', 'Roast on a tray with vegetables.'],
  ),
  _meal(
    id: 'mexican_chicken_soup',
    name: 'Mexican Chicken Soup',
    diet: _meat,
    moods: {FoodMood.speedy, FoodMood.healthyComfort},
    calories: 420,
    protein: 32,
    carbs: 28,
    fat: 16,
    cook: 30,
    cost: 6.5,
    aisleIngredients: [
      ('chicken breast', 250, 'g', GroceryAisle.protein),
      ('black beans', 200, 'g', GroceryAisle.protein),
      ('tomato', 2, 'count', GroceryAisle.vegetables),
      ('corn', 100, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Simmer chicken with beans, tomato, and corn.'],
  ),
  _meal(
    id: 'thai_red_prawn_curry',
    name: 'Thai Red Prawn Curry',
    diet: _pesc,
    moods: {FoodMood.proteinPacked, FoodMood.familyFavorites},
    calories: 540,
    protein: 28,
    carbs: 42,
    fat: 26,
    cook: 25,
    cost: 9.5,
    aisleIngredients: [
      ('prawns', 250, 'g', GroceryAisle.protein),
      ('coconut milk', 200, 'ml', GroceryAisle.other),
      ('red curry paste', 30, 'g', GroceryAisle.other),
      ('broccoli', 150, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Fry curry paste.', 'Add coconut milk and prawns.'],
  ),
  _meal(
    id: 'quick_broccoli_pasta',
    name: 'Quick Broccoli Pasta',
    diet: _veg,
    moods: {FoodMood.speedy, FoodMood.budgetFriendly},
    calories: 510,
    protein: 18,
    carbs: 72,
    fat: 16,
    cook: 20,
    cost: 4.5,
    aisleIngredients: [
      ('pasta', 160, 'g', GroceryAisle.grains),
      ('broccoli', 200, 'g', GroceryAisle.vegetables),
      ('parmesan', 30, 'g', GroceryAisle.dairy),
    ],
    steps: ['Boil pasta with broccoli.', 'Toss with cheese.'],
  ),
  _meal(
    id: 'sweet_chili_tofu',
    name: 'Sweet Chili Tofu & Veggie',
    diet: _vegan,
    moods: {FoodMood.speedy, FoodMood.proteinPacked},
    calories: 430,
    protein: 22,
    carbs: 48,
    fat: 16,
    cook: 20,
    cost: 5.5,
    aisleIngredients: [
      ('tofu', 250, 'g', GroceryAisle.protein),
      ('sweet chili sauce', 40, 'ml', GroceryAisle.other),
      ('mixed vegetables', 250, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Pan-fry tofu.', 'Toss vegetables in sweet chili sauce.'],
  ),
  _meal(
    id: 'spinach_dal',
    name: 'Spinach Dal',
    diet: _vegan,
    moods: {FoodMood.budgetFriendly, FoodMood.healthyComfort},
    calories: 360,
    protein: 18,
    carbs: 48,
    fat: 8,
    cook: 35,
    cost: 3.0,
    aisleIngredients: [
      ('red lentils', 120, 'g', GroceryAisle.protein),
      ('spinach', 150, 'g', GroceryAisle.vegetables),
      ('turmeric', 4, 'g', GroceryAisle.other),
    ],
    steps: ['Cook lentils.', 'Fold in spinach.'],
  ),
  _meal(
    id: 'lauki_sabzi_roti',
    name: 'Bottle Gourd Sabzi and Millet Roti',
    diet: _vegan,
    moods: {FoodMood.lowCalorie, FoodMood.healthyComfort},
    calories: 410,
    protein: 12,
    carbs: 68,
    fat: 10,
    cook: 30,
    cost: 3.2,
    aisleIngredients: [
      ('bottle gourd', 300, 'g', GroceryAisle.vegetables),
      ('millet flour', 80, 'g', GroceryAisle.grains),
    ],
    steps: ['Cook bottle gourd sabzi.', 'Serve with millet roti.'],
  ),
  _meal(
    id: 'oats_curd_bowl',
    name: 'Oats with Curd',
    diet: _veg,
    moods: {FoodMood.lowCalorie, FoodMood.speedy},
    calories: 290,
    protein: 14,
    carbs: 42,
    fat: 7,
    cook: 10,
    cost: 2.5,
    aisleIngredients: [
      ('oats', 60, 'g', GroceryAisle.grains),
      ('curd', 150, 'g', GroceryAisle.dairy),
    ],
    steps: ['Soak oats.', 'Stir through curd.'],
  ),
  _meal(
    id: 'grilled_fish_broccoli',
    name: 'Grilled Fish with Broccoli',
    diet: _pesc,
    moods: {FoodMood.proteinPacked, FoodMood.lowCalorie},
    calories: 390,
    protein: 36,
    carbs: 12,
    fat: 18,
    cook: 22,
    cost: 9.0,
    aisleIngredients: [
      ('white fish', 220, 'g', GroceryAisle.protein),
      ('broccoli', 200, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Grill fish.', 'Steam broccoli.'],
  ),
  _meal(
    id: 'chickpea_curry',
    name: 'Chickpea Curry',
    diet: _vegan,
    moods: {FoodMood.budgetFriendly, FoodMood.familyFavorites},
    calories: 480,
    protein: 18,
    carbs: 62,
    fat: 16,
    cook: 35,
    cost: 4.0,
    aisleIngredients: [
      ('chickpeas', 240, 'g', GroceryAisle.protein),
      ('onion', 1, 'count', GroceryAisle.vegetables),
      ('tomato', 2, 'count', GroceryAisle.vegetables),
    ],
    steps: ['Saute onion and tomato.', 'Simmer chickpeas.'],
  ),
  _meal(
    id: 'vegetable_khichdi',
    name: 'Vegetable Khichdi',
    diet: _vegan,
    moods: {FoodMood.healthyComfort, FoodMood.budgetFriendly},
    calories: 440,
    protein: 14,
    carbs: 72,
    fat: 10,
    cook: 40,
    cost: 3.8,
    aisleIngredients: [
      ('moong dal', 80, 'g', GroceryAisle.protein),
      ('millet', 80, 'g', GroceryAisle.grains),
      ('mixed vegetables', 200, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Pressure-cook millet, dal, and vegetables.'],
  ),
  _meal(
    id: 'chicken_stir_fry',
    name: 'Chicken Stir Fry',
    diet: _meat,
    moods: {FoodMood.speedy, FoodMood.proteinPacked},
    calories: 470,
    protein: 38,
    carbs: 22,
    fat: 22,
    cook: 18,
    cost: 7.0,
    aisleIngredients: [
      ('chicken breast', 250, 'g', GroceryAisle.protein),
      ('mixed vegetables', 250, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Stir-fry chicken, then vegetables.'],
  ),
  _meal(
    id: 'palak_paneer',
    name: 'Palak Paneer',
    diet: _veg,
    moods: {FoodMood.familyFavorites, FoodMood.proteinPacked},
    calories: 520,
    protein: 24,
    carbs: 18,
    fat: 38,
    cook: 30,
    cost: 6.8,
    aisleIngredients: [
      ('spinach', 250, 'g', GroceryAisle.vegetables),
      ('paneer', 150, 'g', GroceryAisle.dairy),
    ],
    steps: ['Blanch spinach.', 'Simmer paneer in spinach gravy.'],
  ),
  _meal(
    id: 'masoor_dal_millet',
    name: 'Masoor Dal with Millet',
    diet: _vegan,
    moods: {FoodMood.budgetFriendly, FoodMood.healthyComfort},
    calories: 430,
    protein: 20,
    carbs: 68,
    fat: 8,
    cook: 35,
    cost: 3.1,
    aisleIngredients: [
      ('masoor dal', 120, 'g', GroceryAisle.protein),
      ('millet', 80, 'g', GroceryAisle.grains),
    ],
    steps: ['Cook dal.', 'Serve with steamed millet.'],
  ),
  _meal(
    id: 'yogurt_bowl',
    name: 'Greek Yogurt Bowl',
    diet: _veg,
    moods: {FoodMood.lowCalorie, FoodMood.proteinPacked, FoodMood.speedy},
    calories: 280,
    protein: 20,
    carbs: 28,
    fat: 8,
    cook: 5,
    cost: 3.4,
    aisleIngredients: [
      ('greek yogurt', 200, 'g', GroceryAisle.dairy),
      ('berries', 80, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Spoon yogurt.', 'Top with berries.'],
  ),
  _meal(
    id: 'lentil_soup',
    name: 'Lentil Soup',
    diet: _vegan,
    moods: {FoodMood.budgetFriendly, FoodMood.lowCalorie},
    calories: 320,
    protein: 18,
    carbs: 46,
    fat: 6,
    cook: 30,
    cost: 2.8,
    aisleIngredients: [
      ('brown lentils', 120, 'g', GroceryAisle.protein),
      ('carrot', 2, 'count', GroceryAisle.vegetables),
      ('celery', 2, 'count', GroceryAisle.vegetables),
    ],
    steps: ['Simmer lentils with chopped vegetables.'],
  ),
  _meal(
    id: 'tofu_bhurji',
    name: 'Tofu Bhurji',
    diet: _vegan,
    moods: {FoodMood.speedy, FoodMood.proteinPacked},
    calories: 360,
    protein: 24,
    carbs: 14,
    fat: 22,
    cook: 15,
    cost: 4.2,
    aisleIngredients: [
      ('tofu', 250, 'g', GroceryAisle.protein),
      ('onion', 1, 'count', GroceryAisle.vegetables),
      ('tomato', 1, 'count', GroceryAisle.vegetables),
    ],
    steps: ['Crumble tofu.', 'Cook with onion and tomato.'],
  ),
  _meal(
    id: 'egg_white_omelette',
    name: 'Egg White Omelette',
    diet: _pesc,
    moods: {FoodMood.speedy, FoodMood.proteinPacked, FoodMood.lowCalorie},
    calories: 210,
    protein: 26,
    carbs: 4,
    fat: 8,
    cook: 10,
    cost: 3.0,
    aisleIngredients: [
      ('egg whites', 180, 'g', GroceryAisle.protein),
      ('spinach', 50, 'g', GroceryAisle.vegetables),
    ],
    steps: ['Whisk egg whites.', 'Cook with spinach.'],
  ),
];

CatalogMeal _meal({
  required String id,
  required String name,
  required DietType diet,
  required Set<FoodMood> moods,
  required int calories,
  required double protein,
  required double carbs,
  required double fat,
  required int cook,
  required double cost,
  required List<(String, num, String, GroceryAisle)> aisleIngredients,
  required List<String> steps,
}) {
  return CatalogMeal(
    id: id,
    name: name,
    servings: 2,
    nutrition: Nutrition(
      calories: calories,
      proteinG: protein,
      carbsG: carbs,
      fatG: fat,
    ),
    cookTimeMinutes: cook,
    diet: diet,
    moods: moods,
    ingredients: [
      for (final item in aisleIngredients)
        Ingredient(
          name: item.$1,
          quantity: item.$2.toDouble(),
          unit: item.$3,
          aisle: item.$4,
        ),
    ],
    instructions: steps,
    estimatedCost: cost,
  );
}
