// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/meetings.dart';
import 'api/setup.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 191481972;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'airo_mind_whisper',
        ioDirectory: '../../rust/airo_mind_whisper/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiMeetingsCancelProcessing();

  Future<MeetingRecord?> crateApiMeetingsGetMeeting({required String id});

  Future<TranscriptDocumentRecord?> crateApiMeetingsGetTranscript({
    required String meetingId,
  });

  Future<void> crateApiMeetingsInitialize({required MindConfig config});

  bool crateApiMeetingsIsReady();

  Future<List<MeetingRecord>> crateApiMeetingsListMeetings();

  Future<List<RequiredModel>> crateApiSetupRequiredModels();

  Future<String> crateApiMeetingsSaveMeeting({
    required String title,
    required BigInt recordedAtMs,
    required String transcript,
    required String minutes,
    required String model,
    required List<TranscriptSegmentRecord> segments,
    required String audioPath,
  });

  Future<List<SearchHit>> crateApiMeetingsSearchMeetings({
    required String query,
  });

  Future<SpeechLanguage> crateApiMeetingsSpeechLanguageDefault();

  Stream<TranscriptEvent> crateApiMeetingsTranscribeRecording({
    required String wavPath,
    String? language,
  });

  Future<List<InstalledModel>> crateApiSetupVerifyInstalledModels({
    required String modelsDir,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiMeetingsCancelProcessing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMeetingsCancelProcessingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsCancelProcessingConstMeta =>
      const TaskConstMeta(debugName: "cancel_processing", argNames: []);

  @override
  Future<MeetingRecord?> crateApiMeetingsGetMeeting({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_meeting_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMeetingsGetMeetingConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsGetMeetingConstMeta =>
      const TaskConstMeta(debugName: "get_meeting", argNames: ["id"]);

  @override
  Future<TranscriptDocumentRecord?> crateApiMeetingsGetTranscript({
    required String meetingId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(meetingId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_transcript_document_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMeetingsGetTranscriptConstMeta,
        argValues: [meetingId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsGetTranscriptConstMeta =>
      const TaskConstMeta(debugName: "get_transcript", argNames: ["meetingId"]);

  @override
  Future<void> crateApiMeetingsInitialize({required MindConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mind_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMeetingsInitializeConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsInitializeConstMeta =>
      const TaskConstMeta(debugName: "initialize", argNames: ["config"]);

  @override
  bool crateApiMeetingsIsReady() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMeetingsIsReadyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsIsReadyConstMeta =>
      const TaskConstMeta(debugName: "is_ready", argNames: []);

  @override
  Future<List<MeetingRecord>> crateApiMeetingsListMeetings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_meeting_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMeetingsListMeetingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsListMeetingsConstMeta =>
      const TaskConstMeta(debugName: "list_meetings", argNames: []);

  @override
  Future<List<RequiredModel>> crateApiSetupRequiredModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_required_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetupRequiredModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupRequiredModelsConstMeta =>
      const TaskConstMeta(debugName: "required_models", argNames: []);

  @override
  Future<String> crateApiMeetingsSaveMeeting({
    required String title,
    required BigInt recordedAtMs,
    required String transcript,
    required String minutes,
    required String model,
    required List<TranscriptSegmentRecord> segments,
    required String audioPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_u_64(recordedAtMs, serializer);
          sse_encode_String(transcript, serializer);
          sse_encode_String(minutes, serializer);
          sse_encode_String(model, serializer);
          sse_encode_list_transcript_segment_record(segments, serializer);
          sse_encode_String(audioPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMeetingsSaveMeetingConstMeta,
        argValues: [
          title,
          recordedAtMs,
          transcript,
          minutes,
          model,
          segments,
          audioPath,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsSaveMeetingConstMeta =>
      const TaskConstMeta(
        debugName: "save_meeting",
        argNames: [
          "title",
          "recordedAtMs",
          "transcript",
          "minutes",
          "model",
          "segments",
          "audioPath",
        ],
      );

  @override
  Future<List<SearchHit>> crateApiMeetingsSearchMeetings({
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_hit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMeetingsSearchMeetingsConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsSearchMeetingsConstMeta =>
      const TaskConstMeta(debugName: "search_meetings", argNames: ["query"]);

  @override
  Future<SpeechLanguage> crateApiMeetingsSpeechLanguageDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_speech_language,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMeetingsSpeechLanguageDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMeetingsSpeechLanguageDefaultConstMeta =>
      const TaskConstMeta(debugName: "speech_language_default", argNames: []);

  @override
  Stream<TranscriptEvent> crateApiMeetingsTranscribeRecording({
    required String wavPath,
    String? language,
  }) {
    final sink = RustStreamSink<TranscriptEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(wavPath, serializer);
            sse_encode_opt_String(language, serializer);
            sse_encode_StreamSink_transcript_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMeetingsTranscribeRecordingConstMeta,
          argValues: [wavPath, language, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMeetingsTranscribeRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_recording",
        argNames: ["wavPath", "language", "sink"],
      );

  @override
  Future<List<InstalledModel>> crateApiSetupVerifyInstalledModels({
    required String modelsDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelsDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_installed_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetupVerifyInstalledModelsConstMeta,
        argValues: [modelsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupVerifyInstalledModelsConstMeta =>
      const TaskConstMeta(
        debugName: "verify_installed_models",
        argNames: ["modelsDir"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<TranscriptEvent> dco_decode_StreamSink_transcript_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MeetingRecord dco_decode_box_autoadd_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_meeting_record(raw);
  }

  @protected
  MindConfig dco_decode_box_autoadd_mind_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mind_config(raw);
  }

  @protected
  TranscriptDocumentRecord dco_decode_box_autoadd_transcript_document_record(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transcript_document_record(raw);
  }

  @protected
  TranscriptSegmentRecord dco_decode_box_autoadd_transcript_segment_record(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transcript_segment_record(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InstalledModel dco_decode_installed_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InstalledModel(
      fileName: dco_decode_String(arr[0]),
      present: dco_decode_bool(arr[1]),
      verified: dco_decode_bool(arr[2]),
      detail: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<InstalledModel> dco_decode_list_installed_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_installed_model).toList();
  }

  @protected
  List<MeetingRecord> dco_decode_list_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_meeting_record).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RequiredModel> dco_decode_list_required_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_required_model).toList();
  }

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit).toList();
  }

  @protected
  List<TranscriptSegmentRecord> dco_decode_list_transcript_segment_record(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transcript_segment_record)
        .toList();
  }

  @protected
  MeetingRecord dco_decode_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MeetingRecord(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      recordedAt: dco_decode_u_64(arr[2]),
      transcript: dco_decode_String(arr[3]),
      minutes: dco_decode_String(arr[4]),
      model: dco_decode_String(arr[5]),
    );
  }

  @protected
  MindConfig dco_decode_mind_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MindConfig(
      modelsDir: dco_decode_String(arr[0]),
      storePath: dco_decode_String(arr[1]),
      memoryBudgetMb: dco_decode_u_32(arr[2]),
      speechLanguage: dco_decode_speech_language(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MeetingRecord? dco_decode_opt_box_autoadd_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_meeting_record(raw);
  }

  @protected
  TranscriptDocumentRecord?
  dco_decode_opt_box_autoadd_transcript_document_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_transcript_document_record(raw);
  }

  @protected
  RequiredModel dco_decode_required_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RequiredModel(
      fileName: dco_decode_String(arr[0]),
      sizeBytes: dco_decode_u_64(arr[1]),
      sha256: dco_decode_String(arr[2]),
    );
  }

  @protected
  SearchHit dco_decode_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchHit(
      meetingId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      recordedAt: dco_decode_u_64(arr[2]),
      snippet: dco_decode_String(arr[3]),
    );
  }

  @protected
  SpeechLanguage dco_decode_speech_language(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpeechLanguage.values[raw as int];
  }

  @protected
  TranscriptDocumentRecord dco_decode_transcript_document_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TranscriptDocumentRecord(
      meetingId: dco_decode_String(arr[0]),
      audioPath: dco_decode_String(arr[1]),
      modelVersion: dco_decode_String(arr[2]),
      segments: dco_decode_list_transcript_segment_record(arr[3]),
    );
  }

  @protected
  TranscriptEvent dco_decode_transcript_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TranscriptEvent_Transcribing(
          segment: dco_decode_box_autoadd_transcript_segment_record(raw[1]),
        );
      case 1:
        return TranscriptEvent_TranscriptReady(
          text: dco_decode_String(raw[1]),
          segments: dco_decode_list_transcript_segment_record(raw[2]),
        );
      case 2:
        return TranscriptEvent_Cancelled();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TranscriptSegmentRecord dco_decode_transcript_segment_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TranscriptSegmentRecord(
      id: dco_decode_String(arr[0]),
      startMs: dco_decode_u_64(arr[1]),
      endMs: dco_decode_u_64(arr[2]),
      text: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<TranscriptEvent> sse_decode_StreamSink_transcript_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MeetingRecord sse_decode_box_autoadd_meeting_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_meeting_record(deserializer));
  }

  @protected
  MindConfig sse_decode_box_autoadd_mind_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mind_config(deserializer));
  }

  @protected
  TranscriptDocumentRecord sse_decode_box_autoadd_transcript_document_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transcript_document_record(deserializer));
  }

  @protected
  TranscriptSegmentRecord sse_decode_box_autoadd_transcript_segment_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transcript_segment_record(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InstalledModel sse_decode_installed_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_present = sse_decode_bool(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return InstalledModel(
      fileName: var_fileName,
      present: var_present,
      verified: var_verified,
      detail: var_detail,
    );
  }

  @protected
  List<InstalledModel> sse_decode_list_installed_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InstalledModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_installed_model(deserializer));
    }
    return ans_;
  }

  @protected
  List<MeetingRecord> sse_decode_list_meeting_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MeetingRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_meeting_record(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RequiredModel> sse_decode_list_required_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RequiredModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_required_model(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<TranscriptSegmentRecord> sse_decode_list_transcript_segment_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranscriptSegmentRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transcript_segment_record(deserializer));
    }
    return ans_;
  }

  @protected
  MeetingRecord sse_decode_meeting_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_recordedAt = sse_decode_u_64(deserializer);
    var var_transcript = sse_decode_String(deserializer);
    var var_minutes = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    return MeetingRecord(
      id: var_id,
      title: var_title,
      recordedAt: var_recordedAt,
      transcript: var_transcript,
      minutes: var_minutes,
      model: var_model,
    );
  }

  @protected
  MindConfig sse_decode_mind_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelsDir = sse_decode_String(deserializer);
    var var_storePath = sse_decode_String(deserializer);
    var var_memoryBudgetMb = sse_decode_u_32(deserializer);
    var var_speechLanguage = sse_decode_speech_language(deserializer);
    return MindConfig(
      modelsDir: var_modelsDir,
      storePath: var_storePath,
      memoryBudgetMb: var_memoryBudgetMb,
      speechLanguage: var_speechLanguage,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MeetingRecord? sse_decode_opt_box_autoadd_meeting_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_meeting_record(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TranscriptDocumentRecord?
  sse_decode_opt_box_autoadd_transcript_document_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_transcript_document_record(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RequiredModel sse_decode_required_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    return RequiredModel(
      fileName: var_fileName,
      sizeBytes: var_sizeBytes,
      sha256: var_sha256,
    );
  }

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_meetingId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_recordedAt = sse_decode_u_64(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    return SearchHit(
      meetingId: var_meetingId,
      title: var_title,
      recordedAt: var_recordedAt,
      snippet: var_snippet,
    );
  }

  @protected
  SpeechLanguage sse_decode_speech_language(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SpeechLanguage.values[inner];
  }

  @protected
  TranscriptDocumentRecord sse_decode_transcript_document_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_meetingId = sse_decode_String(deserializer);
    var var_audioPath = sse_decode_String(deserializer);
    var var_modelVersion = sse_decode_String(deserializer);
    var var_segments = sse_decode_list_transcript_segment_record(deserializer);
    return TranscriptDocumentRecord(
      meetingId: var_meetingId,
      audioPath: var_audioPath,
      modelVersion: var_modelVersion,
      segments: var_segments,
    );
  }

  @protected
  TranscriptEvent sse_decode_transcript_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_segment = sse_decode_box_autoadd_transcript_segment_record(
          deserializer,
        );
        return TranscriptEvent_Transcribing(segment: var_segment);
      case 1:
        var var_text = sse_decode_String(deserializer);
        var var_segments = sse_decode_list_transcript_segment_record(
          deserializer,
        );
        return TranscriptEvent_TranscriptReady(
          text: var_text,
          segments: var_segments,
        );
      case 2:
        return TranscriptEvent_Cancelled();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TranscriptSegmentRecord sse_decode_transcript_segment_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_startMs = sse_decode_u_64(deserializer);
    var var_endMs = sse_decode_u_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    return TranscriptSegmentRecord(
      id: var_id,
      startMs: var_startMs,
      endMs: var_endMs,
      text: var_text,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_transcript_event_Sse(
    RustStreamSink<TranscriptEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcript_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_meeting_record(
    MeetingRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_meeting_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mind_config(
    MindConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mind_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transcript_document_record(
    TranscriptDocumentRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transcript_document_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transcript_segment_record(
    TranscriptSegmentRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transcript_segment_record(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_installed_model(
    InstalledModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_bool(self.present, serializer);
    sse_encode_bool(self.verified, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_list_installed_model(
    List<InstalledModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_installed_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_meeting_record(
    List<MeetingRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_meeting_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_required_model(
    List<RequiredModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_required_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transcript_segment_record(
    List<TranscriptSegmentRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transcript_segment_record(item, serializer);
    }
  }

  @protected
  void sse_encode_meeting_record(MeetingRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.recordedAt, serializer);
    sse_encode_String(self.transcript, serializer);
    sse_encode_String(self.minutes, serializer);
    sse_encode_String(self.model, serializer);
  }

  @protected
  void sse_encode_mind_config(MindConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelsDir, serializer);
    sse_encode_String(self.storePath, serializer);
    sse_encode_u_32(self.memoryBudgetMb, serializer);
    sse_encode_speech_language(self.speechLanguage, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_meeting_record(
    MeetingRecord? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_meeting_record(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_transcript_document_record(
    TranscriptDocumentRecord? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_transcript_document_record(self, serializer);
    }
  }

  @protected
  void sse_encode_required_model(RequiredModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.meetingId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.recordedAt, serializer);
    sse_encode_String(self.snippet, serializer);
  }

  @protected
  void sse_encode_speech_language(
    SpeechLanguage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transcript_document_record(
    TranscriptDocumentRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.meetingId, serializer);
    sse_encode_String(self.audioPath, serializer);
    sse_encode_String(self.modelVersion, serializer);
    sse_encode_list_transcript_segment_record(self.segments, serializer);
  }

  @protected
  void sse_encode_transcript_event(
    TranscriptEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TranscriptEvent_Transcribing(segment: final segment):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_transcript_segment_record(segment, serializer);
      case TranscriptEvent_TranscriptReady(
        text: final text,
        segments: final segments,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
        sse_encode_list_transcript_segment_record(segments, serializer);
      case TranscriptEvent_Cancelled():
        sse_encode_i_32(2, serializer);
    }
  }

  @protected
  void sse_encode_transcript_segment_record(
    TranscriptSegmentRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_u_64(self.startMs, serializer);
    sse_encode_u_64(self.endMs, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
