// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/meetings.dart';
import 'api/mind_runtime.dart';
import 'api/setup.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'mind_runtime_state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<TranscriptEvent> dco_decode_StreamSink_transcript_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MeetingRecord dco_decode_box_autoadd_meeting_record(dynamic raw);

  @protected
  MindConfig dco_decode_box_autoadd_mind_config(dynamic raw);

  @protected
  TranscriptDocumentRecord dco_decode_box_autoadd_transcript_document_record(
    dynamic raw,
  );

  @protected
  TranscriptSegmentRecord dco_decode_box_autoadd_transcript_segment_record(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InstalledModel dco_decode_installed_model(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<InstalledModel> dco_decode_list_installed_model(dynamic raw);

  @protected
  List<MeetingActionItemRecord> dco_decode_list_meeting_action_item_record(
    dynamic raw,
  );

  @protected
  List<MeetingDecisionRecord> dco_decode_list_meeting_decision_record(
    dynamic raw,
  );

  @protected
  List<MeetingMetricRecord> dco_decode_list_meeting_metric_record(dynamic raw);

  @protected
  List<MeetingRecord> dco_decode_list_meeting_record(dynamic raw);

  @protected
  List<MindOpWire> dco_decode_list_mind_op_wire(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RequiredModel> dco_decode_list_required_model(dynamic raw);

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw);

  @protected
  List<TranscriptSegmentRecord> dco_decode_list_transcript_segment_record(
    dynamic raw,
  );

  @protected
  MeetingActionItemRecord dco_decode_meeting_action_item_record(dynamic raw);

  @protected
  MeetingActionStatus dco_decode_meeting_action_status(dynamic raw);

  @protected
  MeetingDecisionRecord dco_decode_meeting_decision_record(dynamic raw);

  @protected
  MeetingDecisionStatus dco_decode_meeting_decision_status(dynamic raw);

  @protected
  MeetingMetricRecord dco_decode_meeting_metric_record(dynamic raw);

  @protected
  MeetingRecord dco_decode_meeting_record(dynamic raw);

  @protected
  MindConfig dco_decode_mind_config(dynamic raw);

  @protected
  MindOpWire dco_decode_mind_op_wire(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MeetingRecord? dco_decode_opt_box_autoadd_meeting_record(dynamic raw);

  @protected
  TranscriptDocumentRecord?
  dco_decode_opt_box_autoadd_transcript_document_record(dynamic raw);

  @protected
  RequiredModel dco_decode_required_model(dynamic raw);

  @protected
  SearchHit dco_decode_search_hit(dynamic raw);

  @protected
  SpeechLanguage dco_decode_speech_language(dynamic raw);

  @protected
  TranscriptDocumentRecord dco_decode_transcript_document_record(dynamic raw);

  @protected
  TranscriptEvent dco_decode_transcript_event(dynamic raw);

  @protected
  TranscriptSegmentRecord dco_decode_transcript_segment_record(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<TranscriptEvent> sse_decode_StreamSink_transcript_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MeetingRecord sse_decode_box_autoadd_meeting_record(
    SseDeserializer deserializer,
  );

  @protected
  MindConfig sse_decode_box_autoadd_mind_config(SseDeserializer deserializer);

  @protected
  TranscriptDocumentRecord sse_decode_box_autoadd_transcript_document_record(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptSegmentRecord sse_decode_box_autoadd_transcript_segment_record(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InstalledModel sse_decode_installed_model(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<InstalledModel> sse_decode_list_installed_model(
    SseDeserializer deserializer,
  );

  @protected
  List<MeetingActionItemRecord> sse_decode_list_meeting_action_item_record(
    SseDeserializer deserializer,
  );

  @protected
  List<MeetingDecisionRecord> sse_decode_list_meeting_decision_record(
    SseDeserializer deserializer,
  );

  @protected
  List<MeetingMetricRecord> sse_decode_list_meeting_metric_record(
    SseDeserializer deserializer,
  );

  @protected
  List<MeetingRecord> sse_decode_list_meeting_record(
    SseDeserializer deserializer,
  );

  @protected
  List<MindOpWire> sse_decode_list_mind_op_wire(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RequiredModel> sse_decode_list_required_model(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer);

  @protected
  List<TranscriptSegmentRecord> sse_decode_list_transcript_segment_record(
    SseDeserializer deserializer,
  );

  @protected
  MeetingActionItemRecord sse_decode_meeting_action_item_record(
    SseDeserializer deserializer,
  );

  @protected
  MeetingActionStatus sse_decode_meeting_action_status(
    SseDeserializer deserializer,
  );

  @protected
  MeetingDecisionRecord sse_decode_meeting_decision_record(
    SseDeserializer deserializer,
  );

  @protected
  MeetingDecisionStatus sse_decode_meeting_decision_status(
    SseDeserializer deserializer,
  );

  @protected
  MeetingMetricRecord sse_decode_meeting_metric_record(
    SseDeserializer deserializer,
  );

  @protected
  MeetingRecord sse_decode_meeting_record(SseDeserializer deserializer);

  @protected
  MindConfig sse_decode_mind_config(SseDeserializer deserializer);

  @protected
  MindOpWire sse_decode_mind_op_wire(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MeetingRecord? sse_decode_opt_box_autoadd_meeting_record(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptDocumentRecord?
  sse_decode_opt_box_autoadd_transcript_document_record(
    SseDeserializer deserializer,
  );

  @protected
  RequiredModel sse_decode_required_model(SseDeserializer deserializer);

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer);

  @protected
  SpeechLanguage sse_decode_speech_language(SseDeserializer deserializer);

  @protected
  TranscriptDocumentRecord sse_decode_transcript_document_record(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptEvent sse_decode_transcript_event(SseDeserializer deserializer);

  @protected
  TranscriptSegmentRecord sse_decode_transcript_segment_record(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcript_event_Sse(
    RustStreamSink<TranscriptEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_meeting_record(
    MeetingRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mind_config(
    MindConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transcript_document_record(
    TranscriptDocumentRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transcript_segment_record(
    TranscriptSegmentRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_installed_model(
    InstalledModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_installed_model(
    List<InstalledModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meeting_action_item_record(
    List<MeetingActionItemRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meeting_decision_record(
    List<MeetingDecisionRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meeting_metric_record(
    List<MeetingMetricRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meeting_record(
    List<MeetingRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mind_op_wire(
    List<MindOpWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_required_model(
    List<RequiredModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transcript_segment_record(
    List<TranscriptSegmentRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_action_item_record(
    MeetingActionItemRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_action_status(
    MeetingActionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_decision_record(
    MeetingDecisionRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_decision_status(
    MeetingDecisionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_metric_record(
    MeetingMetricRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_record(MeetingRecord self, SseSerializer serializer);

  @protected
  void sse_encode_mind_config(MindConfig self, SseSerializer serializer);

  @protected
  void sse_encode_mind_op_wire(MindOpWire self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_meeting_record(
    MeetingRecord? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_transcript_document_record(
    TranscriptDocumentRecord? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_required_model(RequiredModel self, SseSerializer serializer);

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer);

  @protected
  void sse_encode_speech_language(
    SpeechLanguage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcript_document_record(
    TranscriptDocumentRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcript_event(
    TranscriptEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcript_segment_record(
    TranscriptSegmentRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
