// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MindDeviceWire {
  final String name;
  final String fingerprintA;
  final String fingerprintB;
  final String fingerprintC;
  final bool isThisDevice;
  final BigInt revokedAtMs;

  const MindDeviceWire({
    required this.name,
    required this.fingerprintA,
    required this.fingerprintB,
    required this.fingerprintC,
    required this.isThisDevice,
    required this.revokedAtMs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      fingerprintA.hashCode ^
      fingerprintB.hashCode ^
      fingerprintC.hashCode ^
      isThisDevice.hashCode ^
      revokedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MindDeviceWire &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fingerprintA == other.fingerprintA &&
          fingerprintB == other.fingerprintB &&
          fingerprintC == other.fingerprintC &&
          isThisDevice == other.isThisDevice &&
          revokedAtMs == other.revokedAtMs;
}

class VaultStateWire {
  final bool isSealed;
  final BigInt keyCount;
  final BigInt revokedCount;
  final BigInt revocationEpoch;
  final BigInt onDiskBytes;

  const VaultStateWire({
    required this.isSealed,
    required this.keyCount,
    required this.revokedCount,
    required this.revocationEpoch,
    required this.onDiskBytes,
  });

  @override
  int get hashCode =>
      isSealed.hashCode ^
      keyCount.hashCode ^
      revokedCount.hashCode ^
      revocationEpoch.hashCode ^
      onDiskBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStateWire &&
          runtimeType == other.runtimeType &&
          isSealed == other.isSealed &&
          keyCount == other.keyCount &&
          revokedCount == other.revokedCount &&
          revocationEpoch == other.revocationEpoch &&
          onDiskBytes == other.onDiskBytes;
}
