// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 68556957;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__minutes__cancel_generation_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_generation",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::minutes::cancel_generation();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__meeting_intelligence__cancel_meeting_intelligence_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_meeting_intelligence",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::meeting_intelligence::cancel_meeting_intelligence();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__reasoning__cancel_reasoning_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_reasoning",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::reasoning::cancel_reasoning();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__minutes__generate_completion_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_completion",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_prompt = <String>::sse_decode(&mut deserializer);
            let api_max_output_tokens = <u32>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::minutes::GenerationEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::minutes::generate_completion(
                        api_prompt,
                        api_max_output_tokens,
                        api_sink,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__minutes__generate_minutes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_minutes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_transcript = <String>::sse_decode(&mut deserializer);
            let api_grammar = <Option<String>>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::minutes::GenerationEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::minutes::generate_minutes(
                        api_transcript,
                        api_grammar,
                        api_sink,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__minutes__generation_model_id_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generation_model_id",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::minutes::generation_model_id())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__minutes__generation_stats_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generation_stats",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::minutes::generation_stats())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__minutes__initialize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::minutes::GenerationConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::minutes::initialize(api_config)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__minutes__is_ready_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_ready",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::minutes::is_ready())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__meeting_intelligence__process_meeting_intelligence_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_meeting_intelligence",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_meeting_id = <String>::sse_decode(&mut deserializer);
            let api_title = <String>::sse_decode(&mut deserializer);
            let api_segments =
                <Vec<crate::api::meeting_intelligence::MeetingIntelligenceSegment>>::sse_decode(
                    &mut deserializer,
                );
            let api_sink = <StreamSink<
                crate::api::meeting_intelligence::MeetingIntelligenceEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::meeting_intelligence::process_meeting_intelligence(
                        api_meeting_id,
                        api_title,
                        api_segments,
                        api_sink,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__reasoning__reason_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reason",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::reasoning::ReasoningRequest>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::reasoning::ReasoningEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::reasoning::reason(api_request, api_sink)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__minutes__unload_generation_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "unload_generation",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::minutes::unload_generation();
                })?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::minutes::GenerationEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::meeting_intelligence::MeetingIntelligenceEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::reasoning::ReasoningEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::minutes::GenerationConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_modelsDir = <String>::sse_decode(deserializer);
        let mut var_memoryBudgetMb = <u32>::sse_decode(deserializer);
        let mut var_preferIndicGeneration = <bool>::sse_decode(deserializer);
        let mut var_allowCompactFallback = <bool>::sse_decode(deserializer);
        return crate::api::minutes::GenerationConfig {
            models_dir: var_modelsDir,
            memory_budget_mb: var_memoryBudgetMb,
            prefer_indic_generation: var_preferIndicGeneration,
            allow_compact_fallback: var_allowCompactFallback,
        };
    }
}

impl SseDecode for crate::api::minutes::GenerationEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::minutes::GenerationEvent::Generating { text: var_text };
            }
            1 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::minutes::GenerationEvent::MinutesReady { text: var_text };
            }
            2 => {
                return crate::api::minutes::GenerationEvent::Cancelled;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::minutes::GenerationStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_prefillMs = <u64>::sse_decode(deserializer);
        let mut var_prefillTokens = <u32>::sse_decode(deserializer);
        let mut var_generationMs = <u64>::sse_decode(deserializer);
        let mut var_generatedTokens = <u32>::sse_decode(deserializer);
        let mut var_tokensPerSecond = <f64>::sse_decode(deserializer);
        let mut var_peakRssBytes = <u64>::sse_decode(deserializer);
        return crate::api::minutes::GenerationStats {
            prefill_ms: var_prefillMs,
            prefill_tokens: var_prefillTokens,
            generation_ms: var_generationMs,
            generated_tokens: var_generatedTokens,
            tokens_per_second: var_tokensPerSecond,
            peak_rss_bytes: var_peakRssBytes,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::meeting_intelligence::MeetingActionItemRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::meeting_intelligence::MeetingActionItemRecord>::sse_decode(
                    deserializer,
                ),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::meeting_intelligence::MeetingDecisionRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::meeting_intelligence::MeetingDecisionRecord>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::meeting_intelligence::MeetingIntelligenceSegment> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::meeting_intelligence::MeetingIntelligenceSegment>::sse_decode(
                    deserializer,
                ),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::meeting_intelligence::MeetingMetricRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::meeting_intelligence::MeetingMetricRecord>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::reasoning::ReasoningContextItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::reasoning::ReasoningContextItem>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingActionItemRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_task = <String>::sse_decode(deserializer);
        let mut var_owner = <Option<String>>::sse_decode(deserializer);
        let mut var_due = <Option<String>>::sse_decode(deserializer);
        let mut var_status =
            <crate::api::meeting_intelligence::MeetingActionStatus>::sse_decode(deserializer);
        let mut var_evidenceSegmentIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::meeting_intelligence::MeetingActionItemRecord {
            id: var_id,
            task: var_task,
            owner: var_owner,
            due: var_due,
            status: var_status,
            evidence_segment_ids: var_evidenceSegmentIds,
        };
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingActionStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::meeting_intelligence::MeetingActionStatus::Open,
            1 => crate::api::meeting_intelligence::MeetingActionStatus::InProgress,
            2 => crate::api::meeting_intelligence::MeetingActionStatus::Done,
            3 => crate::api::meeting_intelligence::MeetingActionStatus::Blocked,
            _ => unreachable!("Invalid variant for MeetingActionStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingDecisionRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_statement = <String>::sse_decode(deserializer);
        let mut var_status =
            <crate::api::meeting_intelligence::MeetingDecisionStatus>::sse_decode(deserializer);
        let mut var_evidenceSegmentIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::meeting_intelligence::MeetingDecisionRecord {
            id: var_id,
            statement: var_statement,
            status: var_status,
            evidence_segment_ids: var_evidenceSegmentIds,
        };
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingDecisionStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::meeting_intelligence::MeetingDecisionStatus::Proposed,
            1 => crate::api::meeting_intelligence::MeetingDecisionStatus::Agreed,
            2 => crate::api::meeting_intelligence::MeetingDecisionStatus::Rejected,
            3 => crate::api::meeting_intelligence::MeetingDecisionStatus::Deferred,
            _ => unreachable!("Invalid variant for MeetingDecisionStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingIntelligenceEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::meeting_intelligence::MeetingIntelligenceEvent::Extracting;
            }
            1 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::meeting_intelligence::MeetingIntelligenceEvent::Generating {
                    text: var_text,
                };
            }
            2 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::meeting_intelligence::MeetingIntelligenceEvent::MinutesReady {
                    text: var_text,
                };
            }
            3 => {
                let mut var_decisions = <Vec<
                    crate::api::meeting_intelligence::MeetingDecisionRecord,
                >>::sse_decode(deserializer);
                let mut var_actionItems = <Vec<
                    crate::api::meeting_intelligence::MeetingActionItemRecord,
                >>::sse_decode(deserializer);
                let mut var_metrics =
                    <Vec<crate::api::meeting_intelligence::MeetingMetricRecord>>::sse_decode(
                        deserializer,
                    );
                return crate::api::meeting_intelligence::MeetingIntelligenceEvent::IrReady {
                    decisions: var_decisions,
                    action_items: var_actionItems,
                    metrics: var_metrics,
                };
            }
            4 => {
                return crate::api::meeting_intelligence::MeetingIntelligenceEvent::Cancelled;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingIntelligenceSegment {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_startMs = <u64>::sse_decode(deserializer);
        let mut var_endMs = <u64>::sse_decode(deserializer);
        let mut var_text = <String>::sse_decode(deserializer);
        return crate::api::meeting_intelligence::MeetingIntelligenceSegment {
            id: var_id,
            start_ms: var_startMs,
            end_ms: var_endMs,
            text: var_text,
        };
    }
}

impl SseDecode for crate::api::meeting_intelligence::MeetingMetricRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        let mut var_evidenceSegmentIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::meeting_intelligence::MeetingMetricRecord {
            id: var_id,
            name: var_name,
            value: var_value,
            evidence_segment_ids: var_evidenceSegmentIds,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::reasoning::ReasoningLevel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::reasoning::ReasoningLevel>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::reasoning::ReasoningContextItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_text = <String>::sse_decode(deserializer);
        return crate::api::reasoning::ReasoningContextItem {
            source: var_source,
            text: var_text,
        };
    }
}

impl SseDecode for crate::api::reasoning::ReasoningEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::reasoning::ReasoningEvent::Started;
            }
            1 => {
                let mut var_stage =
                    <crate::api::reasoning::ReasoningStage>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::StageChanged { stage: var_stage };
            }
            2 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::Progress {
                    message: var_message,
                };
            }
            3 => {
                let mut var_tool = <String>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::ToolStarted { tool: var_tool };
            }
            4 => {
                let mut var_tool = <String>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::ToolCompleted { tool: var_tool };
            }
            5 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::AnswerDelta { text: var_text };
            }
            6 => {
                let mut var_answer = <String>::sse_decode(deserializer);
                let mut var_reasoningSummary = <Option<String>>::sse_decode(deserializer);
                let mut var_level =
                    <crate::api::reasoning::ReasoningLevel>::sse_decode(deserializer);
                let mut var_confidence = <Option<f32>>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::Completed {
                    answer: var_answer,
                    reasoning_summary: var_reasoningSummary,
                    level: var_level,
                    confidence: var_confidence,
                };
            }
            7 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::reasoning::ReasoningEvent::Error {
                    message: var_message,
                };
            }
            8 => {
                return crate::api::reasoning::ReasoningEvent::Cancelled;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::reasoning::ReasoningLevel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::reasoning::ReasoningLevel::None,
            1 => crate::api::reasoning::ReasoningLevel::Light,
            2 => crate::api::reasoning::ReasoningLevel::Standard,
            3 => crate::api::reasoning::ReasoningLevel::Deep,
            _ => unreachable!("Invalid variant for ReasoningLevel: {}", inner),
        };
    }
}

impl SseDecode for crate::api::reasoning::ReasoningRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_userQuery = <String>::sse_decode(deserializer);
        let mut var_intentKind = <String>::sse_decode(deserializer);
        let mut var_intentComplexity = <f32>::sse_decode(deserializer);
        let mut var_requestedLevel =
            <Option<crate::api::reasoning::ReasoningLevel>>::sse_decode(deserializer);
        let mut var_maxReasoningLevel =
            <crate::api::reasoning::ReasoningLevel>::sse_decode(deserializer);
        let mut var_availableMemoryMb = <u32>::sse_decode(deserializer);
        let mut var_gpuAvailable = <bool>::sse_decode(deserializer);
        let mut var_npuAvailable = <bool>::sse_decode(deserializer);
        let mut var_thermalConstrained = <bool>::sse_decode(deserializer);
        let mut var_batteryConstrained = <bool>::sse_decode(deserializer);
        let mut var_memories =
            <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_decode(deserializer);
        let mut var_documents =
            <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_decode(deserializer);
        let mut var_toolResults =
            <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_decode(deserializer);
        let mut var_history =
            <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_decode(deserializer);
        let mut var_toolNames = <Vec<String>>::sse_decode(deserializer);
        return crate::api::reasoning::ReasoningRequest {
            user_query: var_userQuery,
            intent_kind: var_intentKind,
            intent_complexity: var_intentComplexity,
            requested_level: var_requestedLevel,
            max_reasoning_level: var_maxReasoningLevel,
            available_memory_mb: var_availableMemoryMb,
            gpu_available: var_gpuAvailable,
            npu_available: var_npuAvailable,
            thermal_constrained: var_thermalConstrained,
            battery_constrained: var_batteryConstrained,
            memories: var_memories,
            documents: var_documents,
            tool_results: var_toolResults,
            history: var_history,
            tool_names: var_toolNames,
        };
    }
}

impl SseDecode for crate::api::reasoning::ReasoningStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::reasoning::ReasoningStage::Understanding,
            1 => crate::api::reasoning::ReasoningStage::RetrievingContext,
            2 => crate::api::reasoning::ReasoningStage::UsingTool,
            3 => crate::api::reasoning::ReasoningStage::Analyzing,
            4 => crate::api::reasoning::ReasoningStage::Validating,
            5 => crate::api::reasoning::ReasoningStage::ComposingAnswer,
            6 => crate::api::reasoning::ReasoningStage::Complete,
            _ => unreachable!("Invalid variant for ReasoningStage: {}", inner),
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        4 => wire__crate__api__minutes__generate_completion_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__minutes__generate_minutes_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__minutes__initialize_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__meeting_intelligence__process_meeting_intelligence_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => wire__crate__api__reasoning__reason_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__minutes__cancel_generation_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__meeting_intelligence__cancel_meeting_intelligence_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__reasoning__cancel_reasoning_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__minutes__generation_model_id_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__minutes__generation_stats_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__minutes__is_ready_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__minutes__unload_generation_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::minutes::GenerationConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.models_dir.into_into_dart().into_dart(),
            self.memory_budget_mb.into_into_dart().into_dart(),
            self.prefer_indic_generation.into_into_dart().into_dart(),
            self.allow_compact_fallback.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::minutes::GenerationConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::minutes::GenerationConfig>
    for crate::api::minutes::GenerationConfig
{
    fn into_into_dart(self) -> crate::api::minutes::GenerationConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::minutes::GenerationEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::minutes::GenerationEvent::Generating { text } => {
                [0.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minutes::GenerationEvent::MinutesReady { text } => {
                [1.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minutes::GenerationEvent::Cancelled => [2.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::minutes::GenerationEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::minutes::GenerationEvent>
    for crate::api::minutes::GenerationEvent
{
    fn into_into_dart(self) -> crate::api::minutes::GenerationEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::minutes::GenerationStats {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.prefill_ms.into_into_dart().into_dart(),
            self.prefill_tokens.into_into_dart().into_dart(),
            self.generation_ms.into_into_dart().into_dart(),
            self.generated_tokens.into_into_dart().into_dart(),
            self.tokens_per_second.into_into_dart().into_dart(),
            self.peak_rss_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::minutes::GenerationStats
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::minutes::GenerationStats>
    for crate::api::minutes::GenerationStats
{
    fn into_into_dart(self) -> crate::api::minutes::GenerationStats {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::meeting_intelligence::MeetingActionItemRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.task.into_into_dart().into_dart(),
            self.owner.into_into_dart().into_dart(),
            self.due.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.evidence_segment_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingActionItemRecord
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingActionItemRecord>
    for crate::api::meeting_intelligence::MeetingActionItemRecord
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingActionItemRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::meeting_intelligence::MeetingActionStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Open => 0.into_dart(),
            Self::InProgress => 1.into_dart(),
            Self::Done => 2.into_dart(),
            Self::Blocked => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingActionStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingActionStatus>
    for crate::api::meeting_intelligence::MeetingActionStatus
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingActionStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::meeting_intelligence::MeetingDecisionRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.statement.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.evidence_segment_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingDecisionRecord
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingDecisionRecord>
    for crate::api::meeting_intelligence::MeetingDecisionRecord
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingDecisionRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::meeting_intelligence::MeetingDecisionStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Proposed => 0.into_dart(),
            Self::Agreed => 1.into_dart(),
            Self::Rejected => 2.into_dart(),
            Self::Deferred => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingDecisionStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingDecisionStatus>
    for crate::api::meeting_intelligence::MeetingDecisionStatus
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingDecisionStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::meeting_intelligence::MeetingIntelligenceEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::Extracting => {
                [0.into_dart()].into_dart()
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::Generating { text } => {
                [1.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::MinutesReady { text } => {
                [2.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::IrReady {
                decisions,
                action_items,
                metrics,
            } => [
                3.into_dart(),
                decisions.into_into_dart().into_dart(),
                action_items.into_into_dart().into_dart(),
                metrics.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::Cancelled => {
                [4.into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingIntelligenceEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingIntelligenceEvent>
    for crate::api::meeting_intelligence::MeetingIntelligenceEvent
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingIntelligenceEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::api::meeting_intelligence::MeetingIntelligenceSegment
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.start_ms.into_into_dart().into_dart(),
            self.end_ms.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingIntelligenceSegment
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingIntelligenceSegment>
    for crate::api::meeting_intelligence::MeetingIntelligenceSegment
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingIntelligenceSegment {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::meeting_intelligence::MeetingMetricRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.evidence_segment_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::meeting_intelligence::MeetingMetricRecord
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::meeting_intelligence::MeetingMetricRecord>
    for crate::api::meeting_intelligence::MeetingMetricRecord
{
    fn into_into_dart(self) -> crate::api::meeting_intelligence::MeetingMetricRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::reasoning::ReasoningContextItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::reasoning::ReasoningContextItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::reasoning::ReasoningContextItem>
    for crate::api::reasoning::ReasoningContextItem
{
    fn into_into_dart(self) -> crate::api::reasoning::ReasoningContextItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::reasoning::ReasoningEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::reasoning::ReasoningEvent::Started => [0.into_dart()].into_dart(),
            crate::api::reasoning::ReasoningEvent::StageChanged { stage } => {
                [1.into_dart(), stage.into_into_dart().into_dart()].into_dart()
            }
            crate::api::reasoning::ReasoningEvent::Progress { message } => {
                [2.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::reasoning::ReasoningEvent::ToolStarted { tool } => {
                [3.into_dart(), tool.into_into_dart().into_dart()].into_dart()
            }
            crate::api::reasoning::ReasoningEvent::ToolCompleted { tool } => {
                [4.into_dart(), tool.into_into_dart().into_dart()].into_dart()
            }
            crate::api::reasoning::ReasoningEvent::AnswerDelta { text } => {
                [5.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::api::reasoning::ReasoningEvent::Completed {
                answer,
                reasoning_summary,
                level,
                confidence,
            } => [
                6.into_dart(),
                answer.into_into_dart().into_dart(),
                reasoning_summary.into_into_dart().into_dart(),
                level.into_into_dart().into_dart(),
                confidence.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::reasoning::ReasoningEvent::Error { message } => {
                [7.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::reasoning::ReasoningEvent::Cancelled => [8.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::reasoning::ReasoningEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::reasoning::ReasoningEvent>
    for crate::api::reasoning::ReasoningEvent
{
    fn into_into_dart(self) -> crate::api::reasoning::ReasoningEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::reasoning::ReasoningLevel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::None => 0.into_dart(),
            Self::Light => 1.into_dart(),
            Self::Standard => 2.into_dart(),
            Self::Deep => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::reasoning::ReasoningLevel
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::reasoning::ReasoningLevel>
    for crate::api::reasoning::ReasoningLevel
{
    fn into_into_dart(self) -> crate::api::reasoning::ReasoningLevel {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::reasoning::ReasoningRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.user_query.into_into_dart().into_dart(),
            self.intent_kind.into_into_dart().into_dart(),
            self.intent_complexity.into_into_dart().into_dart(),
            self.requested_level.into_into_dart().into_dart(),
            self.max_reasoning_level.into_into_dart().into_dart(),
            self.available_memory_mb.into_into_dart().into_dart(),
            self.gpu_available.into_into_dart().into_dart(),
            self.npu_available.into_into_dart().into_dart(),
            self.thermal_constrained.into_into_dart().into_dart(),
            self.battery_constrained.into_into_dart().into_dart(),
            self.memories.into_into_dart().into_dart(),
            self.documents.into_into_dart().into_dart(),
            self.tool_results.into_into_dart().into_dart(),
            self.history.into_into_dart().into_dart(),
            self.tool_names.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::reasoning::ReasoningRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::reasoning::ReasoningRequest>
    for crate::api::reasoning::ReasoningRequest
{
    fn into_into_dart(self) -> crate::api::reasoning::ReasoningRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::reasoning::ReasoningStage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Understanding => 0.into_dart(),
            Self::RetrievingContext => 1.into_dart(),
            Self::UsingTool => 2.into_dart(),
            Self::Analyzing => 3.into_dart(),
            Self::Validating => 4.into_dart(),
            Self::ComposingAnswer => 5.into_dart(),
            Self::Complete => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::reasoning::ReasoningStage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::reasoning::ReasoningStage>
    for crate::api::reasoning::ReasoningStage
{
    fn into_into_dart(self) -> crate::api::reasoning::ReasoningStage {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::minutes::GenerationEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::meeting_intelligence::MeetingIntelligenceEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::reasoning::ReasoningEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::minutes::GenerationConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.models_dir, serializer);
        <u32>::sse_encode(self.memory_budget_mb, serializer);
        <bool>::sse_encode(self.prefer_indic_generation, serializer);
        <bool>::sse_encode(self.allow_compact_fallback, serializer);
    }
}

impl SseEncode for crate::api::minutes::GenerationEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::minutes::GenerationEvent::Generating { text } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::minutes::GenerationEvent::MinutesReady { text } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::minutes::GenerationEvent::Cancelled => {
                <i32>::sse_encode(2, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::minutes::GenerationStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.prefill_ms, serializer);
        <u32>::sse_encode(self.prefill_tokens, serializer);
        <u64>::sse_encode(self.generation_ms, serializer);
        <u32>::sse_encode(self.generated_tokens, serializer);
        <f64>::sse_encode(self.tokens_per_second, serializer);
        <u64>::sse_encode(self.peak_rss_bytes, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::meeting_intelligence::MeetingActionItemRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::meeting_intelligence::MeetingActionItemRecord>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode for Vec<crate::api::meeting_intelligence::MeetingDecisionRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::meeting_intelligence::MeetingDecisionRecord>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::meeting_intelligence::MeetingIntelligenceSegment> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::meeting_intelligence::MeetingIntelligenceSegment>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode for Vec<crate::api::meeting_intelligence::MeetingMetricRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::meeting_intelligence::MeetingMetricRecord>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::reasoning::ReasoningContextItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::reasoning::ReasoningContextItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingActionItemRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.task, serializer);
        <Option<String>>::sse_encode(self.owner, serializer);
        <Option<String>>::sse_encode(self.due, serializer);
        <crate::api::meeting_intelligence::MeetingActionStatus>::sse_encode(
            self.status,
            serializer,
        );
        <Vec<String>>::sse_encode(self.evidence_segment_ids, serializer);
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingActionStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::meeting_intelligence::MeetingActionStatus::Open => 0,
                crate::api::meeting_intelligence::MeetingActionStatus::InProgress => 1,
                crate::api::meeting_intelligence::MeetingActionStatus::Done => 2,
                crate::api::meeting_intelligence::MeetingActionStatus::Blocked => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingDecisionRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.statement, serializer);
        <crate::api::meeting_intelligence::MeetingDecisionStatus>::sse_encode(
            self.status,
            serializer,
        );
        <Vec<String>>::sse_encode(self.evidence_segment_ids, serializer);
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingDecisionStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::meeting_intelligence::MeetingDecisionStatus::Proposed => 0,
                crate::api::meeting_intelligence::MeetingDecisionStatus::Agreed => 1,
                crate::api::meeting_intelligence::MeetingDecisionStatus::Rejected => 2,
                crate::api::meeting_intelligence::MeetingDecisionStatus::Deferred => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingIntelligenceEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::Extracting => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::Generating { text } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::MinutesReady { text } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::IrReady {
                decisions,
                action_items,
                metrics,
            } => {
                <i32>::sse_encode(3, serializer);
                <Vec<crate::api::meeting_intelligence::MeetingDecisionRecord>>::sse_encode(
                    decisions, serializer,
                );
                <Vec<crate::api::meeting_intelligence::MeetingActionItemRecord>>::sse_encode(
                    action_items,
                    serializer,
                );
                <Vec<crate::api::meeting_intelligence::MeetingMetricRecord>>::sse_encode(
                    metrics, serializer,
                );
            }
            crate::api::meeting_intelligence::MeetingIntelligenceEvent::Cancelled => {
                <i32>::sse_encode(4, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingIntelligenceSegment {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <u64>::sse_encode(self.start_ms, serializer);
        <u64>::sse_encode(self.end_ms, serializer);
        <String>::sse_encode(self.text, serializer);
    }
}

impl SseEncode for crate::api::meeting_intelligence::MeetingMetricRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.value, serializer);
        <Vec<String>>::sse_encode(self.evidence_segment_ids, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::reasoning::ReasoningLevel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::reasoning::ReasoningLevel>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::reasoning::ReasoningContextItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.source, serializer);
        <String>::sse_encode(self.text, serializer);
    }
}

impl SseEncode for crate::api::reasoning::ReasoningEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::reasoning::ReasoningEvent::Started => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::reasoning::ReasoningEvent::StageChanged { stage } => {
                <i32>::sse_encode(1, serializer);
                <crate::api::reasoning::ReasoningStage>::sse_encode(stage, serializer);
            }
            crate::api::reasoning::ReasoningEvent::Progress { message } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::reasoning::ReasoningEvent::ToolStarted { tool } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(tool, serializer);
            }
            crate::api::reasoning::ReasoningEvent::ToolCompleted { tool } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(tool, serializer);
            }
            crate::api::reasoning::ReasoningEvent::AnswerDelta { text } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::reasoning::ReasoningEvent::Completed {
                answer,
                reasoning_summary,
                level,
                confidence,
            } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(answer, serializer);
                <Option<String>>::sse_encode(reasoning_summary, serializer);
                <crate::api::reasoning::ReasoningLevel>::sse_encode(level, serializer);
                <Option<f32>>::sse_encode(confidence, serializer);
            }
            crate::api::reasoning::ReasoningEvent::Error { message } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::reasoning::ReasoningEvent::Cancelled => {
                <i32>::sse_encode(8, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::reasoning::ReasoningLevel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::reasoning::ReasoningLevel::None => 0,
                crate::api::reasoning::ReasoningLevel::Light => 1,
                crate::api::reasoning::ReasoningLevel::Standard => 2,
                crate::api::reasoning::ReasoningLevel::Deep => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::reasoning::ReasoningRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.user_query, serializer);
        <String>::sse_encode(self.intent_kind, serializer);
        <f32>::sse_encode(self.intent_complexity, serializer);
        <Option<crate::api::reasoning::ReasoningLevel>>::sse_encode(
            self.requested_level,
            serializer,
        );
        <crate::api::reasoning::ReasoningLevel>::sse_encode(self.max_reasoning_level, serializer);
        <u32>::sse_encode(self.available_memory_mb, serializer);
        <bool>::sse_encode(self.gpu_available, serializer);
        <bool>::sse_encode(self.npu_available, serializer);
        <bool>::sse_encode(self.thermal_constrained, serializer);
        <bool>::sse_encode(self.battery_constrained, serializer);
        <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_encode(self.memories, serializer);
        <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_encode(self.documents, serializer);
        <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_encode(
            self.tool_results,
            serializer,
        );
        <Vec<crate::api::reasoning::ReasoningContextItem>>::sse_encode(self.history, serializer);
        <Vec<String>>::sse_encode(self.tool_names, serializer);
    }
}

impl SseEncode for crate::api::reasoning::ReasoningStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::reasoning::ReasoningStage::Understanding => 0,
                crate::api::reasoning::ReasoningStage::RetrievingContext => 1,
                crate::api::reasoning::ReasoningStage::UsingTool => 2,
                crate::api::reasoning::ReasoningStage::Analyzing => 3,
                crate::api::reasoning::ReasoningStage::Validating => 4,
                crate::api::reasoning::ReasoningStage::ComposingAnswer => 5,
                crate::api::reasoning::ReasoningStage::Complete => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
