// `deny`, not `forbid`. An FFI boundary is unsafe by construction -- the
// generated bridge dereferences pointers handed over by Dart -- and `forbid`
// cannot be lifted anywhere, including on generated code.
//
// The allowance is granted on exactly one module, `frb_generated`, which is
// machine-written and never edited.
#![deny(unsafe_code)]
//! Airo Mind's speech half: whisper.cpp, the meeting library, and the bridge
//! Flutter calls for both.
//!
//! # Why this is its own library
//!
//! whisper.cpp and llama.cpp each statically vendor their own copy of ggml.
//! Same symbol names, 348 files of difference between the trees. One library
//! containing both is a one-definition-rule conflict between two upstream
//! projects, and every linker handles it differently and badly: Android's lld
//! refuses (20+ duplicate symbols), a merged static archive fails outright
//! (592), and Apple's linker links it while emitting 339 duplicate-symbol
//! warnings and choosing an implementation per symbol by link order.
//!
//! So each engine gets its own cdylib. rustc's version script exports only the
//! bridge entry points, so neither library's ggml is visible to the other even
//! when both are loaded into one process. `airo_mind_core` is what they share,
//! and it is std-only precisely so that sharing it is safe.
//!
//! # What lives here rather than in llama's library
//!
//! The **meeting library** -- store, index, save, search, open. Transcripts are
//! what the store holds and what the index is built from, so they sit with the
//! engine that produces them. Generation contributes minutes to a record that
//! is created here.

#[cfg(feature = "whisper")]
pub mod api;

#[cfg(feature = "whisper")]
#[allow(
    // The only unsafe in the crate. See the crate-level note above.
    unsafe_code,
    clippy::all,
    dead_code,
    unused_imports,
    non_snake_case,
    non_camel_case_types,
    missing_docs,
    clippy::needless_lifetimes
)]
// Generated by `flutter_rust_bridge_codegen`. Never edited by hand -- the
// generator overwrites it, so a fix made here is a fix that disappears.
mod frb_generated;

#[cfg(feature = "whisper")]
mod whisper;

/// `transcript.json` persistence (`#1629` Gap D). Only used by `api::meetings`,
/// gated the same way.
#[cfg(feature = "whisper")]
mod transcript_store;

// `use`, not `mod`: the engine and the setup surface moved here from the old
// combined crate unchanged, and `crate::engine::…` / `crate::models::…` keep
// resolving. The definitions live in `airo_mind_core`.
#[cfg_attr(not(feature = "whisper"), allow(unused_imports))]
pub(crate) use airo_mind_core::{budget, cancel, engine, models};

/// Used by `api::setup`, the only caller outside `models`.
#[cfg(feature = "whisper")]
pub(crate) use airo_mind_core::file_digest as digest_file;

#[cfg(feature = "whisper")]
pub use whisper::WhisperSpeechEngine;

// Re-exported so a consumer of this library does not have to name the core
// crate to use the types this one hands back.
pub use airo_mind_core::{
    AudioInput, CancelToken, EngineError, Hit, Meeting, MeetingStore, ResourceBudget,
    ResourceRequest, RuntimeError, SearchIndex, SpeechEngine, Supervisor, TranscriptSegment,
    TranscriptionOptions,
};
