name: storage_sqlite
description: Component for storage_sqlite
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform_storage:
    path: ../platform_storage
  platform_vector_store:
    path: ../platform_vector_store
  drift: ^2.34.0
  sqlite3_flutter_libs: ^0.6.0+eol

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
