// AUTO-GENERATED by flutter_rust_bridge_codegen.
// Run `flutter_rust_bridge_codegen generate` from the repo root to regenerate.
//
// This stub is checked in so the package compiles before the native library
// is built. The real generated file replaces it when codegen runs.

// ignore_for_file: unused_import, prefer_const_constructors

/// Stub: calls the Rust normalize_channel_name via FFI.
/// Replaced by real generated code after `flutter_rust_bridge_codegen generate`.
String normalizeChannelName({required String name}) {
  throw NativeBridgeUnavailableException(
    'flutter_rust_bridge_codegen has not been run yet. '
    'Run `flutter_rust_bridge_codegen generate` from the repo root.',
  );
}

/// Stub: calls the Rust parse_m3u_entries via FFI.
/// Replaced by real generated code after `flutter_rust_bridge_codegen generate`.
List<FrbM3uEntry> parseM3uEntries({required String content}) {
  throw NativeBridgeUnavailableException(
    'flutter_rust_bridge_codegen has not been run yet. '
    'Run `flutter_rust_bridge_codegen generate` from the repo root.',
  );
}

/// Stub: calls the Rust parse_xmltv_programmes via FFI.
/// Replaced by real generated code after `flutter_rust_bridge_codegen generate`.
FrbXmltvParseResult parseXmltvProgrammes({
  required String content,
  required int maxProgrammes,
}) {
  throw NativeBridgeUnavailableException(
    'flutter_rust_bridge_codegen has not been run yet. '
    'Run `flutter_rust_bridge_codegen generate` from the repo root.',
  );
}

/// Stub: calls the Rust parse_xmltv_programmes_file via FFI.
/// Replaced by real generated code after `flutter_rust_bridge_codegen generate`.
FrbXmltvParseResult parseXmltvProgrammesFile({
  required String path,
  required int maxProgrammes,
}) {
  throw NativeBridgeUnavailableException(
    'flutter_rust_bridge_codegen has not been run yet. '
    'Run `flutter_rust_bridge_codegen generate` from the repo root.',
  );
}

class FrbM3uEntry {
  const FrbM3uEntry({
    required this.name,
    required this.url,
    this.logo,
    this.group,
    this.tvgId,
    this.tvgName,
    this.language,
  });

  final String name;
  final String url;
  final String? logo;
  final String? group;
  final String? tvgId;
  final String? tvgName;
  final String? language;
}

class FrbXmltvProgramme {
  const FrbXmltvProgramme({
    required this.channelId,
    required this.start,
    this.stop,
    this.title,
  });

  final String channelId;
  final String start;
  final String? stop;
  final String? title;
}

class FrbXmltvParseStats {
  const FrbXmltvParseStats({
    required this.programmeCount,
    required this.skippedProgrammeCount,
    required this.truncated,
  });

  final int programmeCount;
  final int skippedProgrammeCount;
  final bool truncated;
}

class FrbXmltvParseResult {
  const FrbXmltvParseResult({required this.programmes, required this.stats});

  final List<FrbXmltvProgramme> programmes;
  final FrbXmltvParseStats stats;
}

class NativeBridgeUnavailableException implements Exception {
  const NativeBridgeUnavailableException(this.message);

  final String message;

  @override
  String toString() => 'NativeBridgeUnavailableException: $message';
}
