// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/m3u.dart';
import 'api/text.dart';
import 'api/xmltv.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1828127264;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'airo_core',
        ioDirectory: '../../rust/airo_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<M3uChannelParseResult> crateApiM3UM3UChannelParseResultDefault();

  Future<M3uParseResult> crateApiM3UM3UParseResultDefault();

  Future<M3uParseStats> crateApiM3UM3UParseStatsDefault();

  Future<M3uPlaylist> crateApiM3UM3UPlaylistDefault();

  Future<String> crateApiTextNormalizeChannelName({required String name});

  Future<M3uChannelParseResult> crateApiM3UParseM3UChannelsWithStats({
    required String content,
  });

  Future<List<M3uEntry>> crateApiM3UParseM3UEntries({required String content});

  Future<M3uChannelParseResult> crateApiM3UParseM3UFileChannelsWithStats({
    required String path,
  });

  Future<M3uParseResult> crateApiM3UParseM3UFileWithStats({
    required String path,
  });

  Future<M3uPlaylist> crateApiM3UParseM3UPlaylist({required String content});

  Future<M3uParseResult> crateApiM3UParseM3UWithStats({
    required String content,
  });

  Future<XmltvCurrentNextResult> crateApiXmltvParseXmltvCurrentNextFile({
    required String path,
    required List<String> channelIds,
    required PlatformInt64 nowEpochSeconds,
    required int defaultDurationSeconds,
  });

  Future<XmltvParseResult> crateApiXmltvParseXmltvProgrammes({
    required String content,
    required int maxProgrammes,
  });

  Future<XmltvParseResult> crateApiXmltvParseXmltvProgrammesFile({
    required String path,
    required int maxProgrammes,
  });

  Future<XmltvCurrentNextResult> crateApiXmltvXmltvCurrentNextResultDefault();

  Future<XmltvCurrentNextStats> crateApiXmltvXmltvCurrentNextStatsDefault();

  Future<XmltvParseResult> crateApiXmltvXmltvParseResultDefault();

  Future<XmltvParseStats> crateApiXmltvXmltvParseStatsDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<M3uChannelParseResult> crateApiM3UM3UChannelParseResultDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_channel_parse_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3Um3UChannelParseResultDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3Um3UChannelParseResultDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "m_3_u_channel_parse_result_default",
        argNames: [],
      );

  @override
  Future<M3uParseResult> crateApiM3UM3UParseResultDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_parse_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3Um3UParseResultDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3Um3UParseResultDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "m_3_u_parse_result_default",
        argNames: [],
      );

  @override
  Future<M3uParseStats> crateApiM3UM3UParseStatsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_parse_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3Um3UParseStatsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3Um3UParseStatsDefaultConstMeta =>
      const TaskConstMeta(debugName: "m_3_u_parse_stats_default", argNames: []);

  @override
  Future<M3uPlaylist> crateApiM3UM3UPlaylistDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_playlist,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3Um3UPlaylistDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3Um3UPlaylistDefaultConstMeta =>
      const TaskConstMeta(debugName: "m_3_u_playlist_default", argNames: []);

  @override
  Future<String> crateApiTextNormalizeChannelName({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTextNormalizeChannelNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTextNormalizeChannelNameConstMeta =>
      const TaskConstMeta(
        debugName: "normalize_channel_name",
        argNames: ["name"],
      );

  @override
  Future<M3uChannelParseResult> crateApiM3UParseM3UChannelsWithStats({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_channel_parse_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3UParseM3UChannelsWithStatsConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3UParseM3UChannelsWithStatsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_m3u_channels_with_stats",
        argNames: ["content"],
      );

  @override
  Future<List<M3uEntry>> crateApiM3UParseM3UEntries({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_m_3_u_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3UParseM3UEntriesConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3UParseM3UEntriesConstMeta => const TaskConstMeta(
    debugName: "parse_m3u_entries",
    argNames: ["content"],
  );

  @override
  Future<M3uChannelParseResult> crateApiM3UParseM3UFileChannelsWithStats({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_channel_parse_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiM3UParseM3UFileChannelsWithStatsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3UParseM3UFileChannelsWithStatsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_m3u_file_channels_with_stats",
        argNames: ["path"],
      );

  @override
  Future<M3uParseResult> crateApiM3UParseM3UFileWithStats({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_parse_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiM3UParseM3UFileWithStatsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3UParseM3UFileWithStatsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_m3u_file_with_stats",
        argNames: ["path"],
      );

  @override
  Future<M3uPlaylist> crateApiM3UParseM3UPlaylist({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_playlist,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3UParseM3UPlaylistConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3UParseM3UPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "parse_m3u_playlist",
        argNames: ["content"],
      );

  @override
  Future<M3uParseResult> crateApiM3UParseM3UWithStats({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_m_3_u_parse_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiM3UParseM3UWithStatsConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiM3UParseM3UWithStatsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_m3u_with_stats",
        argNames: ["content"],
      );

  @override
  Future<XmltvCurrentNextResult> crateApiXmltvParseXmltvCurrentNextFile({
    required String path,
    required List<String> channelIds,
    required PlatformInt64 nowEpochSeconds,
    required int defaultDurationSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_String(channelIds, serializer);
          sse_encode_i_64(nowEpochSeconds, serializer);
          sse_encode_u_32(defaultDurationSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_current_next_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiXmltvParseXmltvCurrentNextFileConstMeta,
        argValues: [path, channelIds, nowEpochSeconds, defaultDurationSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvParseXmltvCurrentNextFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_xmltv_current_next_file",
        argNames: [
          "path",
          "channelIds",
          "nowEpochSeconds",
          "defaultDurationSeconds",
        ],
      );

  @override
  Future<XmltvParseResult> crateApiXmltvParseXmltvProgrammes({
    required String content,
    required int maxProgrammes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          sse_encode_u_32(maxProgrammes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_parse_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiXmltvParseXmltvProgrammesConstMeta,
        argValues: [content, maxProgrammes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvParseXmltvProgrammesConstMeta =>
      const TaskConstMeta(
        debugName: "parse_xmltv_programmes",
        argNames: ["content", "maxProgrammes"],
      );

  @override
  Future<XmltvParseResult> crateApiXmltvParseXmltvProgrammesFile({
    required String path,
    required int maxProgrammes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(maxProgrammes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_parse_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiXmltvParseXmltvProgrammesFileConstMeta,
        argValues: [path, maxProgrammes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvParseXmltvProgrammesFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_xmltv_programmes_file",
        argNames: ["path", "maxProgrammes"],
      );

  @override
  Future<XmltvCurrentNextResult> crateApiXmltvXmltvCurrentNextResultDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_current_next_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiXmltvXmltvCurrentNextResultDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvXmltvCurrentNextResultDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "xmltv_current_next_result_default",
        argNames: [],
      );

  @override
  Future<XmltvCurrentNextStats> crateApiXmltvXmltvCurrentNextStatsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_current_next_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiXmltvXmltvCurrentNextStatsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvXmltvCurrentNextStatsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "xmltv_current_next_stats_default",
        argNames: [],
      );

  @override
  Future<XmltvParseResult> crateApiXmltvXmltvParseResultDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_parse_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiXmltvXmltvParseResultDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvXmltvParseResultDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "xmltv_parse_result_default",
        argNames: [],
      );

  @override
  Future<XmltvParseStats> crateApiXmltvXmltvParseStatsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xmltv_parse_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiXmltvXmltvParseStatsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXmltvXmltvParseStatsDefaultConstMeta =>
      const TaskConstMeta(debugName: "xmltv_parse_stats_default", argNames: []);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  XmltvProgramme dco_decode_box_autoadd_xmltv_programme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_xmltv_programme(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<M3uChannel> dco_decode_list_m_3_u_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_m_3_u_channel).toList();
  }

  @protected
  List<M3uEntry> dco_decode_list_m_3_u_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_m_3_u_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<XmltvCurrentNextEntry> dco_decode_list_xmltv_current_next_entry(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_xmltv_current_next_entry)
        .toList();
  }

  @protected
  List<XmltvProgramme> dco_decode_list_xmltv_programme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_xmltv_programme).toList();
  }

  @protected
  M3uChannel dco_decode_m_3_u_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return M3uChannel(
      name: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      logo: dco_decode_opt_String(arr[2]),
      group: dco_decode_opt_String(arr[3]),
      tvgId: dco_decode_opt_String(arr[4]),
      tvgName: dco_decode_opt_String(arr[5]),
      language: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  M3uChannelParseResult dco_decode_m_3_u_channel_parse_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return M3uChannelParseResult(
      channels: dco_decode_list_m_3_u_channel(arr[0]),
      stats: dco_decode_m_3_u_parse_stats(arr[1]),
    );
  }

  @protected
  M3uEntry dco_decode_m_3_u_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return M3uEntry(
      name: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      logo: dco_decode_opt_String(arr[2]),
      group: dco_decode_opt_String(arr[3]),
      tvgId: dco_decode_opt_String(arr[4]),
      tvgName: dco_decode_opt_String(arr[5]),
      language: dco_decode_opt_String(arr[6]),
      duration: dco_decode_opt_box_autoadd_i_64(arr[7]),
      extras: dco_decode_Map_String_String_None(arr[8]),
    );
  }

  @protected
  M3uParseResult dco_decode_m_3_u_parse_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return M3uParseResult(
      playlist: dco_decode_m_3_u_playlist(arr[0]),
      stats: dco_decode_m_3_u_parse_stats(arr[1]),
    );
  }

  @protected
  M3uParseStats dco_decode_m_3_u_parse_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return M3uParseStats(
      parsedCount: dco_decode_u_32(arr[0]),
      skippedCount: dco_decode_u_32(arr[1]),
      malformedCount: dco_decode_u_32(arr[2]),
      elapsedMillis: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  M3uPlaylist dco_decode_m_3_u_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return M3uPlaylist(
      entries: dco_decode_list_m_3_u_entry(arr[0]),
      headers: dco_decode_Map_String_String_None(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  XmltvProgramme? dco_decode_opt_box_autoadd_xmltv_programme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_xmltv_programme(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  XmltvCurrentNextEntry dco_decode_xmltv_current_next_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return XmltvCurrentNextEntry(
      channelId: dco_decode_String(arr[0]),
      current: dco_decode_opt_box_autoadd_xmltv_programme(arr[1]),
      next: dco_decode_opt_box_autoadd_xmltv_programme(arr[2]),
    );
  }

  @protected
  XmltvCurrentNextResult dco_decode_xmltv_current_next_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return XmltvCurrentNextResult(
      entries: dco_decode_list_xmltv_current_next_entry(arr[0]),
      stats: dco_decode_xmltv_current_next_stats(arr[1]),
    );
  }

  @protected
  XmltvCurrentNextStats dco_decode_xmltv_current_next_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return XmltvCurrentNextStats(
      programmeCount: dco_decode_u_32(arr[0]),
      skippedProgrammeCount: dco_decode_u_32(arr[1]),
      invalidTimestampCount: dco_decode_u_32(arr[2]),
      matchedProgrammeCount: dco_decode_u_32(arr[3]),
      requestedChannelCount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  XmltvParseResult dco_decode_xmltv_parse_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return XmltvParseResult(
      programmes: dco_decode_list_xmltv_programme(arr[0]),
      stats: dco_decode_xmltv_parse_stats(arr[1]),
    );
  }

  @protected
  XmltvParseStats dco_decode_xmltv_parse_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return XmltvParseStats(
      programmeCount: dco_decode_u_32(arr[0]),
      skippedProgrammeCount: dco_decode_u_32(arr[1]),
      truncated: dco_decode_bool(arr[2]),
    );
  }

  @protected
  XmltvProgramme dco_decode_xmltv_programme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return XmltvProgramme(
      channelId: dco_decode_String(arr[0]),
      start: dco_decode_String(arr[1]),
      stop: dco_decode_opt_String(arr[2]),
      title: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  XmltvProgramme sse_decode_box_autoadd_xmltv_programme(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_xmltv_programme(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<M3uChannel> sse_decode_list_m_3_u_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <M3uChannel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_m_3_u_channel(deserializer));
    }
    return ans_;
  }

  @protected
  List<M3uEntry> sse_decode_list_m_3_u_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <M3uEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_m_3_u_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<XmltvCurrentNextEntry> sse_decode_list_xmltv_current_next_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <XmltvCurrentNextEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_xmltv_current_next_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<XmltvProgramme> sse_decode_list_xmltv_programme(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <XmltvProgramme>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_xmltv_programme(deserializer));
    }
    return ans_;
  }

  @protected
  M3uChannel sse_decode_m_3_u_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_logo = sse_decode_opt_String(deserializer);
    var var_group = sse_decode_opt_String(deserializer);
    var var_tvgId = sse_decode_opt_String(deserializer);
    var var_tvgName = sse_decode_opt_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    return M3uChannel(
      name: var_name,
      url: var_url,
      logo: var_logo,
      group: var_group,
      tvgId: var_tvgId,
      tvgName: var_tvgName,
      language: var_language,
    );
  }

  @protected
  M3uChannelParseResult sse_decode_m_3_u_channel_parse_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channels = sse_decode_list_m_3_u_channel(deserializer);
    var var_stats = sse_decode_m_3_u_parse_stats(deserializer);
    return M3uChannelParseResult(channels: var_channels, stats: var_stats);
  }

  @protected
  M3uEntry sse_decode_m_3_u_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_logo = sse_decode_opt_String(deserializer);
    var var_group = sse_decode_opt_String(deserializer);
    var var_tvgId = sse_decode_opt_String(deserializer);
    var var_tvgName = sse_decode_opt_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_extras = sse_decode_Map_String_String_None(deserializer);
    return M3uEntry(
      name: var_name,
      url: var_url,
      logo: var_logo,
      group: var_group,
      tvgId: var_tvgId,
      tvgName: var_tvgName,
      language: var_language,
      duration: var_duration,
      extras: var_extras,
    );
  }

  @protected
  M3uParseResult sse_decode_m_3_u_parse_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playlist = sse_decode_m_3_u_playlist(deserializer);
    var var_stats = sse_decode_m_3_u_parse_stats(deserializer);
    return M3uParseResult(playlist: var_playlist, stats: var_stats);
  }

  @protected
  M3uParseStats sse_decode_m_3_u_parse_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_parsedCount = sse_decode_u_32(deserializer);
    var var_skippedCount = sse_decode_u_32(deserializer);
    var var_malformedCount = sse_decode_u_32(deserializer);
    var var_elapsedMillis = sse_decode_i_64(deserializer);
    return M3uParseStats(
      parsedCount: var_parsedCount,
      skippedCount: var_skippedCount,
      malformedCount: var_malformedCount,
      elapsedMillis: var_elapsedMillis,
    );
  }

  @protected
  M3uPlaylist sse_decode_m_3_u_playlist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entries = sse_decode_list_m_3_u_entry(deserializer);
    var var_headers = sse_decode_Map_String_String_None(deserializer);
    return M3uPlaylist(entries: var_entries, headers: var_headers);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  XmltvProgramme? sse_decode_opt_box_autoadd_xmltv_programme(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_xmltv_programme(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  XmltvCurrentNextEntry sse_decode_xmltv_current_next_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channelId = sse_decode_String(deserializer);
    var var_current = sse_decode_opt_box_autoadd_xmltv_programme(deserializer);
    var var_next = sse_decode_opt_box_autoadd_xmltv_programme(deserializer);
    return XmltvCurrentNextEntry(
      channelId: var_channelId,
      current: var_current,
      next: var_next,
    );
  }

  @protected
  XmltvCurrentNextResult sse_decode_xmltv_current_next_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entries = sse_decode_list_xmltv_current_next_entry(deserializer);
    var var_stats = sse_decode_xmltv_current_next_stats(deserializer);
    return XmltvCurrentNextResult(entries: var_entries, stats: var_stats);
  }

  @protected
  XmltvCurrentNextStats sse_decode_xmltv_current_next_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_programmeCount = sse_decode_u_32(deserializer);
    var var_skippedProgrammeCount = sse_decode_u_32(deserializer);
    var var_invalidTimestampCount = sse_decode_u_32(deserializer);
    var var_matchedProgrammeCount = sse_decode_u_32(deserializer);
    var var_requestedChannelCount = sse_decode_u_32(deserializer);
    return XmltvCurrentNextStats(
      programmeCount: var_programmeCount,
      skippedProgrammeCount: var_skippedProgrammeCount,
      invalidTimestampCount: var_invalidTimestampCount,
      matchedProgrammeCount: var_matchedProgrammeCount,
      requestedChannelCount: var_requestedChannelCount,
    );
  }

  @protected
  XmltvParseResult sse_decode_xmltv_parse_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_programmes = sse_decode_list_xmltv_programme(deserializer);
    var var_stats = sse_decode_xmltv_parse_stats(deserializer);
    return XmltvParseResult(programmes: var_programmes, stats: var_stats);
  }

  @protected
  XmltvParseStats sse_decode_xmltv_parse_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_programmeCount = sse_decode_u_32(deserializer);
    var var_skippedProgrammeCount = sse_decode_u_32(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    return XmltvParseStats(
      programmeCount: var_programmeCount,
      skippedProgrammeCount: var_skippedProgrammeCount,
      truncated: var_truncated,
    );
  }

  @protected
  XmltvProgramme sse_decode_xmltv_programme(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channelId = sse_decode_String(deserializer);
    var var_start = sse_decode_String(deserializer);
    var var_stop = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    return XmltvProgramme(
      channelId: var_channelId,
      start: var_start,
      stop: var_stop,
      title: var_title,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_xmltv_programme(
    XmltvProgramme self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_xmltv_programme(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_m_3_u_channel(
    List<M3uChannel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_m_3_u_channel(item, serializer);
    }
  }

  @protected
  void sse_encode_list_m_3_u_entry(
    List<M3uEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_m_3_u_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_xmltv_current_next_entry(
    List<XmltvCurrentNextEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_xmltv_current_next_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_xmltv_programme(
    List<XmltvProgramme> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_xmltv_programme(item, serializer);
    }
  }

  @protected
  void sse_encode_m_3_u_channel(M3uChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.logo, serializer);
    sse_encode_opt_String(self.group, serializer);
    sse_encode_opt_String(self.tvgId, serializer);
    sse_encode_opt_String(self.tvgName, serializer);
    sse_encode_opt_String(self.language, serializer);
  }

  @protected
  void sse_encode_m_3_u_channel_parse_result(
    M3uChannelParseResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_m_3_u_channel(self.channels, serializer);
    sse_encode_m_3_u_parse_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_m_3_u_entry(M3uEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.logo, serializer);
    sse_encode_opt_String(self.group, serializer);
    sse_encode_opt_String(self.tvgId, serializer);
    sse_encode_opt_String(self.tvgName, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_box_autoadd_i_64(self.duration, serializer);
    sse_encode_Map_String_String_None(self.extras, serializer);
  }

  @protected
  void sse_encode_m_3_u_parse_result(
    M3uParseResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_m_3_u_playlist(self.playlist, serializer);
    sse_encode_m_3_u_parse_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_m_3_u_parse_stats(
    M3uParseStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.parsedCount, serializer);
    sse_encode_u_32(self.skippedCount, serializer);
    sse_encode_u_32(self.malformedCount, serializer);
    sse_encode_i_64(self.elapsedMillis, serializer);
  }

  @protected
  void sse_encode_m_3_u_playlist(M3uPlaylist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_m_3_u_entry(self.entries, serializer);
    sse_encode_Map_String_String_None(self.headers, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_xmltv_programme(
    XmltvProgramme? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_xmltv_programme(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_xmltv_current_next_entry(
    XmltvCurrentNextEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.channelId, serializer);
    sse_encode_opt_box_autoadd_xmltv_programme(self.current, serializer);
    sse_encode_opt_box_autoadd_xmltv_programme(self.next, serializer);
  }

  @protected
  void sse_encode_xmltv_current_next_result(
    XmltvCurrentNextResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_xmltv_current_next_entry(self.entries, serializer);
    sse_encode_xmltv_current_next_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_xmltv_current_next_stats(
    XmltvCurrentNextStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.programmeCount, serializer);
    sse_encode_u_32(self.skippedProgrammeCount, serializer);
    sse_encode_u_32(self.invalidTimestampCount, serializer);
    sse_encode_u_32(self.matchedProgrammeCount, serializer);
    sse_encode_u_32(self.requestedChannelCount, serializer);
  }

  @protected
  void sse_encode_xmltv_parse_result(
    XmltvParseResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_xmltv_programme(self.programmes, serializer);
    sse_encode_xmltv_parse_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_xmltv_parse_stats(
    XmltvParseStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.programmeCount, serializer);
    sse_encode_u_32(self.skippedProgrammeCount, serializer);
    sse_encode_bool(self.truncated, serializer);
  }

  @protected
  void sse_encode_xmltv_programme(
    XmltvProgramme self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.channelId, serializer);
    sse_encode_String(self.start, serializer);
    sse_encode_opt_String(self.stop, serializer);
    sse_encode_opt_String(self.title, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
