// AUTO-GENERATED by flutter_rust_bridge_codegen.
// Run `flutter_rust_bridge_codegen generate` from the repo root to regenerate.
//
// This stub is checked in so the package compiles before the native library
// is built. The real generated file replaces it when codegen runs.

// ignore_for_file: unused_import, prefer_const_constructors

/// Stub: calls the Rust normalize_channel_name via FFI.
/// Replaced by real generated code after `flutter_rust_bridge_codegen generate`.
String normalizeChannelName({required String name}) {
  throw NativeBridgeUnavailableException(
    'flutter_rust_bridge_codegen has not been run yet. '
    'Run `flutter_rust_bridge_codegen generate` from the repo root.',
  );
}

class NativeBridgeUnavailableException implements Exception {
  const NativeBridgeUnavailableException(this.message);

  final String message;

  @override
  String toString() => 'NativeBridgeUnavailableException: $message';
}
