// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'api/m3u.dart';
import 'api/text.dart';
import 'api/xmltv.dart';
import 'frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  XmltvProgramme dco_decode_box_autoadd_xmltv_programme(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<M3uEntry> dco_decode_list_m_3_u_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<XmltvCurrentNextEntry> dco_decode_list_xmltv_current_next_entry(
    dynamic raw,
  );

  @protected
  List<XmltvProgramme> dco_decode_list_xmltv_programme(dynamic raw);

  @protected
  M3uEntry dco_decode_m_3_u_entry(dynamic raw);

  @protected
  M3uPlaylist dco_decode_m_3_u_playlist(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  XmltvProgramme? dco_decode_opt_box_autoadd_xmltv_programme(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  XmltvCurrentNextEntry dco_decode_xmltv_current_next_entry(dynamic raw);

  @protected
  XmltvCurrentNextResult dco_decode_xmltv_current_next_result(dynamic raw);

  @protected
  XmltvCurrentNextStats dco_decode_xmltv_current_next_stats(dynamic raw);

  @protected
  XmltvParseResult dco_decode_xmltv_parse_result(dynamic raw);

  @protected
  XmltvParseStats dco_decode_xmltv_parse_stats(dynamic raw);

  @protected
  XmltvProgramme dco_decode_xmltv_programme(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  XmltvProgramme sse_decode_box_autoadd_xmltv_programme(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<M3uEntry> sse_decode_list_m_3_u_entry(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<XmltvCurrentNextEntry> sse_decode_list_xmltv_current_next_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<XmltvProgramme> sse_decode_list_xmltv_programme(
    SseDeserializer deserializer,
  );

  @protected
  M3uEntry sse_decode_m_3_u_entry(SseDeserializer deserializer);

  @protected
  M3uPlaylist sse_decode_m_3_u_playlist(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  XmltvProgramme? sse_decode_opt_box_autoadd_xmltv_programme(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  XmltvCurrentNextEntry sse_decode_xmltv_current_next_entry(
    SseDeserializer deserializer,
  );

  @protected
  XmltvCurrentNextResult sse_decode_xmltv_current_next_result(
    SseDeserializer deserializer,
  );

  @protected
  XmltvCurrentNextStats sse_decode_xmltv_current_next_stats(
    SseDeserializer deserializer,
  );

  @protected
  XmltvParseResult sse_decode_xmltv_parse_result(SseDeserializer deserializer);

  @protected
  XmltvParseStats sse_decode_xmltv_parse_stats(SseDeserializer deserializer);

  @protected
  XmltvProgramme sse_decode_xmltv_programme(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_xmltv_programme(
    XmltvProgramme self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_m_3_u_entry(
    List<M3uEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_xmltv_current_next_entry(
    List<XmltvCurrentNextEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_xmltv_programme(
    List<XmltvProgramme> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_m_3_u_entry(M3uEntry self, SseSerializer serializer);

  @protected
  void sse_encode_m_3_u_playlist(M3uPlaylist self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_xmltv_programme(
    XmltvProgramme? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_xmltv_current_next_entry(
    XmltvCurrentNextEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xmltv_current_next_result(
    XmltvCurrentNextResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xmltv_current_next_stats(
    XmltvCurrentNextStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xmltv_parse_result(
    XmltvParseResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xmltv_parse_stats(
    XmltvParseStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xmltv_programme(
    XmltvProgramme self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary();
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
