name: platform_indexing
description: Component for platform_indexing
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  platform_content:
    path: ../platform_content
  flutter:
    sdk: flutter
  platform_contracts:
    path: ../platform_contracts
  platform_identity:
    path: ../platform_identity

  platform_parser:
    path: ../platform_parser
  platform_scheduler:
    path: ../platform_scheduler
  platform_pipeline:
    path: ../platform_pipeline
dev_dependencies:
  platform_content:
    path: ../platform_content
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
