name: platform_indexing
description: Component for platform_indexing
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform_contracts:
    path: ../platform_contracts
  platform_identity:
    path: ../platform_identity

  platform_documents:
    path: ../platform_documents
  platform_scheduler:
    path: ../platform_scheduler
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
