name: platform_native
description: Core infrastructure for managing native execution, FFI, and dynamic libraries.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mocktail: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
