import 'package:core_ui/core_ui.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platform_channels/platform_channels.dart';

import '../../application/providers/rails_provider.dart';
import '../widgets/channel_initials.dart';

/// The unified browse body (spec §5.2): rail list generated by the Media
/// Engine, rendered identically on phone/tablet/TV/desktop. Only spacing,
/// card sizes, and focus behavior adapt per form factor.
class BrowseScreen extends ConsumerWidget {
  const BrowseScreen({super.key, this.onChannelSelected});

  /// Invoked when a card is tapped/selected. The host screen decides
  /// whether that means "play inline", "open player route", etc.
  final void Function(IPTVChannel channel)? onChannelSelected;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final rails = ref.watch(railsProvider);
    return rails.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => Center(
        child: Text('Could not build rails: $error'),
      ),
      data: (results) => ListView(
        padding: const EdgeInsets.only(top: 12, bottom: 20),
        children: [
          for (final result in results)
            AiroRail(
              title: result.definition.title,
              subtitle: result.definition.subtitle,
              // Height derives from the same variant the cards use below
              // (AiroRail.cardVariant → MediaCard.railHeightFor), so rail
              // and card sizing can never drift out of sync.
              cardVariant: _variantFor(result.definition.layout),
              children: [
                for (final channel in result.channels)
                  MediaCard(
                    name: channel.name,
                    subtitle: channel.group,
                    logoUrl: channel.logoUrl,
                    initials: channelInitials(channel.name),
                    variant: _variantFor(result.definition.layout),
                    onTap: () => onChannelSelected?.call(channel),
                  ),
              ],
            ),
        ],
      ),
    );
  }

  /// [MediaCardVariant] for each [RailLayout].
  static MediaCardVariant _variantFor(RailLayout layout) => switch (layout) {
        RailLayout.compact => MediaCardVariant.compact,
        RailLayout.standard => MediaCardVariant.standard,
        RailLayout.hero => MediaCardVariant.hero,
      };
}
