import 'package:core_ui/core_ui.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platform_channels/platform_channels.dart';

import '../../application/providers/rails_provider.dart';
import '../widgets/channel_initials.dart';

/// The unified browse body (spec §5.2): rail list generated by the Media
/// Engine, rendered identically on phone/tablet/TV/desktop. Only spacing,
/// card sizes, and focus behavior adapt per form factor.
class BrowseScreen extends ConsumerWidget {
  const BrowseScreen({super.key, this.onChannelSelected});

  /// Invoked when a card is tapped/selected. The host screen decides
  /// whether that means "play inline", "open player route", etc.
  final void Function(IPTVChannel channel)? onChannelSelected;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final rails = ref.watch(railsProvider);
    return rails.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => Center(
        child: Text('Could not build rails: $error'),
      ),
      data: (results) => ListView(
        padding: const EdgeInsets.only(top: 12, bottom: 20),
        children: [
          for (final result in results)
            AiroRail(
              title: result.definition.title,
              subtitle: result.definition.subtitle,
              // AiroRail's own default (156) is sized for a bare thumbnail
              // plus a two-line label; it doesn't leave room for the
              // border + padding a real MediaCard renders (measured
              // overflow otherwise), so size explicitly per variant here.
              railHeight: _railHeightFor(result.definition.layout),
              children: [
                for (final channel in result.channels)
                  MediaCard(
                    name: channel.name,
                    subtitle: channel.group,
                    logoUrl: channel.logoUrl,
                    initials: channelInitials(channel.name),
                    variant: _variantFor(result.definition.layout),
                    onTap: () => onChannelSelected?.call(channel),
                  ),
              ],
            ),
        ],
      ),
    );
  }

  /// Rail height (thumbnail + name/subtitle text block + card border/padding
  /// + the rail's own list-view inset) for each [RailLayout], matching the
  /// thumbnail sizes [MediaCard] uses per [MediaCardVariant].
  static double _railHeightFor(RailLayout layout) {
    final thumbnailHeight = switch (layout) {
      RailLayout.compact => 84.0,
      RailLayout.standard => 104.0,
      RailLayout.hero => 180.0,
    };
    return thumbnailHeight + 64;
  }

  /// [MediaCardVariant] for each [RailLayout], matching [_railHeightFor]
  /// exactly so a rail's card size always fits the band height it renders
  /// in — a mismatch here overflows (e.g. a compact-height rail rendering
  /// standard-sized cards).
  static MediaCardVariant _variantFor(RailLayout layout) => switch (layout) {
        RailLayout.compact => MediaCardVariant.compact,
        RailLayout.standard => MediaCardVariant.standard,
        RailLayout.hero => MediaCardVariant.hero,
      };
}
