import 'package:core_ui/core_ui.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platform_channels/platform_channels.dart';

import '../../application/providers/iptv_providers.dart';
import '../../application/providers/rails_provider.dart';
import '../tv_ux/widgets/tv_continue_watching_scaffold.dart';
import '../widgets/channel_initials.dart';

/// The unified browse body (spec §5.2): rail list generated by the Media
/// Engine, rendered identically on phone/tablet/TV/desktop. Only spacing,
/// card sizes, and focus behavior adapt per form factor.
class BrowseScreen extends ConsumerStatefulWidget {
  const BrowseScreen({super.key, this.onChannelSelected});

  /// Invoked when a card is tapped/selected. The host screen decides
  /// whether that means "play inline", "open player route", etc.
  final void Function(IPTVChannel channel)? onChannelSelected;

  @override
  ConsumerState<BrowseScreen> createState() => _BrowseScreenState();
}

class _BrowseScreenState extends ConsumerState<BrowseScreen> {
  var _showContinueWatchingHint = false;

  @override
  Widget build(BuildContext context) {
    final rails = ref.watch(railsProvider);
    return rails.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => Center(child: Text('Could not build rails: $error')),
      data: (results) => TvContinueWatchingScaffold(
        showRemoveHint: _showContinueWatchingHint,
        child: ListView(
          padding: const EdgeInsets.only(top: 12, bottom: 88),
          children: [
            for (final result in results)
              _buildRail(context, result),
          ],
        ),
      ),
    );
  }

  Widget _buildRail(BuildContext context, RailResult result) {
    final isContinueWatching = result.definition.id == 'recently-watched';
    final cardVariant = isContinueWatching
        ? MediaCardVariant.continueWatching
        : _variantFor(result.definition.layout);

    return AiroRail(
      title: result.definition.title,
      subtitle: result.definition.subtitle,
      cardVariant: cardVariant,
      children: [
        for (final channel in result.channels)
          MediaCard(
            name: channel.name,
            subtitle: channel.group,
            logoUrl: channel.logoUrl,
            initials: channelInitials(channel.name),
            variant: cardVariant,
            showResumeBadge: isContinueWatching,
            isLive: false,
            selectLongPressForSecondary: isContinueWatching,
            onTap: () => widget.onChannelSelected?.call(channel),
            onLongPress: isContinueWatching
                ? () => _removeFromContinueWatching(channel.id)
                : () => _toggleFavorite(context, channel),
            onFocus: isContinueWatching
                ? () => setState(() => _showContinueWatchingHint = true)
                : null,
            onUnfocus: isContinueWatching
                ? () => setState(() => _showContinueWatchingHint = false)
                : null,
          ),
      ],
    );
  }

  Future<void> _removeFromContinueWatching(String channelId) async {
    await ref.read(removeFromRecentlyWatchedProvider(channelId).future);
    if (!mounted) return;
    setState(() => _showContinueWatchingHint = false);
  }

  Future<void> _toggleFavorite(
    BuildContext context,
    IPTVChannel channel,
  ) async {
    final isNowFavorite = await ref.read(channelFavoriteTogglerProvider)(
      channel.id,
    );
    if (!context.mounted) return;
    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(
        SnackBar(
          content: Text(
            isNowFavorite
                ? '${channel.name} added to favorites'
                : '${channel.name} removed from favorites',
          ),
          duration: const Duration(seconds: 2),
        ),
      );
  }

  /// [MediaCardVariant] for each [RailLayout].
  static MediaCardVariant _variantFor(RailLayout layout) => switch (layout) {
    RailLayout.compact => MediaCardVariant.compact,
    RailLayout.standard => MediaCardVariant.standard,
    RailLayout.hero => MediaCardVariant.hero,
  };
}
