name: platform_execution
description: Component for platform_execution
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  platform_graph:
    path: ../platform_graph
  flutter:
    sdk: flutter
  platform_identity:
    path: ../platform_identity

dev_dependencies:
  platform_graph:
    path: ../platform_graph
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
