name: platform_planner
description: Component for platform_planner
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform_execution:
    path: ../platform_execution
  platform_pipeline:
    path: ../platform_pipeline

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
