//! `ContextId` — an identifier that has already been canonicalized.
//!
//! `I6` requires canonicalization exactly once, at the boundary, and states the
//! defect test directly: *"a function that accepts a raw value and a canonical
//! one at the same type is a defect: the type must distinguish them, or the raw
//! form must be unreachable past the boundary."*
//!
//! A normalization call inside the Vault would satisfy neither half. Phase 1
//! takes ids from its caller, so if the Vault normalized *and* Phase 2's
//! runtime normalized, that is canonicalization twice -- which `I6` forbids in
//! the same breath: *"re-canonicalizing hides the layer that forgot."* A
//! `ContextId` cannot be re-canonicalized. It can only be constructed from a
//! raw `&str`, exactly once, wherever the boundary currently is.
//!
//! # Why ASCII rather than NFC
//!
//! `Freeze §4` requires subject ids to be *"NFC-normalized and rejected if they
//! contain control characters."* This type enforces **printable ASCII**, which
//! is strictly stronger: every ASCII string is already in NFC, because no ASCII
//! scalar has a canonical decomposition. So the frozen requirement is satisfied
//! rather than amended, and no ADR is needed.
//!
//! The alternative was a `unicode-normalization` dependency, which Constitution
//! §6 gates behind a scorecard and chief-open-source-officer sign-off -- a human
//! gate, on the crypto path, for a case Phase 1 does not have: **identity
//! strings are minted by the runtime, not typed by a user.** User-visible names
//! arrive with the Phase 2 ontology layer, and `SEC-14`'s ruling already
//! separates them: a name may be reused, the identity behind it may not.
//!
//! If Phase 2 ever needs user-typed identifiers, widening ASCII to NFC is a
//! constructor change in one file, and every existing id remains valid because
//! ASCII is a subset of NFC.

use std::fmt;

use super::error::VaultError;

/// A canonical context identifier. Construction is the only canonicalization
/// point in the crate.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContextId(String);

impl ContextId {
    /// The boundary. Rejects anything that is not printable ASCII.
    ///
    /// `SEC-32` reproduced the failure this closes: destroy a context, re-add
    /// the same name in NFD, and the retired identity is resurrected while
    /// `is_content_destroyed` reports it live -- a crypto-shredding bypass
    /// reachable by keystroke rather than by attack. Two ids differing only by
    /// Unicode form are different subjects, so destroying one does not revoke
    /// the other.
    pub fn new(raw: &str) -> Result<Self, VaultError> {
        if raw.is_empty() {
            return Err(VaultError::InvalidIdentifier);
        }
        // Printable ASCII only: rejects control characters (`\r`, `\n`,
        // `\0`), bidi overrides such as U+202E, and every non-NFC form at
        // once, because a non-ASCII byte cannot appear at all.
        if !raw.bytes().all(|b| (0x20..0x7f).contains(&b)) {
            return Err(VaultError::InvalidIdentifier);
        }
        Ok(Self(raw.to_string()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Test-only shorthand. Not `pub`: production code constructs at the boundary
/// and handles the error, which is the point of the type.
#[cfg(test)]
pub(crate) fn cid(raw: &str) -> ContextId {
    ContextId::new(raw).expect("test identifier must be canonical")
}

impl fmt::Display for ContextId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

// `SEC-47`. `Freeze §4`'s row says "Subject ids", and `RevocationSubject` has
// three variants. `ContextId` covered one. Content is the DIRECT subject of
// crypto-shredding, and since §4.1 removed all per-content state from the
// Vault, `is_content_revoked` is the only defence for content deletion --
// against a BTreeMap keyed by byte equality. Probed: destroy `café` NFC, re-add
// `café` NFD, and the destroyed content is live while `is_content_destroyed`
// reports false.
//
// Written out rather than generated by a macro. `L1.1` scans source text for
// `pub` items, so a macro-generated type is INVISIBLE to it -- adding
// `canonical_id!(FooId, ...)` would put a new type on the public surface with
// no allowlist entry and no gate failure. Twenty lines is cheaper than a hole
// in the gate that guards every other public item.
//
// The predicate still exists exactly once: both delegate to `ContextId::new`.

/// A canonical content identifier. See `ContextId`.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContentId(String);

impl ContentId {
    pub fn new(raw: &str) -> Result<Self, VaultError> {
        ContextId::new(raw).map(|c| Self(c.as_str().to_string()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ContentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// A canonical device identifier. See `ContextId`.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DeviceId(String);

impl DeviceId {
    pub fn new(raw: &str) -> Result<Self, VaultError> {
        ContextId::new(raw).map(|c| Self(c.as_str().to_string()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for DeviceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

#[cfg(test)]
pub(crate) fn content_id(raw: &str) -> ContentId {
    ContentId::new(raw).expect("test identifier must be canonical")
}

#[cfg(test)]
mod tests {
    use super::*;
    #[allow(unused_imports)]
    use crate::vault::identifier::{cid, content_id, ContentId, DeviceId};

    #[test]
    fn rejects_the_sec_32_bypass_inputs() {
        // NFD "café" -- the exact input that resurrected a retired identity.
        assert!(ContextId::new("cafe\u{301}").is_err());
        assert!(ContextId::new("a\u{0}b").is_err());
        assert!(ContextId::new("a\nb").is_err());
        assert!(ContextId::new("\u{202E}evil").is_err());
        assert!(ContextId::new("").is_err());
    }

    #[test]
    fn accepts_the_ids_the_runtime_mints() {
        for ok in ["inbox", "tax-2026", "ctx-000000000001", "a:b", "A_b.c"] {
            assert_eq!(ContextId::new(ok).unwrap().as_str(), ok);
        }
    }

    #[test]
    fn ascii_is_already_nfc_so_two_ids_cannot_differ_by_form() {
        // The property `Freeze §4` asks for, in its failing form: there is no
        // pair of accepted ids that are canonically equivalent yet unequal.
        let a = ContextId::new("cafe").unwrap();
        assert!(ContextId::new("cafe\u{301}").is_err());
        assert_eq!(a.as_str(), "cafe");
    }
}
