name: core_analytics
description: Local privacy-first analytics, telemetry filters, and vendor-neutral event reporting engine.
version: 1.0.0
homepage: https://developerscoffee.com
repository: https://github.com/DevelopersCoffee/airo_analytics
issue_tracker: https://github.com/DevelopersCoffee/airo_analytics/issues

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  airo_analytics: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
