// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'runtime_contracts.dart';

// These functions are ignored because they are not marked as `pub`: `fail`, `health`, `next_jitter`, `record`, `telemetry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<MockRuntime> mockRuntimeNew({required MockConfig config}) =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeNew(config: config);

Future<FailureInjection> mockFailureInjectionDefault() =>
    RustLib.instance.api.crateApiMockRuntimeMockFailureInjectionDefault();

Future<RuntimeCapabilities> mockRuntimeCapabilities() =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeCapabilities();

Future<RuntimeRegistry> runtimeRegistryNew() =>
    RustLib.instance.api.crateApiMockRuntimeRuntimeRegistryNew();

Future<void> runtimeRegistryRegisterMock({required RuntimeRegistry registry}) =>
    RustLib.instance.api.crateApiMockRuntimeRuntimeRegistryRegisterMock(
      registry: registry,
    );

Future<bool> runtimeRegistryContainsMock({required RuntimeRegistry registry}) =>
    RustLib.instance.api.crateApiMockRuntimeRuntimeRegistryContainsMock(
      registry: registry,
    );

Future<RuntimeHealth> mockRuntimeInitialize({required MockRuntime runtime}) =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeInitialize(
      runtime: runtime,
    );

Future<List<String>> mockRuntimeGenerate({
  required MockRuntime runtime,
  required InferenceIr ir,
  required int tokenCount,
}) => RustLib.instance.api.crateApiMockRuntimeMockRuntimeGenerate(
  runtime: runtime,
  ir: ir,
  tokenCount: tokenCount,
);

Future<void> mockRuntimeCancel({required MockRuntime runtime}) =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeCancel(runtime: runtime);

Future<RuntimeHealth> mockRuntimeShutdown({required MockRuntime runtime}) =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeShutdown(
      runtime: runtime,
    );

Future<RuntimeHealth> mockRuntimeHealth({required MockRuntime runtime}) =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeHealth(runtime: runtime);

Future<List<ExecutionTraceEntry>> mockRuntimeTrace({
  required MockRuntime runtime,
}) =>
    RustLib.instance.api.crateApiMockRuntimeMockRuntimeTrace(runtime: runtime);

Future<List<TelemetryEvent>> mockRuntimeTelemetry({
  required MockRuntime runtime,
}) => RustLib.instance.api.crateApiMockRuntimeMockRuntimeTelemetry(
  runtime: runtime,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MockRuntime>>
abstract class MockRuntime implements RustOpaqueInterface {
  MockConfig get config;

  RuntimeSession get session;

  TelemetryStub get telemetry;

  ExecutionTrace get trace;

  set config(MockConfig config);

  set session(RuntimeSession session);

  set telemetry(TelemetryStub telemetry);

  set trace(ExecutionTrace trace);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeRegistry>>
abstract class RuntimeRegistry implements RustOpaqueInterface {
  RuntimeApiVersion get contractVersion;

  List<RuntimeId> get runtimes;

  set contractVersion(RuntimeApiVersion contractVersion);

  set runtimes(List<RuntimeId> runtimes);
}

class ExecutionTrace {
  const ExecutionTrace({required this.entries});
  final List<ExecutionTraceEntry> entries;

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionTrace &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}

class ExecutionTraceEntry {
  const ExecutionTraceEntry({
    required this.sequence,
    required this.event,
    required this.elapsedMs,
  });
  final int sequence;
  final String event;
  final BigInt elapsedMs;

  @override
  int get hashCode => sequence.hashCode ^ event.hashCode ^ elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionTraceEntry &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          event == other.event &&
          elapsedMs == other.elapsedMs;
}

class FailureInjection {
  const FailureInjection({
    this.error,
    this.afterTokens,
    this.cancelAfterTokens,
  });
  final RuntimeErrorCode? error;
  final int? afterTokens;
  final int? cancelAfterTokens;

  @override
  int get hashCode =>
      error.hashCode ^ afterTokens.hashCode ^ cancelAfterTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FailureInjection &&
          runtimeType == other.runtimeType &&
          error == other.error &&
          afterTokens == other.afterTokens &&
          cancelAfterTokens == other.cancelAfterTokens;
}

class MockConfig {
  const MockConfig({
    required this.startupDelayMs,
    required this.firstTokenDelayMs,
    required this.tokenDelayMs,
    required this.tokenRate,
    required this.seed,
    this.failure,
    this.failAfterTokens,
    this.cancelAfterTokens,
  });
  final BigInt startupDelayMs;
  final BigInt firstTokenDelayMs;
  final BigInt tokenDelayMs;
  final int tokenRate;
  final BigInt seed;
  final RuntimeErrorCode? failure;
  final int? failAfterTokens;
  final int? cancelAfterTokens;

  static Future<MockConfig> default_() =>
      RustLib.instance.api.crateApiMockRuntimeMockConfigDefault();

  @override
  int get hashCode =>
      startupDelayMs.hashCode ^
      firstTokenDelayMs.hashCode ^
      tokenDelayMs.hashCode ^
      tokenRate.hashCode ^
      seed.hashCode ^
      failure.hashCode ^
      failAfterTokens.hashCode ^
      cancelAfterTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MockConfig &&
          runtimeType == other.runtimeType &&
          startupDelayMs == other.startupDelayMs &&
          firstTokenDelayMs == other.firstTokenDelayMs &&
          tokenDelayMs == other.tokenDelayMs &&
          tokenRate == other.tokenRate &&
          seed == other.seed &&
          failure == other.failure &&
          failAfterTokens == other.failAfterTokens &&
          cancelAfterTokens == other.cancelAfterTokens;
}

class RuntimeSession {
  const RuntimeSession({
    required this.sessionId,
    required this.state,
    required this.generatedTokens,
  });
  final String sessionId;
  final RuntimeHealthState state;
  final int generatedTokens;

  @override
  int get hashCode =>
      sessionId.hashCode ^ state.hashCode ^ generatedTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          state == other.state &&
          generatedTokens == other.generatedTokens;
}

class TelemetryEvent {
  const TelemetryEvent({
    required this.sequence,
    required this.event,
    required this.elapsedMs,
    this.error,
  });
  final int sequence;
  final String event;
  final BigInt elapsedMs;
  final RuntimeErrorCode? error;

  @override
  int get hashCode =>
      sequence.hashCode ^ event.hashCode ^ elapsedMs.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelemetryEvent &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          event == other.event &&
          elapsedMs == other.elapsedMs &&
          error == other.error;
}

class TelemetryStub {
  const TelemetryStub({required this.events});
  final List<TelemetryEvent> events;

  @override
  int get hashCode => events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelemetryStub &&
          runtimeType == other.runtimeType &&
          events == other.events;
}
