// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `normalized_clock`, `parse_timestamp`, `parse_timing_line`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<RecommendationScore>> rankRecommendations({
  required List<RecommendationCandidate> candidates,
}) => RustLib.instance.api.crateApiNativeEngineRankRecommendations(
  candidates: candidates,
);

Future<VectorClockRelation> compareVectorClocks({
  required List<VectorClockCounter> left,
  required List<VectorClockCounter> right,
}) => RustLib.instance.api.crateApiNativeEngineCompareVectorClocks(
  left: left,
  right: right,
);

Future<SubtitleParseResult> parseSubtitles({
  required String content,
  required SubtitleFormat format,
}) => RustLib.instance.api.crateApiNativeEngineParseSubtitles(
  content: content,
  format: format,
);

class RecommendationCandidate {
  const RecommendationCandidate({
    required this.id,
    required this.title,
    required this.genreAffinity,
    required this.providerAffinity,
    required this.languageAffinity,
    required this.preferredTime,
    required this.deviceFit,
    this.completionPermille,
    this.lastWatchedAgeDays,
  });
  final String id;
  final String title;
  final PlatformInt64 genreAffinity;
  final PlatformInt64 providerAffinity;
  final PlatformInt64 languageAffinity;
  final int? completionPermille;
  final int? lastWatchedAgeDays;
  final bool preferredTime;
  final bool deviceFit;

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      genreAffinity.hashCode ^
      providerAffinity.hashCode ^
      languageAffinity.hashCode ^
      completionPermille.hashCode ^
      lastWatchedAgeDays.hashCode ^
      preferredTime.hashCode ^
      deviceFit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationCandidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          genreAffinity == other.genreAffinity &&
          providerAffinity == other.providerAffinity &&
          languageAffinity == other.languageAffinity &&
          completionPermille == other.completionPermille &&
          lastWatchedAgeDays == other.lastWatchedAgeDays &&
          preferredTime == other.preferredTime &&
          deviceFit == other.deviceFit;
}

class RecommendationScore {
  const RecommendationScore({
    required this.id,
    required this.score,
    required this.genrePoints,
    required this.providerPoints,
    required this.languagePoints,
    required this.completionPoints,
    required this.recencyPoints,
    required this.timeBucketPoints,
    required this.deviceFitPoints,
  });
  final String id;
  final PlatformInt64 score;
  final PlatformInt64 genrePoints;
  final PlatformInt64 providerPoints;
  final PlatformInt64 languagePoints;
  final PlatformInt64 completionPoints;
  final PlatformInt64 recencyPoints;
  final PlatformInt64 timeBucketPoints;
  final PlatformInt64 deviceFitPoints;

  @override
  int get hashCode =>
      id.hashCode ^
      score.hashCode ^
      genrePoints.hashCode ^
      providerPoints.hashCode ^
      languagePoints.hashCode ^
      completionPoints.hashCode ^
      recencyPoints.hashCode ^
      timeBucketPoints.hashCode ^
      deviceFitPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationScore &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          score == other.score &&
          genrePoints == other.genrePoints &&
          providerPoints == other.providerPoints &&
          languagePoints == other.languagePoints &&
          completionPoints == other.completionPoints &&
          recencyPoints == other.recencyPoints &&
          timeBucketPoints == other.timeBucketPoints &&
          deviceFitPoints == other.deviceFitPoints;
}

class SubtitleCue {
  const SubtitleCue({
    required this.startMillis,
    required this.endMillis,
    required this.text,
  });
  final BigInt startMillis;
  final BigInt endMillis;
  final String text;

  @override
  int get hashCode => startMillis.hashCode ^ endMillis.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleCue &&
          runtimeType == other.runtimeType &&
          startMillis == other.startMillis &&
          endMillis == other.endMillis &&
          text == other.text;
}

enum SubtitleFormat { srt, webVtt }

class SubtitleParseResult {
  const SubtitleParseResult({
    required this.cues,
    required this.malformedCueCount,
    required this.truncated,
  });
  final List<SubtitleCue> cues;
  final int malformedCueCount;
  final bool truncated;

  @override
  int get hashCode =>
      cues.hashCode ^ malformedCueCount.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleParseResult &&
          runtimeType == other.runtimeType &&
          cues == other.cues &&
          malformedCueCount == other.malformedCueCount &&
          truncated == other.truncated;
}

class VectorClockCounter {
  const VectorClockCounter({required this.nodeId, required this.counter});
  final String nodeId;
  final BigInt counter;

  @override
  int get hashCode => nodeId.hashCode ^ counter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VectorClockCounter &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          counter == other.counter;
}

enum VectorClockRelation { equal, leftDominates, rightDominates, concurrent }
