// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'runtime_contracts.dart';

// These functions are ignored because they are not marked as `pub`: `failure`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Pure planner entry point. It performs no I/O, platform calls, or runtime
/// calls; all observations arrive as arguments.
Future<PlannerResult> planInference({
  required InferenceRequest request,
  required DeviceProfile device,
  required List<ModelManifest> models,
  required RuntimeRegistry registry,
  required PlannerConfig config,
}) => RustLib.instance.api.crateApiPlannerPlanInference(
  request: request,
  device: device,
  models: models,
  registry: registry,
  config: config,
);

class DeviceProfile {
  const DeviceProfile({
    required this.totalMemoryMb,
    required this.availableMemoryMb,
    required this.accelerator,
    required this.thermalLimited,
    required this.batterySaver,
  });
  final BigInt totalMemoryMb;
  final BigInt availableMemoryMb;
  final ComputeAccelerator accelerator;
  final bool thermalLimited;
  final bool batterySaver;

  @override
  int get hashCode =>
      totalMemoryMb.hashCode ^
      availableMemoryMb.hashCode ^
      accelerator.hashCode ^
      thermalLimited.hashCode ^
      batterySaver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceProfile &&
          runtimeType == other.runtimeType &&
          totalMemoryMb == other.totalMemoryMb &&
          availableMemoryMb == other.availableMemoryMb &&
          accelerator == other.accelerator &&
          thermalLimited == other.thermalLimited &&
          batterySaver == other.batterySaver;
}

class ExecutionPlan {
  const ExecutionPlan({
    required this.ir,
    required this.batchSize,
    required this.thermalLimited,
    required this.batterySaver,
  });
  final InferenceIr ir;
  final int batchSize;
  final bool thermalLimited;
  final bool batterySaver;

  @override
  int get hashCode =>
      ir.hashCode ^
      batchSize.hashCode ^
      thermalLimited.hashCode ^
      batterySaver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionPlan &&
          runtimeType == other.runtimeType &&
          ir == other.ir &&
          batchSize == other.batchSize &&
          thermalLimited == other.thermalLimited &&
          batterySaver == other.batterySaver;
}

class ModelManifest {
  const ModelManifest({
    required this.id,
    required this.capability,
    required this.estimatedPeakMemoryMb,
    required this.maxContextTokens,
    this.preferredRuntime,
    this.preferredAccelerator,
  });
  final String id;
  final CapabilityId capability;
  final BigInt estimatedPeakMemoryMb;
  final int maxContextTokens;
  final RuntimeId? preferredRuntime;
  final ComputeAccelerator? preferredAccelerator;

  @override
  int get hashCode =>
      id.hashCode ^
      capability.hashCode ^
      estimatedPeakMemoryMb.hashCode ^
      maxContextTokens.hashCode ^
      preferredRuntime.hashCode ^
      preferredAccelerator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelManifest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          capability == other.capability &&
          estimatedPeakMemoryMb == other.estimatedPeakMemoryMb &&
          maxContextTokens == other.maxContextTokens &&
          preferredRuntime == other.preferredRuntime &&
          preferredAccelerator == other.preferredAccelerator;
}

class PlannerConfig {
  const PlannerConfig({
    required this.defaultContextTokens,
    required this.minimumContextTokens,
    required this.defaultOutputTokens,
    required this.minimumOutputTokens,
    required this.batchSize,
    required this.temperature,
    required this.topK,
    required this.topP,
  });
  final int defaultContextTokens;
  final int minimumContextTokens;
  final int defaultOutputTokens;
  final int minimumOutputTokens;
  final int batchSize;
  final double temperature;
  final int topK;
  final double topP;

  static Future<PlannerConfig> default_() =>
      RustLib.instance.api.crateApiPlannerPlannerConfigDefault();

  @override
  int get hashCode =>
      defaultContextTokens.hashCode ^
      minimumContextTokens.hashCode ^
      defaultOutputTokens.hashCode ^
      minimumOutputTokens.hashCode ^
      batchSize.hashCode ^
      temperature.hashCode ^
      topK.hashCode ^
      topP.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlannerConfig &&
          runtimeType == other.runtimeType &&
          defaultContextTokens == other.defaultContextTokens &&
          minimumContextTokens == other.minimumContextTokens &&
          defaultOutputTokens == other.defaultOutputTokens &&
          minimumOutputTokens == other.minimumOutputTokens &&
          batchSize == other.batchSize &&
          temperature == other.temperature &&
          topK == other.topK &&
          topP == other.topP;
}

enum PlannerErrorCode {
  noCapabilityMatch,
  noRuntimeAvailable,
  insufficientMemory,
  unsupportedAccelerator,
  invalidConfiguration,
}

class PlannerResult {
  const PlannerResult({this.plan, this.error});
  final ExecutionPlan? plan;
  final PlannerErrorCode? error;

  @override
  int get hashCode => plan.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlannerResult &&
          runtimeType == other.runtimeType &&
          plan == other.plan &&
          error == other.error;
}
