// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_migration`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

Future<RelationalStoreStatus> initializeRelationalStore({
  required String path,
}) => RustLib.instance.api.crateApiRelationalStoreInitializeRelationalStore(
  path: path,
);

class RelationalStoreStatus {
  const RelationalStoreStatus({
    required this.schemaVersion,
    required this.foreignKeysEnabled,
  });
  final int schemaVersion;
  final bool foreignKeysEnabled;

  @override
  int get hashCode => schemaVersion.hashCode ^ foreignKeysEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationalStoreStatus &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          foreignKeysEnabled == other.foreignKeysEnabled;
}
