// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Stable entry point used by generated Flutter bindings to verify the v1 API.
Future<RuntimeApiVersion> runtimeApiVersion() =>
    RustLib.instance.api.crateApiRuntimeContractsRuntimeApiVersion();

/// Contract-only round trip used by binding and serialization tests.
///
/// This is deliberately policy-free; planner implementations are introduced
/// in a later milestone.
Future<InferenceRequest> runtimeContractsRoundTrip({
  required InferenceRequest request,
}) => RustLib.instance.api.crateApiRuntimeContractsRuntimeContractsRoundTrip(
  request: request,
);

Future<InferenceIr> runtimeIrRoundTrip({required InferenceIr ir}) =>
    RustLib.instance.api.crateApiRuntimeContractsRuntimeIrRoundTrip(ir: ir);

Future<RuntimeCapabilities> runtimeCapabilitiesRoundTrip({
  required RuntimeCapabilities capabilities,
}) => RustLib.instance.api.crateApiRuntimeContractsRuntimeCapabilitiesRoundTrip(
  capabilities: capabilities,
);

Future<RuntimeHealth> runtimeHealthRoundTrip({required RuntimeHealth health}) =>
    RustLib.instance.api.crateApiRuntimeContractsRuntimeHealthRoundTrip(
      health: health,
    );

/// Stable capability identifiers used by model selection.
enum CapabilityId { chat, vision, embedding, speech, reasoning, toolCalling }

/// Capability negotiation state.
enum CapabilityState { supported, unsupported, unknown }

/// Platform-neutral compute accelerator identifiers.
enum ComputeAccelerator {
  cpu,
  vulkan,
  metal,
  coreMl,
  appleNeuralEngine,
  nnapi,
  openCl,
  cuda,
}

/// Priority used by the inference scheduler.
enum ExecutionPriority { interactive, foreground, background, maintenance }

class ExecutionTrace {
  const ExecutionTrace({required this.entries});
  final List<ExecutionTraceEntry> entries;

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionTrace &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}

class ExecutionTraceEntry {
  const ExecutionTraceEntry({
    required this.sequence,
    required this.event,
    required this.elapsedMs,
  });
  final int sequence;
  final ExecutionTraceEvent event;
  final BigInt elapsedMs;

  @override
  int get hashCode => sequence.hashCode ^ event.hashCode ^ elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionTraceEntry &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          event == other.event &&
          elapsedMs == other.elapsedMs;
}

/// Stable lifecycle and execution trace events shared by every backend.
enum ExecutionTraceEvent {
  initializing,
  ready,
  generationStarted,
  firstToken,
  streaming,
  generationFinished,
  generationFailed,
  shuttingDown,
  stopped,
}

/// Immutable backend-neutral intermediate representation.
class InferenceIr {
  const InferenceIr({
    required this.runtime,
    required this.accelerator,
    required this.modelId,
    required this.contextTokens,
    required this.outputTokens,
    required this.temperature,
    required this.topK,
    required this.topP,
    required this.priority,
  });
  final RuntimeId runtime;
  final ComputeAccelerator accelerator;
  final String modelId;
  final int contextTokens;
  final int outputTokens;
  final double temperature;
  final int topK;
  final double topP;
  final ExecutionPriority priority;

  @override
  int get hashCode =>
      runtime.hashCode ^
      accelerator.hashCode ^
      modelId.hashCode ^
      contextTokens.hashCode ^
      outputTokens.hashCode ^
      temperature.hashCode ^
      topK.hashCode ^
      topP.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InferenceIr &&
          runtimeType == other.runtimeType &&
          runtime == other.runtime &&
          accelerator == other.accelerator &&
          modelId == other.modelId &&
          contextTokens == other.contextTokens &&
          outputTokens == other.outputTokens &&
          temperature == other.temperature &&
          topK == other.topK &&
          topP == other.topP &&
          priority == other.priority;
}

/// Immutable request entering the planner.
class InferenceRequest {
  const InferenceRequest({
    required this.capability,
    required this.prompt,
    required this.priority,
    this.modelId,
  });
  final CapabilityId capability;
  final String prompt;
  final String? modelId;
  final ExecutionPriority priority;

  @override
  int get hashCode =>
      capability.hashCode ^
      prompt.hashCode ^
      modelId.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InferenceRequest &&
          runtimeType == other.runtimeType &&
          capability == other.capability &&
          prompt == other.prompt &&
          modelId == other.modelId &&
          priority == other.priority;
}

/// Stable public contract version.
enum RuntimeApiVersion { v1 }

/// Runtime capability declaration and negotiated feature states.
class RuntimeCapabilities {
  const RuntimeCapabilities({
    required this.contractVersion,
    required this.runtime,
    required this.streaming,
    required this.cancellation,
    required this.vision,
    required this.toolCalling,
    required this.grammar,
    required this.jsonMode,
  });
  final RuntimeApiVersion contractVersion;
  final RuntimeId runtime;
  final CapabilityState streaming;
  final CapabilityState cancellation;
  final CapabilityState vision;
  final CapabilityState toolCalling;
  final CapabilityState grammar;
  final CapabilityState jsonMode;

  @override
  int get hashCode =>
      contractVersion.hashCode ^
      runtime.hashCode ^
      streaming.hashCode ^
      cancellation.hashCode ^
      vision.hashCode ^
      toolCalling.hashCode ^
      grammar.hashCode ^
      jsonMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeCapabilities &&
          runtimeType == other.runtimeType &&
          contractVersion == other.contractVersion &&
          runtime == other.runtime &&
          streaming == other.streaming &&
          cancellation == other.cancellation &&
          vision == other.vision &&
          toolCalling == other.toolCalling &&
          grammar == other.grammar &&
          jsonMode == other.jsonMode;
}

/// Stable runtime failure identifiers.
enum RuntimeErrorCode {
  outOfMemory,
  modelMissing,
  runtimeUnavailable,
  backendUnavailable,
  initializationFailed,
  thermalLimit,
  storageFailure,
  permissionDenied,
  contextTooLarge,
  unsupportedModel,
  plannerFailure,
  timeout,
  cancelled,
  unknown,
}

/// Backend health snapshot.
class RuntimeHealth {
  const RuntimeHealth({required this.state, this.error, this.detail});
  final RuntimeHealthState state;
  final RuntimeErrorCode? error;
  final String? detail;

  @override
  int get hashCode => state.hashCode ^ error.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeHealth &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          error == other.error &&
          detail == other.detail;
}

/// Runtime lifecycle state shared by every backend.
enum RuntimeHealthState {
  created,
  initializing,
  ready,
  busy,
  recovering,
  lowMemory,
  thermallyLimited,
  unavailable,
  shuttingDown,
  stopped,
  failed,
}

/// Stable runtime identifiers.
enum RuntimeId { mock, liteRt, llamaCpp, mlx, onnx }

/// Data-driven registry input consumed by the pure planner.
class RuntimeRegistry {
  const RuntimeRegistry({
    required this.contractVersion,
    required this.runtimes,
  });
  final RuntimeApiVersion contractVersion;
  final List<RuntimeId> runtimes;

  @override
  int get hashCode => contractVersion.hashCode ^ runtimes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeRegistry &&
          runtimeType == other.runtimeType &&
          contractVersion == other.contractVersion &&
          runtimes == other.runtimes;
}

class TelemetryEvent {
  const TelemetryEvent({
    required this.sequence,
    required this.event,
    required this.elapsedMs,
    this.error,
  });
  final int sequence;
  final TelemetryEventKind event;
  final BigInt elapsedMs;
  final RuntimeErrorCode? error;

  @override
  int get hashCode =>
      sequence.hashCode ^ event.hashCode ^ elapsedMs.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelemetryEvent &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          event == other.event &&
          elapsedMs == other.elapsedMs &&
          error == other.error;
}

/// Typed telemetry event kinds. Emission is intentionally non-blocking.
enum TelemetryEventKind {
  runtimeStarted,
  runtimeReady,
  generationStarted,
  firstToken,
  generationFinished,
  generationFailed,
  runtimeStopped,
}
