// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_title`, `attribute_value`, `finish_programme`, `pending_programme`, `resolve_general_ref`
// These functions are ignored because they have generic arguments: `parse_xmltv_programmes_reader`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PendingProgramme`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<XmltvParseResult> parseXmltvProgrammes({
  required String content,
  required int maxProgrammes,
}) => RustLib.instance.api.crateApiXmltvParseXmltvProgrammes(
  content: content,
  maxProgrammes: maxProgrammes,
);

Future<XmltvParseResult> parseXmltvProgrammesFile({
  required String path,
  required int maxProgrammes,
}) => RustLib.instance.api.crateApiXmltvParseXmltvProgrammesFile(
  path: path,
  maxProgrammes: maxProgrammes,
);

class XmltvParseResult {
  const XmltvParseResult({required this.programmes, required this.stats});
  final List<XmltvProgramme> programmes;
  final XmltvParseStats stats;

  static Future<XmltvParseResult> default_() =>
      RustLib.instance.api.crateApiXmltvXmltvParseResultDefault();

  @override
  int get hashCode => programmes.hashCode ^ stats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XmltvParseResult &&
          runtimeType == other.runtimeType &&
          programmes == other.programmes &&
          stats == other.stats;
}

class XmltvParseStats {
  const XmltvParseStats({
    required this.programmeCount,
    required this.skippedProgrammeCount,
    required this.truncated,
  });
  final int programmeCount;
  final int skippedProgrammeCount;
  final bool truncated;

  static Future<XmltvParseStats> default_() =>
      RustLib.instance.api.crateApiXmltvXmltvParseStatsDefault();

  @override
  int get hashCode =>
      programmeCount.hashCode ^
      skippedProgrammeCount.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XmltvParseStats &&
          runtimeType == other.runtimeType &&
          programmeCount == other.programmeCount &&
          skippedProgrammeCount == other.skippedProgrammeCount &&
          truncated == other.truncated;
}

class XmltvProgramme {
  const XmltvProgramme({
    required this.channelId,
    required this.start,
    this.stop,
    this.title,
  });
  final String channelId;
  final String start;
  final String? stop;
  final String? title;

  @override
  int get hashCode =>
      channelId.hashCode ^ start.hashCode ^ stop.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XmltvProgramme &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          start == other.start &&
          stop == other.stop &&
          title == other.title;
}
