// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'meetings.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply_diarization_labels`, `emit_live_delta`, `emit_live_ir`, `ensure_speech_engine_for_live`, `ensure_speech_engine_for_requirement`, `live_fanout_path`, `lock`, `maybe_emit_live_degraded`, `provisional_speaker_label`, `read_live_intelligence_mode`, `register_speech_exit_guard`, `release_speech_on_process_exit`, `release_speech_resources`, `replace_speaker_enrollment_store`, `run_live_pipeline_step`, `sanitize_meeting_id`, `sarvam_edge_speech_model_path`, `spawn_live_worker`, `stop_live_worker`, `stored_final_processing_profile`, `stored_speech_requirement_inputs`, `transcript_segment_record`, `vocabulary_correct_stable`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EnrolledSpeakerRecord`, `Library`, `LiveSessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `airo_mind_whisper_delete_meeting`

/// Dart sets this before each file/batch transcription so the Model Manager
/// can honor the user's final-transcript quality preference.
void setFinalProcessingProfile({required FinalProcessingProfile profile}) =>
    RustLib.instance.api.crateApiMeetingsSetFinalProcessingProfile(
      profile: profile,
    );

/// Loads the speech model and opens the store. Safe to call again — a Flutter
/// hot restart runs it a second time, and refusing would make development
/// require a full relaunch.
///
/// A missing model is an ordinary error carrying the path, because on a real
/// device it is the most likely failure and the user can act on it.
Future<void> initialize({required MindConfig config}) =>
    RustLib.instance.api.crateApiMeetingsInitialize(config: config);

/// True once `initialize` has succeeded. Lets the UI show why it cannot record
/// instead of failing at the moment the user presses the button.
bool isReady() => RustLib.instance.api.crateApiMeetingsIsReady();

/// Sarvam Edge on-device ASR — true when public weights are installed (`#1664`).
///
/// Flip is automatic once `sarvam_edge_speech.onnx` is in the models directory
/// (future HF pin). Dev override: `AIRO_SARVAM_EDGE_SPEECH=1`.
bool sarvamEdgeSpeechAvailable() =>
    RustLib.instance.api.crateApiMeetingsSarvamEdgeSpeechAvailable();

/// Replaces the in-memory enrollment store used during diarization.
Future<void> syncSpeakerEnrollmentJson({required String raw}) =>
    RustLib.instance.api.crateApiMeetingsSyncSpeakerEnrollmentJson(raw: raw);

/// Speaker embedding for one transcript time range (#504).
///
/// Uses ECAPA when the optional ONNX file is installed; stub embedder otherwise.
Float32List embedSpeakerSegment({
  required String wavPath,
  required BigInt startMs,
  required BigInt endMs,
}) => RustLib.instance.api.crateApiMeetingsEmbedSpeakerSegment(
  wavPath: wavPath,
  startMs: startMs,
  endMs: endMs,
);

/// Re-transcribes one time range from a recording using maximum-quality
/// weights. Used by the adaptive planner's segment-level retry — only the
/// suspicious slice is reprocessed, not the whole file.
String transcribeRecordingRange({
  required String wavPath,
  required BigInt startMs,
  required BigInt endMs,
  String? language,
}) => RustLib.instance.api.crateApiMeetingsTranscribeRecordingRange(
  wavPath: wavPath,
  startMs: startMs,
  endMs: endMs,
  language: language,
);

/// Recording → transcript, streaming throughout.
///
/// Runs on a `flutter_rust_bridge` worker thread, never the Dart main isolate.
/// The caller takes the transcript on to generation, which lives in the other
/// library.
///
/// `language` is `#1664`'s per-recording language pin: a whisper.cpp
/// language code (`"en"`, `"hi"`, ...), or `None` to leave the engine on
/// auto-detect. Settings' "pin one or two expected languages" maps to Dart
/// always supplying the user's chosen primary language here — this call
/// accepts exactly one, because whisper.cpp itself has no "try either of
/// these" mode (see `TranscriptionOptions` in `airo_mind_core::engine`). A
/// "globally pinned" language is the same value passed on every call; there
/// is no separate global switch to keep in sync on the Rust side.
Stream<TranscriptEvent> transcribeRecording({
  required String wavPath,
  String? language,
}) => RustLib.instance.api.crateApiMeetingsTranscribeRecording(
  wavPath: wavPath,
  language: language,
);

/// Opens a live transcription session. Refuses before the mic opens when the
/// speech model cannot be admitted (`ADR-0025` §6.6).
Stream<TranscriptEvent> startLiveSession({
  required String meetingId,
  String? language,
}) => RustLib.instance.api.crateApiMeetingsStartLiveSession(
  meetingId: meetingId,
  language: language,
);

/// Interim platform shim: pushes PCM into the native ring. Not the public
/// contract — documented in `LIVE_CAPTURE_FAN_OUT.md` §Interim shim.
void pushLivePcm({required String sessionId, required List<int> samples}) =>
    RustLib.instance.api.crateApiMeetingsPushLivePcm(
      sessionId: sessionId,
      samples: samples,
    );

void pauseLiveSession({required String sessionId}) =>
    RustLib.instance.api.crateApiMeetingsPauseLiveSession(sessionId: sessionId);

void resumeLiveSession({required String sessionId}) => RustLib.instance.api
    .crateApiMeetingsResumeLiveSession(sessionId: sessionId);

/// Flushes stable hypotheses to `FINAL` and emits [`TranscriptEvent::TranscriptReady`].
///
/// When `audio_path` is supplied (the recorded file after stop), ECAPA/solo
/// diarization reconciles provisional live speaker lanes — same pass as
/// [`transcribe_recording`], without re-running ASR.
Future<void> stopLiveSession({required String sessionId, String? audioPath}) =>
    RustLib.instance.api.crateApiMeetingsStopLiveSession(
      sessionId: sessionId,
      audioPath: audioPath,
    );

/// Aborts a live session without persisting transcript output.
void cancelLiveSession({required String sessionId}) => RustLib.instance.api
    .crateApiMeetingsCancelLiveSession(sessionId: sessionId);

/// Makes a meeting durable and searchable, and persists its structured
/// transcript document. Returns the meeting's id.
///
/// Separate from transcription because the minutes come from the other library.
/// The ordering below is a contract, not an implementation detail: an index
/// entry for a meeting the store does not hold is a search result that opens
/// nothing. Keeping it here rather than in Dart is deliberate — the caller
/// sequences the pipeline, but it does not get to sequence durability.
///
/// `model` is the logical identity and version of whatever produced `minutes`
/// (`ADR-0018 §5`), supplied by the generation library. An LLM is not
/// deterministic across versions, so what produced a summary is stored, not
/// inferred later.
///
/// `segments` and `audio_path` are `#1629` Gap D: written to a per-meeting
/// `transcript.json` (`transcript_store`) after the flat `Meeting` record is
/// durable, so the ASR step is reproducible — which model produced these
/// segments, from which recording — independent of the append-only log's flat
/// string.
Future<String> saveMeeting({
  required String title,
  required BigInt recordedAtMs,
  required String transcript,
  required String minutes,
  required String model,
  required List<TranscriptSegmentRecord> segments,
  required String audioPath,
  required List<MeetingDecisionRecord> decisions,
  required List<MeetingActionItemRecord> actionItems,
  required List<MeetingMetricRecord> metrics,
}) => RustLib.instance.api.crateApiMeetingsSaveMeeting(
  title: title,
  recordedAtMs: recordedAtMs,
  transcript: transcript,
  minutes: minutes,
  model: model,
  segments: segments,
  audioPath: audioPath,
  decisions: decisions,
  actionItems: actionItems,
  metrics: metrics,
);

/// Reopens a meeting's structured transcript document — the segments, model
/// version and audio reference `save_meeting` persisted. `Ok(None)` for a
/// meeting saved before this feature shipped, or one with no matching id.
Future<TranscriptDocumentRecord?> getTranscript({required String meetingId}) =>
    RustLib.instance.api.crateApiMeetingsGetTranscript(meetingId: meetingId);

/// Stops the in-flight transcription at the next segment.
///
/// Only this library's job. Dart cancels generation through the other library —
/// two engines, two admission controls, two cancellations.
void cancelProcessing() =>
    RustLib.instance.api.crateApiMeetingsCancelProcessing();

/// Drops the speech Supervisor so whisper.cpp can release Metal buffers
/// before ggml's process-exit `ggml_metal_device` destructor runs.
///
/// Rust statics are never dropped, so without this `NSApplication terminate`
/// hits `GGML_ASSERT([rsets->data count] == 0)` in `ggml_metal_rsets_free`.
/// Safe to call when nothing is loaded. Dart reaches this through the
/// exported C symbol — a new FRB method would require regenerating the
/// bridge, and quit must work on the already-linked dylib.
Future<void> unloadSpeech() =>
    RustLib.instance.api.crateApiMeetingsUnloadSpeech();

/// Exported so Dart can drop the speech engine on Cmd-Q / SIGTERM while
/// AppKit Metal is still valid. Hidden ggml symbols stay unexported; this
/// is a `#[no_mangle]` cdylib entry like the FRB wire functions.
Future<void> airoMindWhisperUnloadSpeech() =>
    RustLib.instance.api.crateApiMeetingsAiroMindWhisperUnloadSpeech();

/// Every meeting, newest first.
Future<List<MeetingRecord>> listMeetings() =>
    RustLib.instance.api.crateApiMeetingsListMeetings();

/// Step 7 of the journey. Searches transcripts and minutes.
Future<List<SearchHit>> searchMeetings({required String query}) =>
    RustLib.instance.api.crateApiMeetingsSearchMeetings(query: query);

/// Step 8. Opens one meeting.
Future<MeetingRecord?> getMeeting({required String id}) =>
    RustLib.instance.api.crateApiMeetingsGetMeeting(id: id);

/// Drops a meeting from the append-only store and search index.
Future<bool> deleteMeeting({required String id}) =>
    RustLib.instance.api.crateApiMeetingsDeleteMeeting(id: id);

/// Final-transcript quality profile exposed to Dart for the adaptive planner.
enum FinalProcessingProfile { fast, balanced, maximumQuality }

/// Wire mirror of `airo_mind_core::MeetingActionItem`.
class MeetingActionItemRecord {
  final String id;
  final String task;

  /// `None` when the transcript named nobody -- never inferred, mirrored
  /// unchanged from `airo_mind_meeting::ir::ActionItem::owner`.
  final String? owner;
  final String? due;
  final MeetingActionStatus status;
  final List<String> evidenceSegmentIds;

  const MeetingActionItemRecord({
    required this.id,
    required this.task,
    this.owner,
    this.due,
    required this.status,
    required this.evidenceSegmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      task.hashCode ^
      owner.hashCode ^
      due.hashCode ^
      status.hashCode ^
      evidenceSegmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingActionItemRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          task == other.task &&
          owner == other.owner &&
          due == other.due &&
          status == other.status &&
          evidenceSegmentIds == other.evidenceSegmentIds;
}

/// Wire mirror of `airo_mind_core::ActionStatus`.
enum MeetingActionStatus { open, inProgress, done, blocked }

/// Wire mirror of `airo_mind_core::MeetingDecision`. `evidence_segment_ids`
/// resolves against `transcript.json` per `ADR-0022 §4` -- this record
/// carries only the ids, never the words, matching the IR's own privacy
/// discipline (`rust/airo_mind_meeting/src/ir.rs`'s "evidence is segment ids,
/// not snippets").
class MeetingDecisionRecord {
  final String id;
  final String statement;
  final MeetingDecisionStatus status;
  final List<String> evidenceSegmentIds;

  const MeetingDecisionRecord({
    required this.id,
    required this.statement,
    required this.status,
    required this.evidenceSegmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      statement.hashCode ^
      status.hashCode ^
      evidenceSegmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingDecisionRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          statement == other.statement &&
          status == other.status &&
          evidenceSegmentIds == other.evidenceSegmentIds;
}

/// Wire mirror of `airo_mind_core::DecisionStatus`.
enum MeetingDecisionStatus { proposed, agreed, rejected, deferred_ }

/// Wire mirror of `airo_mind_core::MeetingMetric`.
class MeetingMetricRecord {
  final String id;
  final String name;
  final String value;
  final List<String> evidenceSegmentIds;

  const MeetingMetricRecord({
    required this.id,
    required this.name,
    required this.value,
    required this.evidenceSegmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      value.hashCode ^
      evidenceSegmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingMetricRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          value == other.value &&
          evidenceSegmentIds == other.evidenceSegmentIds;
}

/// A stored meeting, flattened for the bridge.
///
/// Deliberately not `Meeting` re-exported: the wire contract and the storage
/// record are allowed to diverge, and coupling them means a storage change
/// becomes a Dart change.
class MeetingRecord {
  final String id;
  final String title;
  final BigInt recordedAt;
  final String transcript;
  final String minutes;
  final String model;

  /// `ADR-0022 §1`: the Meeting IR's decisions, action items and metrics,
  /// flattened onto the meeting record the same way every other field on
  /// this struct already is -- IR is not a sibling record with its own
  /// lifecycle, it rides `Meeting`'s.
  final List<MeetingDecisionRecord> decisions;
  final List<MeetingActionItemRecord> actionItems;
  final List<MeetingMetricRecord> metrics;

  const MeetingRecord({
    required this.id,
    required this.title,
    required this.recordedAt,
    required this.transcript,
    required this.minutes,
    required this.model,
    required this.decisions,
    required this.actionItems,
    required this.metrics,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      recordedAt.hashCode ^
      transcript.hashCode ^
      minutes.hashCode ^
      model.hashCode ^
      decisions.hashCode ^
      actionItems.hashCode ^
      metrics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          recordedAt == other.recordedAt &&
          transcript == other.transcript &&
          minutes == other.minutes &&
          model == other.model &&
          decisions == other.decisions &&
          actionItems == other.actionItems &&
          metrics == other.metrics;
}

/// Where the models and the store live. Supplied by Dart, which owns the
/// platform's notion of an application directory.
class MindConfig {
  /// Where the Model Manager looks. **Not** a model path — `ADR-0018 §4`
  /// says nothing above the Manager names a file, a quantisation or a
  /// runtime, and this type is above the Manager.
  final String modelsDir;
  final String storePath;

  /// Admission ceiling for the Supervisor (`C6`). A device that cannot afford
  /// the model is told so before anything allocates.
  final int memoryBudgetMb;

  /// `#1629`. Defaults to `EnglishOnly` on the Dart side, so every existing
  /// caller keeps today's behaviour unchanged.
  final SpeechLanguage speechLanguage;

  const MindConfig({
    required this.modelsDir,
    required this.storePath,
    required this.memoryBudgetMb,
    required this.speechLanguage,
  });

  @override
  int get hashCode =>
      modelsDir.hashCode ^
      storePath.hashCode ^
      memoryBudgetMb.hashCode ^
      speechLanguage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MindConfig &&
          runtimeType == other.runtimeType &&
          modelsDir == other.modelsDir &&
          storePath == other.storePath &&
          memoryBudgetMb == other.memoryBudgetMb &&
          speechLanguage == other.speechLanguage;
}

/// A search result, with the line that matched.
class SearchHit {
  final String meetingId;
  final String title;
  final BigInt recordedAt;
  final String snippet;

  const SearchHit({
    required this.meetingId,
    required this.title,
    required this.recordedAt,
    required this.snippet,
  });

  @override
  int get hashCode =>
      meetingId.hashCode ^
      title.hashCode ^
      recordedAt.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          meetingId == other.meetingId &&
          title == other.title &&
          recordedAt == other.recordedAt &&
          snippet == other.snippet;
}

/// Which speech model to resolve. Mirrors `airo_mind_core::models::
/// ModelLanguage` rather than re-exporting it: that type lives below the
/// Model Manager boundary (`ADR-0018 §4`), and the wire contract is allowed to
/// diverge from the storage/resolution type the same way `MeetingRecord`
/// already diverges from `Meeting`.
///
/// `#1629`: Hindi+English code-switching needs the multilingual weights: the
/// bundled `.en` model is architecturally incapable of any language but
/// English. Choosing `Multilingual` here only resolves a different registry
/// row — it does not download anything by itself, and `initialize` reports
/// `NotInstalled` naming the missing multilingual weight file the same way it
/// would for any other unresolved model (`ADR-0018 §4`: that name is the
/// Model Manager's to know, not this capability's).
///
/// Not to be confused with `TranscriptionOptions::language` (`#1664`), which
/// this field feeds but does not replace: `SpeechLanguage` picks *which
/// model* loads (English-only weights, or multilingual weights capable of
/// more than English); `TranscriptionOptions::language`, supplied per call to
/// `transcribe_recording`, pins *which language the loaded model decodes as*
/// for that one recording, or leaves it on auto-detect. A `Multilingual`
/// model with no language hint still auto-detects — this field alone does
/// not pin anything.
enum SpeechLanguage {
  englishOnly,
  multilingual;

  static Future<SpeechLanguage> default_() =>
      RustLib.instance.api.crateApiMeetingsSpeechLanguageDefault();
}

/// One live transcript update during an active session (`ADR-0025` §6.3).
class TranscriptDeltaRecord {
  final String sessionId;
  final String segmentId;
  final String? speakerLabel;
  final String text;
  final BigInt startMs;
  final BigInt endMs;
  final TranscriptSegmentStateWire state;

  const TranscriptDeltaRecord({
    required this.sessionId,
    required this.segmentId,
    this.speakerLabel,
    required this.text,
    required this.startMs,
    required this.endMs,
    required this.state,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      segmentId.hashCode ^
      speakerLabel.hashCode ^
      text.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptDeltaRecord &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          segmentId == other.segmentId &&
          speakerLabel == other.speakerLabel &&
          text == other.text &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          state == other.state;
}

/// A meeting's transcript, in the reproducible shape `#1629` Gap D asks for:
/// the segments that produced the flat transcript string, which speech model
/// produced them, and which audio file they came from.
class TranscriptDocumentRecord {
  final String meetingId;
  final String audioPath;
  final String modelVersion;
  final List<TranscriptSegmentRecord> segments;

  const TranscriptDocumentRecord({
    required this.meetingId,
    required this.audioPath,
    required this.modelVersion,
    required this.segments,
  });

  @override
  int get hashCode =>
      meetingId.hashCode ^
      audioPath.hashCode ^
      modelVersion.hashCode ^
      segments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptDocumentRecord &&
          runtimeType == other.runtimeType &&
          meetingId == other.meetingId &&
          audioPath == other.audioPath &&
          modelVersion == other.modelVersion &&
          segments == other.segments;
}

@freezed
sealed class TranscriptEvent with _$TranscriptEvent {
  const TranscriptEvent._();

  /// One transcript segment, as whisper produced it.
  const factory TranscriptEvent.transcribing({
    required TranscriptSegmentRecord segment,
  }) = TranscriptEvent_Transcribing;

  /// Live session hypothesis or commit (`PARTIAL` / `STABLE` / `FINAL`).
  const factory TranscriptEvent.delta({required TranscriptDeltaRecord delta}) =
      TranscriptEvent_Delta;

  /// The joined transcript, plus every segment that produced it, in order.
  /// The flat `text` stays for callers that only want to display it; the UI
  /// case that needs a fact to point back at an audio timestamp reads
  /// `segments` instead of re-deriving them.
  const factory TranscriptEvent.transcriptReady({
    required String text,
    required List<TranscriptSegmentRecord> segments,
  }) = TranscriptEvent_TranscriptReady;

  /// The user navigated away. Nothing was saved.
  const factory TranscriptEvent.cancelled() = TranscriptEvent_Cancelled;

  /// Ring overflow, thermal backoff, or another recoverable live degradation.
  const factory TranscriptEvent.degraded({required String message}) =
      TranscriptEvent_Degraded;

  /// One incremental Conversation IR fact (JSON of `ConversationIrEvent`).
  /// Evidence is a segment id, never raw audio (ADR-0022).
  const factory TranscriptEvent.conversationIr({required String json}) =
      TranscriptEvent_ConversationIr;
}

/// One transcript segment, with the evidence-grounding fields `#1657` needs:
/// a stable id and the audio timestamps whisper produced.
///
/// `id` is a sequence number scoped to this recording (`"s0"`, `"s1"`, …)
/// rather than a UUID — it is stable across the one transcription run that
/// produced it (segment 3 is always segment 3 for this recording) and free to
/// compute, which is all an evidence link back to an audio timestamp needs.
/// `start_ms`/`end_ms` are whisper's own segment timestamps
/// (`WhisperSpeechEngine`, `rust/airo_mind_whisper/src/whisper.rs`), carried
/// through rather than recomputed here.
class TranscriptSegmentRecord {
  final String id;
  final BigInt startMs;
  final BigInt endMs;
  final String text;

  /// Diarization label (`sp0`, `sp1`, …). None for legacy segments.
  final String? speakerLabel;

  const TranscriptSegmentRecord({
    required this.id,
    required this.startMs,
    required this.endMs,
    required this.text,
    this.speakerLabel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      text.hashCode ^
      speakerLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptSegmentRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text &&
          speakerLabel == other.speakerLabel;
}

/// Live transcript state for a segment (`PARTIAL` / `STABLE` / `FINAL`).
enum TranscriptSegmentStateWire { partial, stable, final_ }
