// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'meeting_intelligence.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `action_items_from_ir`, `decisions_from_ir`, `metrics_from_ir`, `mom_to_engine`, `runtime_to_engine`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SupervisorGenerationEngine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`, `generate`, `resource_request`, `stats`

/// Segments → validated Meeting IR → streaming MoM.
///
/// Requires `initialize` from `minutes` to have succeeded — this module shares
/// the same `Supervisor` slot.
Stream<MeetingIntelligenceEvent> processMeetingIntelligence({
  required String meetingId,
  required String title,
  required List<MeetingIntelligenceSegment> segments,
}) =>
    RustLib.instance.api.crateApiMeetingIntelligenceProcessMeetingIntelligence(
      meetingId: meetingId,
      title: title,
      segments: segments,
    );

/// Stops the in-flight meeting-intelligence job at the next engine checkpoint.
void cancelMeetingIntelligence() =>
    RustLib.instance.api.crateApiMeetingIntelligenceCancelMeetingIntelligence();

class MeetingActionItemRecord {
  final String id;
  final String task;
  final String? owner;
  final String? due;
  final MeetingActionStatus status;
  final List<String> evidenceSegmentIds;

  const MeetingActionItemRecord({
    required this.id,
    required this.task,
    this.owner,
    this.due,
    required this.status,
    required this.evidenceSegmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      task.hashCode ^
      owner.hashCode ^
      due.hashCode ^
      status.hashCode ^
      evidenceSegmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingActionItemRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          task == other.task &&
          owner == other.owner &&
          due == other.due &&
          status == other.status &&
          evidenceSegmentIds == other.evidenceSegmentIds;
}

enum MeetingActionStatus { open, inProgress, done, blocked }

class MeetingDecisionRecord {
  final String id;
  final String statement;
  final MeetingDecisionStatus status;
  final List<String> evidenceSegmentIds;

  const MeetingDecisionRecord({
    required this.id,
    required this.statement,
    required this.status,
    required this.evidenceSegmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      statement.hashCode ^
      status.hashCode ^
      evidenceSegmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingDecisionRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          statement == other.statement &&
          status == other.status &&
          evidenceSegmentIds == other.evidenceSegmentIds;
}

enum MeetingDecisionStatus { proposed, agreed, rejected, deferred_ }

@freezed
sealed class MeetingIntelligenceEvent with _$MeetingIntelligenceEvent {
  const MeetingIntelligenceEvent._();

  const factory MeetingIntelligenceEvent.extracting() =
      MeetingIntelligenceEvent_Extracting;
  const factory MeetingIntelligenceEvent.generating({required String text}) =
      MeetingIntelligenceEvent_Generating;
  const factory MeetingIntelligenceEvent.minutesReady({required String text}) =
      MeetingIntelligenceEvent_MinutesReady;
  const factory MeetingIntelligenceEvent.irReady({
    required List<MeetingDecisionRecord> decisions,
    required List<MeetingActionItemRecord> actionItems,
    required List<MeetingMetricRecord> metrics,
  }) = MeetingIntelligenceEvent_IrReady;
  const factory MeetingIntelligenceEvent.cancelled() =
      MeetingIntelligenceEvent_Cancelled;
}

class MeetingIntelligenceSegment {
  final String id;
  final BigInt startMs;
  final BigInt endMs;
  final String text;

  const MeetingIntelligenceSegment({
    required this.id,
    required this.startMs,
    required this.endMs,
    required this.text,
  });

  @override
  int get hashCode =>
      id.hashCode ^ startMs.hashCode ^ endMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingIntelligenceSegment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text;
}

class MeetingMetricRecord {
  final String id;
  final String name;
  final String value;
  final List<String> evidenceSegmentIds;

  const MeetingMetricRecord({
    required this.id,
    required this.name,
    required this.value,
    required this.evidenceSegmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      value.hashCode ^
      evidenceSegmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetingMetricRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          value == other.value &&
          evidenceSegmentIds == other.evidenceSegmentIds;
}
