// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'minutes.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `minutes_prompt`

/// Loads the generation model. Called on first use, not at startup: this
/// library is large and only minutes need it.
///
/// Safe to call again — a Flutter hot restart runs it a second time.
Future<void> initialize({required GenerationConfig config}) =>
    RustLib.instance.api.crateApiMinutesInitialize(config: config);

/// True once `initialize` has succeeded.
bool isReady() => RustLib.instance.api.crateApiMinutesIsReady();

/// What produced the minutes, for the meeting library to record.
///
/// Empty before `initialize`, which is a state the caller can act on rather
/// than an error: it means nothing has been generated yet.
String generationModelId() =>
    RustLib.instance.api.crateApiMinutesGenerationModelId();

/// Transcript → minutes, streaming throughout.
Stream<GenerationEvent> generateMinutes({required String transcript}) =>
    RustLib.instance.api.crateApiMinutesGenerateMinutes(transcript: transcript);

/// Stops the in-flight generation at the next token.
void cancelGeneration() =>
    RustLib.instance.api.crateApiMinutesCancelGeneration();

/// Where the models live and what the engine may spend.
class GenerationConfig {
  /// Where the Model Manager looks. **Not** a model path — `ADR-0018 §4`.
  final String modelsDir;

  /// Admission ceiling for the Supervisor (`C6`).
  final int memoryBudgetMb;

  const GenerationConfig({
    required this.modelsDir,
    required this.memoryBudgetMb,
  });

  @override
  int get hashCode => modelsDir.hashCode ^ memoryBudgetMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerationConfig &&
          runtimeType == other.runtimeType &&
          modelsDir == other.modelsDir &&
          memoryBudgetMb == other.memoryBudgetMb;
}

@freezed
sealed class GenerationEvent with _$GenerationEvent {
  const GenerationEvent._();

  /// One token, as llama produced it.
  const factory GenerationEvent.generating({required String text}) =
      GenerationEvent_Generating;
  const factory GenerationEvent.minutesReady({required String text}) =
      GenerationEvent_MinutesReady;

  /// The user navigated away. Nothing was saved.
  const factory GenerationEvent.cancelled() = GenerationEvent_Cancelled;
}
