// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'minutes.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `chosen_weight_path`, `install_generation`, `minutes_prompt`, `register_generation_exit_guard`, `release_generation_on_process_exit`, `release_generation_resources`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Loads the generation model. Called on first use, not at startup: this
/// library is large and only minutes need it.
///
/// Safe to call again — a Flutter hot restart runs it a second time.
Future<void> initialize({required GenerationConfig config}) =>
    RustLib.instance.api.crateApiMinutesInitialize(config: config);

/// True once `initialize` has loaded a generation engine.
bool isReady() => RustLib.instance.api.crateApiMinutesIsReady();

/// What produced the minutes, for the meeting library to record.
///
/// Empty before `initialize`, which is a state the caller can act on rather
/// than an error: it means nothing has been generated yet.
String generationModelId() =>
    RustLib.instance.api.crateApiMinutesGenerationModelId();

/// Transcript → minutes, streaming throughout.
///
/// `grammar` is a GBNF grammar (start symbol `root`) constraining the token
/// stream to a caller-chosen shape, or `None` for the model's normal
/// unconstrained Markdown output. It is plumbing, not policy: this function
/// does not know or care what the grammar encodes -- turning "Meeting IR as
/// JSON" into a concrete GBNF string is a capability decision for whichever
/// caller passes one in, not something minutes.rs decides.
Stream<GenerationEvent> generateMinutes({
  required String transcript,
  String? grammar,
}) => RustLib.instance.api.crateApiMinutesGenerateMinutes(
  transcript: transcript,
  grammar: grammar,
);

/// General text completion for assistant chat — prompt is used as-is (no
/// meeting-secretary wrapper). Shares the same generation engine as
/// [`generate_minutes`].
///
/// `grammar` is a GBNF grammar (start symbol `root`) constraining the token
/// stream, or `null` for unconstrained sampling.
Stream<GenerationEvent> generateCompletion({
  required String prompt,
  required int maxOutputTokens,
  String? grammar,
}) => RustLib.instance.api.crateApiMinutesGenerateCompletion(
  prompt: prompt,
  maxOutputTokens: maxOutputTokens,
  grammar: grammar,
);

/// Stops the in-flight generation at the next token.
void cancelGeneration() =>
    RustLib.instance.api.crateApiMinutesCancelGeneration();

/// Timing and memory from the most recently completed `generate_minutes`
/// call. All zero before anything has generated, or if `initialize` was
/// never called — a state the caller can act on rather than an error.
GenerationStats generationStats() =>
    RustLib.instance.api.crateApiMinutesGenerationStats();

/// Releases the loaded generation model. Safe to call when nothing is
/// loaded, and safe to call again after `initialize` reloads a model — this
/// only clears the Supervisor's generation slot, not the speech one (there
/// is none here) or the recorded `MODEL_ID`, so `generation_model_id`
/// continues to describe whatever was last generated until something new is.
///
/// Also the Metal-exit guard: Rust statics are never dropped, so without an
/// explicit unload the llama.cpp `ggml_metal_device` unique_ptr vector
/// destructor runs at `NSApplication terminate` while residency sets still
/// hold model buffers and `GGML_ASSERT([rsets->data count] == 0)` aborts.
void unloadGeneration() =>
    RustLib.instance.api.crateApiMinutesUnloadGeneration();

/// Where the models live and what the engine may spend.
class GenerationConfig {
  /// Directory for capability resolve, or a weight file the Dart Model
  /// Manager already chose. Minutes still pass a directory (`ADR-0018 §4`).
  /// Chat selection is a file, so the engine must load that file rather than
  /// asking resolve for Draft quality in the same folder.
  final String modelsDir;

  /// Admission ceiling for the Supervisor (`C6`).
  final int memoryBudgetMb;

  /// When true, resolve `ModelQuality::Standard` first (e.g. Sarvam-1 for
  /// Indic meetings). Falls back to `Draft` (Qwen) when
  /// `allow_compact_fallback` is true.
  final bool preferIndicGeneration;

  /// When false and Indic resolution fails, return the error instead of
  /// falling back to Qwen (`enhanced_indic` user preference).
  final bool allowCompactFallback;

  const GenerationConfig({
    required this.modelsDir,
    required this.memoryBudgetMb,
    required this.preferIndicGeneration,
    required this.allowCompactFallback,
  });

  @override
  int get hashCode =>
      modelsDir.hashCode ^
      memoryBudgetMb.hashCode ^
      preferIndicGeneration.hashCode ^
      allowCompactFallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerationConfig &&
          runtimeType == other.runtimeType &&
          modelsDir == other.modelsDir &&
          memoryBudgetMb == other.memoryBudgetMb &&
          preferIndicGeneration == other.preferIndicGeneration &&
          allowCompactFallback == other.allowCompactFallback;
}

@freezed
sealed class GenerationEvent with _$GenerationEvent {
  const GenerationEvent._();

  /// One token, as llama produced it.
  const factory GenerationEvent.generating({required String text}) =
      GenerationEvent_Generating;
  const factory GenerationEvent.minutesReady({required String text}) =
      GenerationEvent_MinutesReady;

  /// The user navigated away. Nothing was saved.
  const factory GenerationEvent.cancelled() = GenerationEvent_Cancelled;
}

/// `RuntimeStats`, crossing the FFI boundary. A separate wire type rather
/// than deriving FRB bindings directly on `airo_mind_core::RuntimeStats`:
/// that type lives in the domain-free runtime crate, and this crate's `api`
/// module is the one place a Dart-shaped mirror of a core type is expected to
/// live (same pattern `GenerationEvent` already follows for `GenerationChunk`).
class GenerationStats {
  final BigInt prefillMs;
  final int prefillTokens;
  final BigInt generationMs;
  final int generatedTokens;
  final double tokensPerSecond;
  final BigInt peakRssBytes;

  const GenerationStats({
    required this.prefillMs,
    required this.prefillTokens,
    required this.generationMs,
    required this.generatedTokens,
    required this.tokensPerSecond,
    required this.peakRssBytes,
  });

  @override
  int get hashCode =>
      prefillMs.hashCode ^
      prefillTokens.hashCode ^
      generationMs.hashCode ^
      generatedTokens.hashCode ^
      tokensPerSecond.hashCode ^
      peakRssBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerationStats &&
          runtimeType == other.runtimeType &&
          prefillMs == other.prefillMs &&
          prefillTokens == other.prefillTokens &&
          generationMs == other.generationMs &&
          generatedTokens == other.generatedTokens &&
          tokensPerSecond == other.tokensPerSecond &&
          peakRssBytes == other.peakRssBytes;
}
