// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `leak_engine_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelFetcher`, `ChannelSearchEngine`, `IoRequest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fetch`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `id`, `search`

/// Create a research service with Dart-injected search/fetch adapters.
Future<ResearchServiceHandle> createResearchService({
  required List<String> engineIds,
  required FutureOr<FrbSearchResponse> Function(String, FrbSearchRequest)
  search,
  required FutureOr<String> Function(String) fetch,
}) => RustLib.instance.api.crateApiResearchCreateResearchService(
  engineIds: engineIds,
  search: search,
  fetch: fetch,
);

String researchStart({
  required ResearchServiceHandle handle,
  required FrbResearchRequest request,
}) => RustLib.instance.api.crateApiResearchResearchStart(
  handle: handle,
  request: request,
);

FrbResearchJobState? researchStatus({
  required ResearchServiceHandle handle,
  required String jobId,
}) => RustLib.instance.api.crateApiResearchResearchStatus(
  handle: handle,
  jobId: jobId,
);

void researchPause({
  required ResearchServiceHandle handle,
  required String jobId,
}) => RustLib.instance.api.crateApiResearchResearchPause(
  handle: handle,
  jobId: jobId,
);

void researchResume({
  required ResearchServiceHandle handle,
  required String jobId,
}) => RustLib.instance.api.crateApiResearchResearchResume(
  handle: handle,
  jobId: jobId,
);

void researchCancel({
  required ResearchServiceHandle handle,
  required String jobId,
}) => RustLib.instance.api.crateApiResearchResearchCancel(
  handle: handle,
  jobId: jobId,
);

FrbResearchCheckpoint? researchCheckpoint({
  required ResearchServiceHandle handle,
  required String jobId,
}) => RustLib.instance.api.crateApiResearchResearchCheckpoint(
  handle: handle,
  jobId: jobId,
);

void researchRestore({
  required ResearchServiceHandle handle,
  required FrbResearchCheckpoint checkpoint,
}) => RustLib.instance.api.crateApiResearchResearchRestore(
  handle: handle,
  checkpoint: checkpoint,
);

String? researchReport({
  required ResearchServiceHandle handle,
  required String jobId,
}) => RustLib.instance.api.crateApiResearchResearchReport(
  handle: handle,
  jobId: jobId,
);

/// Run a admitted job to completion, streaming structured events.
Stream<FrbResearchEvent> researchRun({
  required ResearchServiceHandle handle,
  required String jobId,
  required List<String> knownSourceUrls,
}) => RustLib.instance.api.crateApiResearchResearchRun(
  handle: handle,
  jobId: jobId,
  knownSourceUrls: knownSourceUrls,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ResearchServiceHandle>>
abstract class ResearchServiceHandle implements RustOpaqueInterface {}

class FrbResearchCheckpoint {
  final String record;

  const FrbResearchCheckpoint({required this.record});

  @override
  int get hashCode => record.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbResearchCheckpoint &&
          runtimeType == other.runtimeType &&
          record == other.record;
}

class FrbResearchEvent {
  final FrbResearchEventKind kind;
  final String jobId;
  final String label;
  final String detail;

  const FrbResearchEvent({
    required this.kind,
    required this.jobId,
    required this.label,
    required this.detail,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ jobId.hashCode ^ label.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbResearchEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          jobId == other.jobId &&
          label == other.label &&
          detail == other.detail;
}

enum FrbResearchEventKind {
  jobAdmitted,
  planningStarted,
  intentClassified,
  planCreated,
  searchStarted,
  searchCompleted,
  sourceDiscovered,
  sourceFetched,
  sourceRejected,
  documentParsed,
  analyzingStarted,
  claimCreated,
  gapDetected,
  counterResearchStarted,
  conflictDetected,
  synthesisStarted,
  completed,
  failed,
  paused,
  cancelled,
}

enum FrbResearchJobState {
  created,
  planning,
  searching,
  collecting,
  analyzing,
  verifying,
  gapAnalysis,
  synthesizing,
  validating,
  completed,
  paused,
  cancelled,
  failed,
}

enum FrbResearchMode { quick, standard, deep, exhaustive }

class FrbResearchRequest {
  final String question;
  final FrbResearchMode mode;
  final FrbSearchPolicy policy;
  final String outputFormat;

  const FrbResearchRequest({
    required this.question,
    required this.mode,
    required this.policy,
    required this.outputFormat,
  });

  @override
  int get hashCode =>
      question.hashCode ^
      mode.hashCode ^
      policy.hashCode ^
      outputFormat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbResearchRequest &&
          runtimeType == other.runtimeType &&
          question == other.question &&
          mode == other.mode &&
          policy == other.policy &&
          outputFormat == other.outputFormat;
}

class FrbSearchHit {
  final String url;
  final String title;
  final String snippet;

  const FrbSearchHit({
    required this.url,
    required this.title,
    required this.snippet,
  });

  @override
  int get hashCode => url.hashCode ^ title.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbSearchHit &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          snippet == other.snippet;
}

enum FrbSearchPolicy {
  localOnly,
  privacyFirst,
  balanced,
  maximumQuality,
  academic,
}

class FrbSearchRequest {
  final String query;
  final int maxResults;

  const FrbSearchRequest({required this.query, required this.maxResults});

  @override
  int get hashCode => query.hashCode ^ maxResults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbSearchRequest &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          maxResults == other.maxResults;
}

class FrbSearchResponse {
  final String engineId;
  final List<FrbSearchHit> hits;

  const FrbSearchResponse({required this.engineId, required this.hits});

  @override
  int get hashCode => engineId.hashCode ^ hits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbSearchResponse &&
          runtimeType == other.runtimeType &&
          engineId == other.engineId &&
          hits == other.hits;
}
