name: platform_pipeline
description: Component for platform_pipeline
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  platform_provider:
    path: ../platform_provider
  platform_identity:
    path: ../platform_identity
  flutter:
    sdk: flutter
  platform_execution:
    path: ../platform_execution

dev_dependencies:
  platform_provider:
    path: ../platform_provider
  platform_identity:
    path: ../platform_identity
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
