#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GRADLE_FILE="$ROOT_DIR/app/android/app/build.gradle.kts"
TV_MANIFEST="$ROOT_DIR/app/android/app/src/tv/AndroidManifest.xml"
TV_PUBSPEC="$ROOT_DIR/app/pubspec_tv.yaml"
RESOURCE_KEEP_FILE="${AIRO_TV_RESOURCE_KEEP_FILE:-$ROOT_DIR/app/android/app/src/main/res/raw/keep.xml}"
PLUGIN_REGISTRANT="${AIRO_TV_PLUGIN_REGISTRANT:-$ROOT_DIR/app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java}"
MIN_TARGET_SDK="${AIRO_TV_MIN_TARGET_SDK:-34}"
TV_PACKAGE_NAME="${AIRO_TV_PACKAGE_NAME:-io.airo.app.tv}"

fail() {
  local message="$1"
  echo "::error::$message" >&2
  exit 1
}

target_sdk="$(sed -nE 's/^[[:space:]]*targetSdk[[:space:]]*=[[:space:]]*([0-9]+).*$/\1/p' "$GRADLE_FILE" | head -1)"
compile_sdk="$(sed -nE 's/^[[:space:]]*compileSdk[[:space:]]*=[[:space:]]*([0-9]+).*$/\1/p' "$GRADLE_FILE" | head -1)"

[[ -n "$target_sdk" ]] || fail "Unable to read targetSdk from $GRADLE_FILE"
[[ -n "$compile_sdk" ]] || fail "Unable to read compileSdk from $GRADLE_FILE"

if [[ "$target_sdk" -lt "$MIN_TARGET_SDK" ]]; then
  fail "Android TV targetSdk $target_sdk is below Google Play minimum $MIN_TARGET_SDK"
fi

if [[ "$compile_sdk" -lt "$target_sdk" ]]; then
  fail "compileSdk $compile_sdk is below targetSdk $target_sdk"
fi

grep -q 'android.software.leanback' "$TV_MANIFEST" || fail "TV manifest missing android.software.leanback feature"
grep -q 'android.hardware.touchscreen" android:required="false"' "$TV_MANIFEST" || fail "TV manifest must mark touchscreen optional"
grep -q 'android.intent.category.LEANBACK_LAUNCHER' "$TV_MANIFEST" || fail "TV manifest missing LEANBACK_LAUNCHER"
grep -q 'android:banner="@drawable/tv_banner"' "$TV_MANIFEST" || fail "TV manifest missing TV banner"
grep -q "\"tv\" -> \"$TV_PACKAGE_NAME\"" "$GRADLE_FILE" || fail "TV applicationId must be $TV_PACKAGE_NAME"
grep -A5 '^hooks:' "$TV_PUBSPEC" | grep -q 'source: system' ||
  fail "TV pubspec must use packaged/system SQLite instead of a release-time download"
grep -A6 '^hooks:' "$TV_PUBSPEC" | grep -q 'name: sqlite3' ||
  fail "TV pubspec must resolve the packaged libsqlite3 library"

# The registrant is generated per build and belongs to whichever flavour was
# built last, so on a developer machine it is usually the phone one. Enforcing
# TV rules against a phone registrant reports a TV regression that does not
# exist -- and the obvious "fix" would be to break the phone build. Detect that
# and say so, unless an explicit TV artifact was supplied, which is
# authoritative.
registrant_looks_like_tv() {
  # Phone-only plugins that the TV profile never pulls in.
  ! grep -qE 'GoogleMlKit|MlKit|FlutterContactsPlugin|ImageCompressPlugin' \
    "$PLUGIN_REGISTRANT"
}

[[ -f "$RESOURCE_KEEP_FILE" ]] || fail "Android resource keep file not found: $RESOURCE_KEEP_FILE"
grep -q 'tools:keep="@drawable/audio_service_\*"' "$RESOURCE_KEEP_FILE" ||
  fail "Android resource shrinker must retain audio_service media-control icons"

check_plugin_registrant() {
  [[ -f "$PLUGIN_REGISTRANT" ]] || fail "Generated plugin registrant not found: $PLUGIN_REGISTRANT"
  if [[ -z "${AIRO_TV_RELEASE_APK:-}" ]] && ! registrant_looks_like_tv; then
    echo "::notice::$PLUGIN_REGISTRANT was generated by a non-TV build (it lists phone-only plugins), so the TV registrant contract was not checked. Build the TV flavour (scripts/build-tv.sh) or set AIRO_TV_RELEASE_APK to enforce it."
    return 0
  fi
  grep -q 'VideoPlayerPlugin' "$PLUGIN_REGISTRANT" ||
    fail "TV registrant must include the enabled video_player Android plugin"
  if grep -qE 'MediaKitLibsAndroidVideoPlugin|media_kit_libs_android_video' "$PLUGIN_REGISTRANT"; then
    fail "TV registrant includes media_kit although its native libraries are excluded"
  fi
  echo "Checked TV plugin registrant: $PLUGIN_REGISTRANT"
}

check_apk_native_media_contract() {
  local apk="$1"
  command -v unzip >/dev/null 2>&1 || fail "unzip is required to inspect TV APK native libraries"

  local entries
  entries="$(unzip -Z1 "$apk")"
  if grep -Eq '(^|/)lib/[^/]+/(libmpv|libmediakitandroidhelper)\.so$' <<<"$entries"; then
    fail "video_player-only TV APK unexpectedly packages media_kit native libraries"
  fi
}

# The registrant is generated by the last build in the tree, so it is absent on
# a fresh checkout and belongs to whichever flavour was built most recently
# otherwise. Both facts are easy to misread as "the plugin contract is covered",
# so say which one happened instead of skipping in silence.
if [[ -f "$PLUGIN_REGISTRANT" || -n "${AIRO_TV_RELEASE_APK:-}" ]]; then
  check_plugin_registrant
else
  echo "::notice::No generated plugin registrant at $PLUGIN_REGISTRANT -- skipping the video_player/media_kit registrant contract. Build the TV flavour (scripts/build-tv.sh) or set AIRO_TV_RELEASE_APK to enforce it."
fi

if [[ -n "${AIRO_TV_RELEASE_APK:-}" ]]; then
  [[ -s "$AIRO_TV_RELEASE_APK" ]] || fail "Release APK not found or empty: $AIRO_TV_RELEASE_APK"
  check_apk_native_media_contract "$AIRO_TV_RELEASE_APK"
fi

if [[ -n "${AIRO_TV_RELEASE_AAB:-}" ]]; then
  [[ -s "$AIRO_TV_RELEASE_AAB" ]] || fail "Release AAB not found or empty: $AIRO_TV_RELEASE_AAB"
fi

echo "Airo TV release checks passed: compileSdk=$compile_sdk targetSdk=$target_sdk minRequired=$MIN_TARGET_SDK"
