import 'package:meta/meta.dart';

import '../llm/llm_client.dart';
import '../models/offline_model_info.dart';

enum LocalRuntimeKind { geminiNano, liteRtLm, gguf, mediaPipeWeb }

enum RuntimeBackend { cpu, gpu, npu }

/// Capabilities of a Dart-side [LocalInferenceRuntimeAdapter] for a given
/// offline model.
///
/// This is intentionally a separate type from `core_native`'s
/// `RuntimeCapabilities` (`packages/core_native/lib/src/api/runtime_contracts.dart`,
/// re-exported via `core_native.dart`). That type is generated by
/// flutter_rust_bridge from the Rust runtime contract crate ("This file is
/// automatically generated, so please do not edit it") and describes
/// tri-state (`CapabilityState.supported/unsupported/unknown`) negotiation
/// against a specific `RuntimeApiVersion` and `RuntimeId` at the native FFI
/// boundary. This class describes something narrower and purely
/// Dart-side: which in-process adapter (Gemini Nano, LiteRT-LM, GGUF,
/// MediaPipe web) can serve a given [OfflineModelInfo] before any request
/// reaches the Rust core, keyed by simple booleans and the accelerator
/// [RuntimeBackend]s available to that adapter. `core_native`'s bindings are
/// not yet wired into this selection path (see `feature_mind`'s crate for
/// the first end-to-end Rust integration), so importing the generated type
/// here would couple adapter selection to Rust build wiring this package
/// does not have. Re-evaluate merging these once `core_native` capability
/// negotiation actually drives local runtime selection.
@immutable
class RuntimeCapabilities {
  const RuntimeCapabilities({
    required this.supportedBackends,
    this.supportsStreaming = false,
    this.supportsImages = false,
    this.supportsAudio = false,
    this.supportsToolCalling = false,
    this.supportsSystemPrompt = true,
    this.supportsSpeculativeDecoding = false,
  });

  final Set<RuntimeBackend> supportedBackends;
  final bool supportsStreaming;
  final bool supportsImages;
  final bool supportsAudio;
  final bool supportsToolCalling;
  final bool supportsSystemPrompt;
  final bool supportsSpeculativeDecoding;
}

@immutable
class RuntimeGenerationRequest {
  const RuntimeGenerationRequest({
    required this.prompt,
    this.systemPrompt,
    this.requiresVision = false,
    this.requiresAudio = false,
    this.requiresToolCalling = false,
    this.localOnly = false,
  });

  final String prompt;
  final String? systemPrompt;
  final bool requiresVision;
  final bool requiresAudio;
  final bool requiresToolCalling;
  final bool localOnly;
}

abstract class LocalInferenceRuntimeAdapter implements LLMClient {
  LocalRuntimeKind get runtimeKind;

  Future<bool> supportsModel(OfflineModelInfo model);

  RuntimeCapabilities capabilitiesForModel(OfflineModelInfo model);

  Future<void> prepareModel({OfflineModelInfo? model});

  Future<String?> generateText(
    RuntimeGenerationRequest request, {
    OfflineModelInfo? model,
  });
}

class LocalInferenceRuntimeRegistry {
  LocalInferenceRuntimeRegistry({
    Iterable<LocalInferenceRuntimeAdapter>? adapters,
  }) : _adapters = [...?adapters];

  final List<LocalInferenceRuntimeAdapter> _adapters;

  List<LocalInferenceRuntimeAdapter> get adapters =>
      List.unmodifiable(_adapters);

  void register(LocalInferenceRuntimeAdapter adapter) {
    _adapters.removeWhere(
      (existing) => existing.runtimeKind == adapter.runtimeKind,
    );
    _adapters.add(adapter);
  }
}

extension LocalInferenceRuntimeRegistryAsync on LocalInferenceRuntimeRegistry {
  Future<List<LocalInferenceRuntimeAdapter>> supportedAdaptersForModel(
    OfflineModelInfo model,
  ) async {
    final supported = <LocalInferenceRuntimeAdapter>[];
    for (final adapter in adapters) {
      if (await adapter.supportsModel(model)) {
        supported.add(adapter);
      }
    }
    return supported;
  }
}
