// `deny`, not `forbid`. An FFI boundary is unsafe by construction -- the
// generated bridge dereferences pointers handed over by Dart -- and `forbid`
// cannot be lifted anywhere, including on generated code.
//
// The allowance is granted on exactly one module, `frb_generated`, which is
// machine-written and never edited. Every hand-written line in this crate is
// still denied unsafe, and `grep -rn "unsafe" src/ --exclude=frb_generated.rs`
// returning nothing is the check.
#![deny(unsafe_code)]
//! Airo Mind runtime — Supervisor and the inference engine boundary.
//!
//! Scope is `#1396`: execute **one** pipeline. Audio through a Speech Engine,
//! transcript through a Generation Engine. No plugin system, no generic engine
//! registry, no OCR/Vision/Translation/Retrieval.
//!
//! # What the frozen contracts already decided
//!
//! This crate implements them; it does not restate or redesign them.
//!
//! - **`C6`** — the Supervisor owns lifecycle, scheduling, cancellation, health
//!   and **memory/CPU/IO budgets**. Control plane only: no operation payload,
//!   no projection data, no key material passes through it.
//! - **`C5`** — a capability never calls an engine. It emits operations and
//!   reads projections. Nothing in this crate is reachable from a capability.
//! - **`I2` / `I4`** — an engine that writes files, emits operations, or
//!   updates projections is a defect. **Inference is pure**: input, output,
//!   resource request, nothing else.
//! - **`I7`** — streaming. An engine yields segments through a sink; it never
//!   returns a whole transcript, because a two-hour meeting does not fit the
//!   assumption that it would.
//! - **The runtime knows no domains.** There is no `Minutes` type here.
//!   `GenerationRequest` carries a prompt the *capability* built.

/// The Flutter capability surface and its generated bridge. Both are gated on
/// the real backends -- see `api`.
#[cfg(all(feature = "whisper", feature = "llama"))]
pub mod api;
#[cfg(all(feature = "whisper", feature = "llama"))]
#[allow(
    // The only unsafe in the crate. See the crate-level note above.
    unsafe_code,
    clippy::all,
    dead_code,
    unused_imports,
    non_snake_case,
    non_camel_case_types,
    missing_docs,
    clippy::needless_lifetimes
)]
// Generated by `flutter_rust_bridge_codegen`. Never edited by hand -- the
// generator overwrites it, so a fix made here is a fix that disappears.
mod frb_generated;

mod budget;
mod cancel;
mod engine;
mod search;
mod store;
mod supervisor;
/// WAV decoding for the capability layer. Private: a container format is an
/// input detail, not part of the runtime's surface.
///
/// Compiled even without the backends so its tests run in a CI job that does
/// not build whisper.cpp -- parsing a container is exactly the kind of thing
/// worth testing cheaply. Only `api` calls it, hence the conditional allow.
#[cfg_attr(not(all(feature = "whisper", feature = "llama")), allow(dead_code))]
mod wav;

#[cfg(feature = "llama")]
mod llama;
#[cfg(feature = "whisper")]
mod whisper;

pub use budget::{ResourceBudget, ResourceRequest};
pub use cancel::CancelToken;
pub use engine::{
    AudioInput, EngineError, GenerationChunk, GenerationEngine, GenerationRequest, SpeechEngine,
    TranscriptSegment,
};
pub use search::{Hit, SearchIndex};
pub use store::{Meeting, MeetingStore, StoreError};
pub use supervisor::{RuntimeError, Supervisor};

#[cfg(feature = "llama")]
pub use llama::LlamaGenerationEngine;
#[cfg(feature = "whisper")]
pub use whisper::WhisperSpeechEngine;
