// `deny`, not `forbid`. An FFI boundary is unsafe by construction -- the
// generated bridge dereferences pointers handed over by Dart -- and `forbid`
// cannot be lifted anywhere, including on generated code.
//
// The allowance is granted on exactly one module, `frb_generated`, which is
// machine-written and never edited. Every hand-written line in this crate is
// still denied unsafe, and `grep -rn "unsafe" src/ --exclude=frb_generated.rs`
// returning nothing is the check.
#![deny(unsafe_code)]
//! Airo Mind runtime — Supervisor and the inference engine boundary.
//!
//! Scope is `#1396`: execute **one** pipeline. Audio through a Speech Engine,
//! transcript through a Generation Engine. No plugin system, no generic engine
//! registry, no OCR/Vision/Translation/Retrieval.
//!
//! # What the frozen contracts already decided
//!
//! This crate implements them; it does not restate or redesign them.
//!
//! - **`C6`** — the Supervisor owns lifecycle, scheduling, cancellation, health
//!   and **memory/CPU/IO budgets**. Control plane only: no operation payload,
//!   no projection data, no key material passes through it.
//! - **`C5`** — a capability never calls an engine. It emits operations and
//!   reads projections. Nothing in this crate is reachable from a capability.
//! - **`I2` / `I4`** — an engine that writes files, emits operations, or
//!   updates projections is a defect. **Inference is pure**: input, output,
//!   resource request, nothing else.
//! - **`I7`** — streaming. An engine yields segments through a sink; it never
//!   returns a whole transcript, because a two-hour meeting does not fit the
//!   assumption that it would.
//! - **The runtime knows no domains.** There is no `Minutes` type here.
//!   `GenerationRequest` carries a prompt the *capability* built.

/// The Flutter capability surface and its generated bridge. Both are gated on
/// the real backends -- see `api`.
#[cfg(all(feature = "whisper", feature = "llama"))]
pub mod api;
#[cfg(all(feature = "whisper", feature = "llama"))]
#[allow(
    // The only unsafe in the crate. See the crate-level note above.
    unsafe_code,
    clippy::all,
    dead_code,
    unused_imports,
    non_snake_case,
    non_camel_case_types,
    missing_docs,
    clippy::needless_lifetimes
)]
// Generated by `flutter_rust_bridge_codegen`. Never edited by hand -- the
// generator overwrites it, so a fix made here is a fix that disappears.
mod frb_generated;

// The backend-free half of the runtime now lives in `airo_mind_core`, so that
// the whisper and llama engines can be linked into separate cdylibs without
// duplicating it. See that crate's root for why they must be separate at all.
//
// These are `use`, not `mod`: `crate::wav::decode` and friends keep resolving
// exactly as before, so moving the files did not touch a single call site.
#[cfg_attr(
    not(all(feature = "whisper", feature = "llama")),
    allow(unused_imports)
)]
pub(crate) use airo_mind_core::{budget, cancel, engine, models, wav};

/// Re-exported for `api::setup`, which is the only caller outside `models`.
#[cfg(all(feature = "whisper", feature = "llama"))]
pub(crate) use airo_mind_core::file_digest as digest_file;

#[cfg(feature = "llama")]
mod llama;
#[cfg(feature = "whisper")]
mod whisper;

pub use airo_mind_core::{
    AudioInput, CancelToken, EngineError, GenerationChunk, GenerationEngine, GenerationRequest,
    Hit, Meeting, MeetingStore, ResourceBudget, ResourceRequest, RuntimeError, SearchIndex,
    SpeechEngine, StoreError, Supervisor, TranscriptSegment,
};

#[cfg(feature = "llama")]
pub use llama::LlamaGenerationEngine;
#[cfg(feature = "whisper")]
pub use whisper::WhisperSpeechEngine;
