name: platform_engine_litert
description: LiteRT backend for AIRO.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  platform_pipeline:
    path: ../platform_pipeline
  flutter:
    sdk: flutter
  platform_engine_sdk:
    path: ../platform_engine_sdk
  platform_delegates:
    path: ../platform_delegates

  mocktail: ^1.0.3
  platform_engine_testkit:
    path: ../platform_engine_testkit
  platform_downloads:
    path: ../platform_downloads
dev_dependencies:
  platform_pipeline:
    path: ../platform_pipeline
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
