// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mind.dart';
import 'api/setup.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -425026298;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'airo_mind_runtime',
        ioDirectory: '../../rust/airo_mind_runtime/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiMindCancelProcessing();

  Future<MeetingRecord?> crateApiMindGetMeeting({required String id});

  Future<void> crateApiMindInitialize({required MindConfig config});

  bool crateApiMindIsReady();

  Future<List<MeetingRecord>> crateApiMindListMeetings();

  Stream<ProcessingEvent> crateApiMindProcessRecording({
    required String wavPath,
    required String title,
    required BigInt recordedAtMs,
  });

  Future<List<RequiredModel>> crateApiSetupRequiredModels();

  Future<List<SearchHit>> crateApiMindSearchMeetings({required String query});

  Future<List<InstalledModel>> crateApiSetupVerifyInstalledModels({
    required String modelsDir,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiMindCancelProcessing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMindCancelProcessingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMindCancelProcessingConstMeta =>
      const TaskConstMeta(debugName: "cancel_processing", argNames: []);

  @override
  Future<MeetingRecord?> crateApiMindGetMeeting({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_meeting_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMindGetMeetingConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMindGetMeetingConstMeta =>
      const TaskConstMeta(debugName: "get_meeting", argNames: ["id"]);

  @override
  Future<void> crateApiMindInitialize({required MindConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mind_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMindInitializeConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMindInitializeConstMeta =>
      const TaskConstMeta(debugName: "initialize", argNames: ["config"]);

  @override
  bool crateApiMindIsReady() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMindIsReadyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMindIsReadyConstMeta =>
      const TaskConstMeta(debugName: "is_ready", argNames: []);

  @override
  Future<List<MeetingRecord>> crateApiMindListMeetings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_meeting_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMindListMeetingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMindListMeetingsConstMeta =>
      const TaskConstMeta(debugName: "list_meetings", argNames: []);

  @override
  Stream<ProcessingEvent> crateApiMindProcessRecording({
    required String wavPath,
    required String title,
    required BigInt recordedAtMs,
  }) {
    final sink = RustStreamSink<ProcessingEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(wavPath, serializer);
            sse_encode_String(title, serializer);
            sse_encode_u_64(recordedAtMs, serializer);
            sse_encode_StreamSink_processing_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMindProcessRecordingConstMeta,
          argValues: [wavPath, title, recordedAtMs, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMindProcessRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "process_recording",
        argNames: ["wavPath", "title", "recordedAtMs", "sink"],
      );

  @override
  Future<List<RequiredModel>> crateApiSetupRequiredModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_required_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetupRequiredModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupRequiredModelsConstMeta =>
      const TaskConstMeta(debugName: "required_models", argNames: []);

  @override
  Future<List<SearchHit>> crateApiMindSearchMeetings({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_hit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMindSearchMeetingsConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMindSearchMeetingsConstMeta =>
      const TaskConstMeta(debugName: "search_meetings", argNames: ["query"]);

  @override
  Future<List<InstalledModel>> crateApiSetupVerifyInstalledModels({
    required String modelsDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelsDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_installed_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetupVerifyInstalledModelsConstMeta,
        argValues: [modelsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupVerifyInstalledModelsConstMeta =>
      const TaskConstMeta(
        debugName: "verify_installed_models",
        argNames: ["modelsDir"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ProcessingEvent> dco_decode_StreamSink_processing_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MeetingRecord dco_decode_box_autoadd_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_meeting_record(raw);
  }

  @protected
  MindConfig dco_decode_box_autoadd_mind_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mind_config(raw);
  }

  @protected
  InstalledModel dco_decode_installed_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InstalledModel(
      fileName: dco_decode_String(arr[0]),
      present: dco_decode_bool(arr[1]),
      verified: dco_decode_bool(arr[2]),
      detail: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<InstalledModel> dco_decode_list_installed_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_installed_model).toList();
  }

  @protected
  List<MeetingRecord> dco_decode_list_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_meeting_record).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RequiredModel> dco_decode_list_required_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_required_model).toList();
  }

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit).toList();
  }

  @protected
  MeetingRecord dco_decode_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MeetingRecord(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      recordedAt: dco_decode_u_64(arr[2]),
      transcript: dco_decode_String(arr[3]),
      minutes: dco_decode_String(arr[4]),
      model: dco_decode_String(arr[5]),
    );
  }

  @protected
  MindConfig dco_decode_mind_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MindConfig(
      modelsDir: dco_decode_String(arr[0]),
      storePath: dco_decode_String(arr[1]),
      memoryBudgetMb: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  MeetingRecord? dco_decode_opt_box_autoadd_meeting_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_meeting_record(raw);
  }

  @protected
  ProcessingEvent dco_decode_processing_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ProcessingEvent_Transcribing(text: dco_decode_String(raw[1]));
      case 1:
        return ProcessingEvent_TranscriptReady(text: dco_decode_String(raw[1]));
      case 2:
        return ProcessingEvent_Generating(text: dco_decode_String(raw[1]));
      case 3:
        return ProcessingEvent_MinutesReady(text: dco_decode_String(raw[1]));
      case 4:
        return ProcessingEvent_Saved(meetingId: dco_decode_String(raw[1]));
      case 5:
        return ProcessingEvent_Cancelled();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RequiredModel dco_decode_required_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RequiredModel(
      fileName: dco_decode_String(arr[0]),
      sizeBytes: dco_decode_u_64(arr[1]),
      sha256: dco_decode_String(arr[2]),
    );
  }

  @protected
  SearchHit dco_decode_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchHit(
      meetingId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      recordedAt: dco_decode_u_64(arr[2]),
      snippet: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ProcessingEvent> sse_decode_StreamSink_processing_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MeetingRecord sse_decode_box_autoadd_meeting_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_meeting_record(deserializer));
  }

  @protected
  MindConfig sse_decode_box_autoadd_mind_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mind_config(deserializer));
  }

  @protected
  InstalledModel sse_decode_installed_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_present = sse_decode_bool(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return InstalledModel(
      fileName: var_fileName,
      present: var_present,
      verified: var_verified,
      detail: var_detail,
    );
  }

  @protected
  List<InstalledModel> sse_decode_list_installed_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InstalledModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_installed_model(deserializer));
    }
    return ans_;
  }

  @protected
  List<MeetingRecord> sse_decode_list_meeting_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MeetingRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_meeting_record(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RequiredModel> sse_decode_list_required_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RequiredModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_required_model(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit(deserializer));
    }
    return ans_;
  }

  @protected
  MeetingRecord sse_decode_meeting_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_recordedAt = sse_decode_u_64(deserializer);
    var var_transcript = sse_decode_String(deserializer);
    var var_minutes = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    return MeetingRecord(
      id: var_id,
      title: var_title,
      recordedAt: var_recordedAt,
      transcript: var_transcript,
      minutes: var_minutes,
      model: var_model,
    );
  }

  @protected
  MindConfig sse_decode_mind_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelsDir = sse_decode_String(deserializer);
    var var_storePath = sse_decode_String(deserializer);
    var var_memoryBudgetMb = sse_decode_u_32(deserializer);
    return MindConfig(
      modelsDir: var_modelsDir,
      storePath: var_storePath,
      memoryBudgetMb: var_memoryBudgetMb,
    );
  }

  @protected
  MeetingRecord? sse_decode_opt_box_autoadd_meeting_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_meeting_record(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProcessingEvent sse_decode_processing_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return ProcessingEvent_Transcribing(text: var_text);
      case 1:
        var var_text = sse_decode_String(deserializer);
        return ProcessingEvent_TranscriptReady(text: var_text);
      case 2:
        var var_text = sse_decode_String(deserializer);
        return ProcessingEvent_Generating(text: var_text);
      case 3:
        var var_text = sse_decode_String(deserializer);
        return ProcessingEvent_MinutesReady(text: var_text);
      case 4:
        var var_meetingId = sse_decode_String(deserializer);
        return ProcessingEvent_Saved(meetingId: var_meetingId);
      case 5:
        return ProcessingEvent_Cancelled();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RequiredModel sse_decode_required_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    return RequiredModel(
      fileName: var_fileName,
      sizeBytes: var_sizeBytes,
      sha256: var_sha256,
    );
  }

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_meetingId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_recordedAt = sse_decode_u_64(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    return SearchHit(
      meetingId: var_meetingId,
      title: var_title,
      recordedAt: var_recordedAt,
      snippet: var_snippet,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_processing_event_Sse(
    RustStreamSink<ProcessingEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_processing_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_meeting_record(
    MeetingRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_meeting_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mind_config(
    MindConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mind_config(self, serializer);
  }

  @protected
  void sse_encode_installed_model(
    InstalledModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_bool(self.present, serializer);
    sse_encode_bool(self.verified, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_list_installed_model(
    List<InstalledModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_installed_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_meeting_record(
    List<MeetingRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_meeting_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_required_model(
    List<RequiredModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_required_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_meeting_record(MeetingRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.recordedAt, serializer);
    sse_encode_String(self.transcript, serializer);
    sse_encode_String(self.minutes, serializer);
    sse_encode_String(self.model, serializer);
  }

  @protected
  void sse_encode_mind_config(MindConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelsDir, serializer);
    sse_encode_String(self.storePath, serializer);
    sse_encode_u_32(self.memoryBudgetMb, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_meeting_record(
    MeetingRecord? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_meeting_record(self, serializer);
    }
  }

  @protected
  void sse_encode_processing_event(
    ProcessingEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ProcessingEvent_Transcribing(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case ProcessingEvent_TranscriptReady(text: final text):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
      case ProcessingEvent_Generating(text: final text):
        sse_encode_i_32(2, serializer);
        sse_encode_String(text, serializer);
      case ProcessingEvent_MinutesReady(text: final text):
        sse_encode_i_32(3, serializer);
        sse_encode_String(text, serializer);
      case ProcessingEvent_Saved(meetingId: final meetingId):
        sse_encode_i_32(4, serializer);
        sse_encode_String(meetingId, serializer);
      case ProcessingEvent_Cancelled():
        sse_encode_i_32(5, serializer);
    }
  }

  @protected
  void sse_encode_required_model(RequiredModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.meetingId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.recordedAt, serializer);
    sse_encode_String(self.snippet, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
