name: audio_service
description: Stub implementation of audio_service for TV builds
version: 0.18.18
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0

