name: audio_service
description: Stub implementation of audio_service for TV builds
version: 0.18.18
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.7'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
